### ISSUE TITLE
E-mail not active

### ISSUE THREAD

**Issue by dobrinkamladenova** [carvel-dev/kapp-controller#100]
Hello, I contacted OSSContributions@vmware.com, but the e-mail is not active anymore. Can you please tell me how to reach out to VMware in case I have a more generic question related to open source contributions?

**Comment by cari-lynn** [comment]
Hey @dobrinkamladenova, I'm looking for a email that can help with general questions. In the meantime, what kinds of questions are you looking for answers for? Knowing that may help me point you in the right direction.

**Comment by cari-lynn** [comment]
A member of our Open Source Program Office offered to be a point of contact to route general questions. You can reach out to Dirk H. dirkhh@vmware.com and he will point you in the right direction.

**Comment by dobrinkamladenova** [comment]
Thank you very much, @cari-lynn!
