### ISSUE TITLE
`kctrl`: When adding a package repo, include option to create the namespace if not existing

### ISSUE THREAD

**Issue by ThomasVitale** [carvel-dev/kapp-controller#1001]
**Describe the problem/challenge you have**
When I add a Carvel package repository to a cluster, I first need to create a dedicated namespace explicitly.

1. `kubectl create namespace kadras-packages`
2. `kctrl package repository add -r kadras-repo --url ghcr.io/arktonix/kadras-packages:0.5.1 -n kadras-packages`

**Describe the solution you'd like**
I'd like to skip the explicit creation of the namespace and have it created as part of the `kctrl package` command, similar to how the `helm` CLI works. For example, the functionality could be enabled via a `--create-namespace` flag.

`kctrl package repository add -r kadras-repo --url ghcr.io/arktonix/kadras-packages:0.5.1 -n kadras-packages --create-namespace`

**Anything else you would like to add:**
One of the reasons for this feature request is to make the onboarding experience even simpler when introducing people to Carvel packaging or when using a Carvel metapackage as the foundation of projects/tutorials relying on a Carvel-based platform.

With this feature, that would result in three operations rather than four:

1. deploy kapp-controller
2. add the package repository
3. install the package

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment]
I agree that this is definitely useful in terms of reducing the number of commands that need to be run to add repositories or install packages but I remember that we have had some similar discussion but I can't seem to recall the details. 
cc @100mik @cppforlife

**Comment by 100mik** [comment]
I think it is thoughtful that we are doing this only for PackageRepositories. As _generally_ they would reside any installs will reside in the same namespace that is already created.

There is a case for doing this for installs as well since a PackageRepository might be added to the global namespace. But I think a good first step would be to do this _only_ for repository adds as it is the more common use case.

**Comment by ThomasVitale** [comment]
@100mik as agreed, I'm starting working on this. Should we go with the `--create-namespace` flag or would you prefer a different naming strategy?

**Comment by 100mik** [comment]
I cannot think of a name that's better, so I believe that is what we would go with 🚀
