### ISSUE TITLE
Restricted User/Group impersonation for actualising an `App`

### ISSUE THREAD

**Issue by absoludity** [carvel-dev/kapp-controller#101]
**Describe the problem/challenge you have**

Some Kubernetes applications carry out all interactions with the Kubernetes cluster *as the authenticated user* (ie. the user who is interacting with the cluster). `kubectl` is one example and Kubeapps (my context) is another.  This is generally the case for synchronous actions (such as creating or deleting resources synchronously) but is also possible in other scenarios.

Kapp controller, on the other hand, actualises an `App` into the relevant resources asynchronously. As I understand it, kapp controller enables two methods for authorization of the actual `App` installation: [either a service account or a secret with kubeconfig contents](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/docs/security-model.md). I assume this means that all interaction with the cluster during an install is done with the specified credential, but it's not possible for that interaction during install to be done with the App author's user or group RBAC.

**Describe the solution you'd like**

I would like to know if a third model could be considered, where the user creating the `App` resource (the author) as well as the (potentially filtered) set of groups to which they belong, is recorded when the `App` CR is created, so that kapp-controller can do the actualization by *impersonating* the author of the `App`.

This would have a couple of implications.

## Limited User/Group impersonation

The most important implication is that kapp-controller in this mode (which would not be enabled by default) would need to have RBAC to [impersonate specific users and/or groups](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation). Note that this does not mean kapp-controller can impersonate `cluster-admin` (unless the RBAC allows that), since impersonation header RBAC can be configured to restrict impersonation to a limited set of users or groups (see previous link).

## Dynamic Admission Controller

To record the username and (filtered) groups of the user creating the `App` resource, a [dynamic admission controller](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) would need to be configured with kapp-controller. Specifically this would be a mutating webhook which updates the request with the username and (filtered) groups of the user creating the `App`.

I say filtered only because it'd be sane to limit the group impersonation of kapp-controller to some configurable set and so for privacy only store those relevant groups on the `App` (e.g. `team-a-devs`, `team-b-ops`, etc.)

**Anything else you would like to add:**

The purpose of the stored user/groups would be only for impersonation during the `App` actualisation and upgrade etc. (ie. any communication kapp-controller initiates with the k8s api server on behalf of that app - exactly where the service account / cluster secret is used today). It is explicitly *not* some extra auth for those objects.

So, for example, anyone with RBAC to delete the `App` resource will be able to initiate the deletion. Similarly, anyone with RBAC would be able to update the `App` resource would be able to do so. We would need to think carefully about a simple yet consistent way to handle this. For example, when updating an app, the admission controller could mutate to overwrite the username (bad) or could mutate to update a separate field with the requesting user which can be used for the impersonation of that action (whether update or delete or whatever). This would need some thought.

So... thoughts? :) (and thanks either way for considering both this and #99 - I realise neither is trivial).

**Comment by cppforlife** [comment]
@absoludity i have two concerns:

- since App CR represents continuously updating application, what does it mean to use submitting account for long period of time? do all auth methods result in a service account (im not sure, what happens when user auths via third party system, do they have service account?) what happens when multiple actors are interacting with App CR, eg two different users and another controller.

- i havent seen anyone else do this in Kubernetes space, which is a little bit concerning. resources in k8s are not tied in any way to their creators through standard k8s apis. it feels like we are not using system the way it was intended to be used.

**Comment by absoludity** [comment]
> @absoludity i have two concerns:
> 
>     * since App CR represents continuously updating application, what does it mean to use submitting account for long period of time? do all auth methods result in a service account (im not sure, what happens when user auths via third party system, do they have service account?)

No, there is no service account. When you interact via `kubectl` there is no service account, but instead your request is carried out with a TLS client-authentication certificate ([more details](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#users-in-kubernetes), I realise you know all of this, but just explaining generally why). If the APIServer recognises the certificate it then trusts the encoded user/groups on the cert and matches those with any matching user RBAC. No service accounts involved.

It works in a similar way when a cluster is setup with OIDC parameters:  in this case your request has an `Authorization` header with a signed jwt-token as the value which the apiserver can verify as having been issued by an identity provider it trusts (by verifying the signature). Once verified, the API server accepts the user and groups identified by the token and matches those with any matching user RBAC - no service accounts involved, only users/groups. ([more details](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens))

This works really well for synchronous requests from a user (and is what many apps, Kubeapps included, use). But you are 100% correct that it is odd for an async task/job/controller running on the cluster *after* the user interaction has ended, to still use user authentication.

> what happens when multiple actors are interacting with App CR, eg two different users

See my "Anything else you would like to add" section in the description - I think that's exactly the case I was identifying there (a different user updating or deleting the app than the user who created it). It does indeed feel awkward though - but your questions have prompted a variation which could fit much more nicely...

> and another controller.

Not sure what you mean by another controller?

>     * i havent seen anyone else do this in Kubernetes space, which is a little bit concerning. resources in k8s are not tied in any way to their creators through standard k8s apis. it feels like we are not using system the way it was intended to be used.

Yes, I felt the same way when proposing it but couldn't see a different/better option for the use-case. It seems clear that user/group authentication is for synchronous requests from an actual user client... any apiserver interaction outside an actual user request lifecycle should use a service account. An obvious example is a k8s Job/CronJob which is created via *user* authentication, but it must specify a service account that will be used to create the pods asynchronously by the controller - just like kapp-controller.

So why is this coming up (sorry, I've described a solution above rather than describing what I need)? My use-case for kapp-controller is this:

* I have an application running on an OIDC-enabled cluster where users login with the configured Identity Provider.
* An authenticating user may have never used the cluster before, and for that matter, the cluster RBAC may not have anything matching the authenticating user necessarily, but
* the cluster RBAC matches a group to which the auth'd user belongs: `tanzu-devs`, which enables the sure to create an `App` CR for kapp-controller.

Now since the user has never used this cluster, even though they have authz to create an `App`, they know nothing of a service account they should use, nor should they be able to create a service account and bind it to some role or clusterrole of their choosing (that is the role of the cluster operator, not individual users). They shouldn't have to care about creating a service account - they've authenticated as themselves and the cluster knows what they can and cannot do. How can `kapp-controller` actualize the `App` on behalf of the *user* request?

Another solution could be that `kapp-controller` could be configured to match user/groups to service account names. A cluster operator can create service accounts for different teams, for example, and install a dynamic admission controller which, if enabled, mutates requests to create `App` resources by matching the user/group info with a configured service account and writing the service account? In fact, the admission controller would not even need to be part of kapp-controller initially.

If that makes more sense to you, I might take a look at that. This would allow *users* to create `App` resources such that the service account used is configured by an *operator*, not the user.

(BTW: if you have a process for feature requests that doesn't involve serial conversations on gh issues, such as a google doc or similar, just let me know :) )

**Comment by absoludity** [comment]
I'm going to close this issue since, after discussion, I agree that original request isn't something to consider. Additionally, given that a namespace always has a `default` service account and a user who can create a pod in a namespace will, for example, default to using that `default` service account, it seems this would be a better precedent to follow.

So for my use-case, if a user has authz to create an `App` in a specific repository, it will by default use the `default` service account. Furthermore, if the user has access to list serviceaccounts in the namespace, we can enable selecting from these.
