### ISSUE TITLE
Trigger reconcile on data value secret update

### ISSUE THREAD

**Issue by danniel1205** [carvel-dev/kapp-controller#102]
**Describe the problem/challenge you have**
As a user, I would like to reconfigure my App on day2 by updating the data value secret. As of today, I have to wait until next resync to get my App updated. 

**Describe the solution you'd like**
I would like to have the reconciliation of my App gets immediately triggered on data value secret updates.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Comment by vijaykatam** [comment]
Related issue https://github.com/vmware-tanzu/carvel-kapp-controller/issues/26

**Comment by danielhelfand** [comment]
I am going to close this in favor of #26, but please feel free to reopen if I am misunderstanding the request.
