### ISSUE TITLE
`kctrl package release` validation issue

### ISSUE THREAD

**Issue by matteo-magni** [carvel-dev/kapp-controller#1028]
**What steps did you take:**

```sh
git clone https://github.com/matteo-magni/carvel-lab.git
cd carvel-lab/kctrl/authoring-sample
kctrl package release --repo-output ./repository --tag 0.0.1 --version 0.0.1 --yes
```

**What happened:**

If some package values are required to be provided (i.e. via schema validation) the package won't build, and the error returned is

```text
kctrl: Error: Reconciling: ytt:
  Error:
    Validating final data values:
  name
    from: schema.yml:4
    - must be: length >= 1 (by: schema.yml:3)
      found: length = 0
```

**What did you expect:**

I expect some variables to be required at install time but not at build time.
For example, if I provide a package to deploy infrastructure on AWS I want to force the user to choose the destination region, so no default can be set.

**Anything else you would like to add:**

The same problem was raised by me and @joostvdg in another GH issue two months ago (#927).

**Environment:**

- kctrl version: v0.44.1

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by rohitagg2020** [comment]
Thanks, @matteo-magni for reporting the issue. We will discuss and update the issue with the next steps.

**Comment by 100mik** [comment]
I believe the case here is that there are no defaults for the value in question and it _must_ me supplied.
Am I correct?

**Comment by matteo-magni** [comment]
Correct. The value must be supplied at install time and not at build time, otherwise it would be included in the actual package, which is something I don't really want (that would be the same thing as setting a default).

**Comment by 100mik** [comment]
I see, I agree with this. When running validations initially the intention is to let `kbld` have YAML it can look for images in. I think the build step should use `--dangerous-data-values-disable-validation` when templating. Thanks a lot for the callout!
