### ISSUE TITLE
dry-run option for "install" and "add" commands

### ISSUE THREAD

**Issue by alexbarbato** [carvel-dev/kapp-controller#1029]
**Describe the problem/challenge you have**
When teaching new folks about what kctrl is doing behind the scenes to get them more familiar with the gitops workflows it enables, it's a two step process currently.

1. Run install package / add repository commands
2. kubectl get those items and explain what they are

**Describe the solution you'd like**
Ideally we'd have a dry run option that simply outputs the yaml that it's attempting to install/add.

We could eventually consider adding this to update commands as well, but I think initially it'd be most useful and simplest to dry-run on the create commands.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by rohitagg2020** [comment]
Thanks, @alexbarbato  for reporting the issue. We will discuss and update the issue with the next steps.

**Comment by 100mik** [comment]
This seems to have a lot of support from other folks as well. And I agree it will definitely help folks move towards a GitOps approach. 
Thanks for sharing the thought @alexbarbato ❤️

**Comment by 100mik** [comment]
Another thought, I think as of today if a package is installed, the installation fails after resource creation.
Validating wether the Package exists or not is trickier because the constraints might be a condition on semver.

I wonder if as a separate effort something like `--dry-run-validate` would be useful to verify if the cluster has the needed packages. For the time being, we are working towards putting together a flag that just outputs the YAML that would have been applied 🤔 

@alexbarbato thoughts?

**Comment by alexbarbato** [comment]
Interesting thought - I'm not experiencing that check pain you're describing so for me it's not really in the scope of my ask here. If that helps?

**Comment by 100mik** [comment]
It does! I was wondering if that is something that would be helpful to you 🙌🏼

**Comment by ThomasVitale** [comment]
It would be great if we could have a dry-run mode also for "kctrl dev". Especially for testing purposes, it would be really useful. Should I create a separate issue for that or would it make sense to include it in this one?

**Comment by 100mik** [comment]
> It would be great if we could have a dry-run mode also for "kctrl dev". Especially for testing purposes, it would be really useful. Should I create a separate issue for that or would it make sense to include it in this one?

@ThomasVitale this is something we had given some thought to as well. There should be an issue around raised already 🤔
