### ISSUE TITLE
Update App API Group from k14s.io to carvel.dev

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#103]
As part of the larger rebranding efforts around switching from k14s to Carvel, we should consider updating the Apps API Group from `kappctrl.k14s.io` to `kappctrl.carvel.dev`:

https://github.com/vmware-tanzu/carvel-kapp-controller/blob/ac48b9745e0fbb16045ceb55977bc2203c41034d/pkg/apis/kappctrl/v1alpha1/register.go#L12

In deciding whether to switch to the `kappctrl.carvel.dev` group name, it should also be considered that this will cause a breaking change in kapp as far as how kapp waits for the App CRD to reconcile:

https://github.com/vmware-tanzu/carvel-kapp/blob/cb948046934a0ed1fae3bb3865a63ac863b6f7b3/pkg/kapp/resourcesmisc/kappctrl_k14s_io_v1alpha1_app.go#L25

**Comment by aaronshurley** [comment]
Thanks for capturing this. This makes sense but does have some serious implications regarding breaking changes, as you called out. We'll move this to the Unprioritized Backlog for now.

**Comment by danielhelfand** [comment]
We are not going to do this as it would be a pretty significant breaking change. Closing this.
