### ISSUE TITLE
Fix kapp-controller package bundle to exclude development values

### ISSUE THREAD

**Issue by neil-hickey** [carvel-dev/kapp-controller#1038]
**What steps did you take:**
Installed the latest kapp-controller package (v0.44.1)

**What happened:**
The values.yml contains development values, such as `version: develop` instead of production values only.

**What did you expect:**
The values.yml should only contain configurable values we expect users to need.

**Anything else you would like to add:**
The structure of secretgen-controller folders is something we may want to replicate here as part of this, so that we have clear separation of values based on dev and prod.

https://github.com/vmware-tanzu/carvel-secretgen-controller/tree/develop/config

ghcr.io/vmware-tanzu/carvel-kapp-controller-package-bundle@sha256:9874d2c959d1b8600da37b5798580dd3f6f797512e8da531e31780765db2e59c

Current values.yml can be found here: https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/config/values.yml

We should not expose the following values, SGC has an example set of values we chose to expose, these could help inform the decision in kapp-controller (https://github.com/vmware-tanzu/carvel-secretgen-controller/blob/develop/config/package-bundle/config/values-schema.yml) : 

```
push_images: false
image_cache: true
image_repo: docker.io/k14stest/kapp-controller-test
platform: ""
kapp_controller_version: "develop"
```

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`):
- Kubernetes version (use `kubectl version`)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by neil-hickey** [comment]
will be done as part of https://github.com/carvel-dev/kapp-controller/pull/1047

**Comment by praveenrewar** [comment]
Hey @neil-hickey! Yash is on PTO, so I created a new [PR](https://github.com/carvel-dev/kapp-controller/pull/1111) (as working on the existing one without Yash seemed a bit difficult) to take this further.
