### ISSUE TITLE
Package Authors should be able to provide openAPI schema for configurations in Package CR

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#104]
**Describe the problem/challenge you have**
As a Package Consumer, I need to know the details about the configuration that is accepted by a package and I should be able to have confidence that the values provided by me are in the correct format and valid.

This problem has been divided into three issues:
- Package consumers do not have an easy way to discover the list of configurations that are provided by a package (this issue).
- While installing a package, when Package consumers provide their own configuration values of a package, they should get actionable error messages when the provided configuration is not valid.
    - kapp-controller should do basic structure validation of values provided in InstalledPackage (Issue #148).
    - If Package authors use ytt schemas in their package, kapp-controller should pass on the configuration in the ytt templating step so that ytt can validate the provided configuration (Issue #149).

**Describe the solution you'd like**
- The Package Author should be able to define the schema for their configuration in their package CR. 

- The Package Consumer should be able to view the schema for the configuration of a package so that they know what is the specific format for each configuration.

Short-Term:
- The configuration should be easily discoverable. Currently, Package Consumer will need to download the package bundle and check the data values YAML file to even know what configurations are exposed.
- Learn what type each configuration is
- Learn what is the purpose of each configuration is
- Learn what is the default of each configuration

Long-Term (Post MVP):
- Associated html type with each configuration. How should it be displayed on a UI form?

**Anything else you would like to add:**

- [ ] This feature should come with documentation. Also note we should explicitly call out schemas should be included in the relevant templating steps and that kapp-controller, at least initially, won't do any validation using the schema included in the package definition; That schema is intended mainly for visibility in to what values can and should be provided.

**Comment by aaronshurley** [comment]
We see two options here:
1. kapp-controller leverages templating engine (such as ytt schemas) for this functionality. At this point, ytt schemas is not yet available. (estimate: 1)
2. kapp-controller performs this functionality outside of templating. This option is less desirable. It could be complex for kapp-controller to combine multiple values documents. (estimate: 3)

**Comment by danielhelfand** [comment]
Linking to this `ytt` epic on [schema generation](https://github.com/vmware-tanzu/carvel-ytt/issues/357). Will be useful for creating schemas for Packages. 

Would be nice for us to find a way to actually add the generated schemas to our Package CRs to avoid any copying over of the schema. Like a schema patch approach where `ytt` knows where to add the schema for Package CRs.

**Comment by vibhas** [comment]
@danielhelfand regarding your previous comment just wanted to clarify that for this issue (104), we are assuming that the Package Authors will manually create the OpenAPI schema in the Package CR. Once that ytt epic on schema generation is available, the authors will not have to do it manually.
