### ISSUE TITLE
Restrict exposing some values we manipulate as part of KC Package

### ISSUE THREAD

**Issue by sethiyash** [carvel-dev/kapp-controller#1046]
**What did you expect:**
Today, We expose every field as part of KC package that is there in [config/values.yml](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/config/values.yml) we should restrict exposing values we manipulate during development of KC Package 

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by sethiyash** [comment]
Duplicate of #1038

**Comment by praveenrewar** [comment]
Done as part #1111
