### ISSUE TITLE
Kapp controller failing to reconcile package repository if already package exists

### ISSUE THREAD

**Issue by bikkinamahesh369** [carvel-dev/kapp-controller#1054]
**What steps did you take:**
The package already exists in the environment.  Now I tried to add a package repository that also contains the same package.

**What happened:**
 Kapp Controller failed to reconcile the package
```
11:03:59AM: Deploy failed 
	  | kapp: Error: create package/cert-manager.tanzu.vmware.com.1.10.1+vmware.1-tkg.1-rc.2 (data.packaging.carvel.dev/v1alpha1) namespace: tkg-system:
	  |  Applying rebase rule to package/cert-manager.tanzu.vmware.com.1.10.1+vmware.1-tkg.1-rc.2 (data.packaging.carvel.dev/v1alpha1) namespace: tkg-system:
	  |   Applying ytt (overlayContractV1):
	  |    Evaluating:
	  | - struct has no .annotations field or method (did you mean .generation?)
	  |   in <toplevel>
	  |    overlay.yml:93 | #@ if pkg_repo_ann in data.values.existing.metadata.annotations:
	  | Deploying: Error (see .status.usefulErrorMessage for details)
Error: Reconciling repository: Deploy failed

```
**What did you expect:**
It need to succeed without failing

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`): v0.41.5
- Kubernetes version (use `kubectl version`) 

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment]
We are currently checking if pkg_repo_ann is present in the annotations of the existing package ([here](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/ad24bdc3e41219b176f88280a469e9fd21979339/pkg/pkgrepository/app_template.go#L235)), but if the annotations field itself is not present then it fails with a "missing annotations field" error. @shyaamsn thanks for figuring this out :)

We added these rebase rules to help avoid conflict when a package was already present as part of another package repository but in this case the existing package is not part of any pkgr and doesn't have any annotations present. Adding a nil check for annotations should fix it.

**Comment by neil-hickey** [comment]
hey @praveenrewar can you update the status of this to reflect if it's in progress or not? Thanks!

**Comment by praveenrewar** [comment]
Hey @neil-hickey Thank you for moving it to Prioritized Backlog 😄 I am planning to take this up tomorrow, or next week, I will update the status to In Progress then.
