### ISSUE TITLE
Package Repository reconciler should not use an app

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kapp-controller#108]
The package reconciler is currently creating an app which naively fetches and installs anything in the source it points to. The intermediary should be cut out and the package repo reconciler should do the fetch and install itself. This will also help down the line when we formalize the structure of a repo bundle.

- [ ] Package repo reconciler should pass all the packages it is going to install through kbld before installation (including the images.yml if its a bundle). This is needed for the air gapped case

**Comment by ewrenn8** [comment]
After some more discussion, we are going to hold off on doing this issue until after we have moved packages to the aggregated api layer. This will allow us to bypass api calls in the controller completely for efficiency

**Comment by vibhas** [comment]
Moved the task "Package repo reconciler should pass all the packages it is going to install through kbld before installation (including the images.yml if its a bundle). This is needed for the air gapped case" to a new [issue](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/143)

**Comment by vibhas** [comment]
Adding "Explore" to this issue so that we can create a proposal.

**Comment by vibhas** [comment]
We are thinking to make this a stretch goal for Packaging MVP. If we make this change post-MVP, there is an additional thing that we need to consider - when kapp-controller is upgraded, it will have to delete all the associated App CR for each Package Repository and then create them using the new mechanism that we decide as part of this issue.

**Comment by danielhelfand** [comment]
Closing since #219 was released in [0.20.0-rc.1](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/alpha-releases/0.20.0-rc.1.yml)
