### ISSUE TITLE
Package repository doesnt have a status field

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kapp-controller#109]
This makes it hard to debug when a package repository isn't working as expected. There should be a status field the shows the user whether reconciliation has been successful, and, if not, what went wrong in the process. 

Since PackageRepository is using an App, we can leverage the underlying App status as the repository's status.

- [ ] Modify the Package consumer docs to add this step

**Comment by aaronshurley** [comment]
We deprioritized this issue a bit for the following reasons:
- we want to see what we address in https://github.com/vmware-tanzu/carvel-kapp-controller/issues/110
- if we're able to move away from App ([issue](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/108)), then this work would change

**Comment by ewrenn8** [comment]
Released in `v0.19.0-alpha.6`
