### ISSUE TITLE
Package Consumers should be able to search for packages that are available on a cluster

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#111]
Related issue: https://github.com/vmware-tanzu/carvel-kapp-controller/issues/92

**Describe the problem/challenge you have**
Once one or more packages are available to install, the package consumer will need a way to be able to view the list of packages and their metadata.

**Describe the solution you'd like**
We need to provide a way such that package consumers can achieve the following:
- Search for packages by name and version

**Anything else you would like to add:**
- The urgency of this feature likely depends on what the MVP scale of packages is (such as 20 vs 1,000).

**Comment by cppforlife** [comment]
closing, since this is not currently important, but when we get to a point when searching is necessary lets reopen/recreate this issue.
