### ISSUE TITLE
Parsing error when using '-' as template argument

### ISSUE THREAD

**Issue by benmoss** [carvel-dev/kapp-controller#115]
**What steps did you take:**
Deployed an app piping from kbld to ytt:

```
...
 template:
  - kbld:
      paths:
      - config/stuff
  - ytt:
      paths:
      - -
      - config/ytt
```

**What happened:**
The deploy eventually times out, but the kapp-controller logs this:
```
reflector.go:153] k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1alpha1.App: v1alpha1.AppList.Items: []v1alpha1.App: v1alpha1.App.Spec: v1alpha1.AppSpec.Template: []v1alpha1.AppTemplate: v1alpha1.AppTemplate.Ytt: v1alpha1.AppTemplateYtt.Paths: []string: ReadString: expects " or n, but found [, error found in #10 byte of ...|"paths":[[null],"con|..., bigger context ...|}},{"ytt":{"ignoreUnknownComments":true,"paths":[[null],"config/ytt"]}}]}}],"kind":"AppList","metada|...
```

**What did you expect:**
It just works, or at least is documented that you need to quote `-` as an argument.

**Anything else you would like to add:**
Quoting `-` fixes the problem.

**Environment:**

- kapp Controller version: v0.17.0-alpha.1.yml
- Kubernetes version (use `kubectl version`)
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by danielhelfand** [comment]
As you mention, the `-` does need to be quoted because otherwise yaml thinks it is the beginning of new array.

We have noticed a fair amount of places in our docs where we do not promote this where we can update the docs:
* https://carvel.dev/kapp-controller/docs/latest/app-spec
* https://carvel.dev/kapp-controller/docs/latest/packaging/#package-cr
* https://carvel.dev/kapp-controller/docs/latest/package-authoring/#creating-the-package-cr

A more helpful error would probably help as well.

**Comment by ewrenn8** [comment]
There is not much we can do here because it is the yaml parsing that is failing. We may be able to get better error messages through adding schema to the App CRD. I created #130 to capture this work.

**Comment by aaronshurley** [comment]
As @ewrenn8 mentioned, there isn't much we can do here. #130 captures a potential error message improvement.

Since @danielhelfand already made the docs updates, can we close out this issue?
