### ISSUE TITLE
kctrl: Support for package and package repository airgapped workflow

### ISSUE THREAD

**Issue by shyaamsn** [carvel-dev/kapp-controller#1197]
**Describe the problem/challenge you have**
As a user I would like kctrl to support airgapped workflow for package and package repositories.Today user has to download and use imgpkg to copy packages and package repositories. As a user I would like to avoid downloading multiple tools and reduce friction involved to support airgapped workflow. 

Since user uses kctrl to author and install packages. It would be ideal to use the same kctrl to also copy packages and package repositories for airgapped workflow. This would avoid downloading another tool and using kctrl to deal with packages and repos seems natural. As a user I shouldnt need to know that packages and repos are bundles and need to download imgpkg to do the relocation.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen. If applicable a visual representation of the UX.]
tanzu package copy --from <> --to-tar <>
tanzu package copy --tar <>  --to-repo 
tanzu package repo copy --from <> --to-tar <>
tanzu package repo copy --tar <>  --to-repo 

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
This does not look like the correct location for this issue, so I am going to close it for now
