### ISSUE TITLE
Support dockerconfigjson secrets for credentials

### ISSUE THREAD

**Issue by jorgemoralespou** [carvel-dev/kapp-controller#120]
kapp-controller's App's `spec.fetch.image.secretRef` and `spec.fetch.imgpkgBundle.secretRef` should support dockerconfigjson type of secrets as they are the standard type of secrets for credentials to OCI registries.

https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials

**Comment by aaronshurley** [comment]
Thanks for creating this issue. We see the value in this request but are not planning to prioritize this immediately in our backlog. Contributions are welcome :)

**Comment by cppforlife** [comment]
vendir started supporting this in latest version. waiting for the bump.

**Comment by cppforlife** [comment]
support is in v0.19.0
