### ISSUE TITLE
kctrl: Error: Building Kubernetes config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable (hint: Ensure cluster name is specified correctly in context configuration)

### ISSUE THREAD

**Issue by tiansiyuan** [carvel-dev/kapp-controller#1207]
With MicroK8s on mac.

How to solve it?

Thanks

**Comment by praveenrewar** [comment]
Hi @tiansiyuan Could you share the steps to reproduce this problem? Are you able to use `kubectl` or you are getting the same error?
I tried using kctrl with microk8s and it's working fine for me.

**Comment by tiansiyuan** [comment]
Hi @praveenrewar I create a link /Users/siyuant/.kube/config -> /Users/siyuant/.microk8s/config and this problem is gone. But I have another issue. microk8s status always says it is not running. And the two pods are not in running status:

% kubectl get pod -A    
NAMESPACE     NAME                                       READY   STATUS     RESTARTS   AGE
kube-system   calico-node-dqvb9                          0/1     Init:0/2   0          43h
kube-system   calico-kube-controllers-79568db7f8-9fqcp   0/1     Pending    0          43h

I reported it at https://github.com/canonical/microk8s/issues/886

Thanks,

Tian

**Comment by praveenrewar** [comment]
Hi @tiansiyuan Good to know that creating a link worked for you. Closing the issue now, but feel free to reopen in case you are still facing any issues.

**Comment by tiansiyuan** [comment]
@praveenrewar Thank you for your kind help.
