### ISSUE TITLE
Change default port to 8443 instead of 10350

### ISSUE THREAD

**Issue by voor** [carvel-dev/kapp-controller#1217]
**Describe the problem/challenge you have**
The default `KAPPCTRL_API_PORT` is currently `10350`, which can cause some issues on hosted Kubernetes clusters, specifically GKE and EKS, that implicitly deny that port by only permitting a smaller subset of traffic.  For example, by default EKS does 9443, 8443, 6443, 4443, and 443.

**Describe the solution you'd like**
Change the default port to `8443`, this will reduce the likelihood of new users experiencing issues when installing kapp-controller in those environments.  It can't be `443` since that's a privileged port.

**Anything else you would like to add:**
Even though it's happening on an overlay network, the cloud providers are looking at the port number for the traffic.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by renuy** [comment]
The standard ports may or may not be available for us to use those ports, and we may have conflict, hence the decision to go with a non-standard port.
Need to explore more to see if there are other service that may use the standard port that we want to use or change to. 

However, it is possible to change the configuration on the release.yaml to change the port at the time of installation.

**Comment by voor** [comment]
> The standard ports may or may not be available for us to use those ports

So the weirdness here is that this is the **containers** port, and so it should always be available to use **except** when you are also setting the pod to use host networking (which should **not** be the normal way kapp-controller is deployed).  The thing that becomes difficult is that cloud providers like GCP or AWS generally are deployed with a network CNI that actually cares about those ports when going to the API Server (which is hosted in the cloud provider's space), so it's almost like an edge case that happens all the time with GCP and AWS.

**Comment by neil-hickey** [comment]
I think that was my misunderstanding of the PORT situation in kapp-controller. I thought that 10350 was the port that the kube-apiserver was serving the Carvel Packaging API on. Not that it was the port on the container of the kapp-controller pod. So generally the problem with having 10350 is that the kapp-controller pod can't talk to the k8s server because communication from 10350 of KC pod to 6443 of k8s server is blocked by default.

> The thing that becomes difficult is that cloud providers like GCP or AWS generally are deployed with a network CNI that actually cares about those ports when going to the API Server (which is hosted in the cloud provider's space), so it's almost like an edge case that happens all the time with GCP and AWS.

I'm slightly confused by that statement, when you say they "care about the ports going to the API Server". What does that mean exactly? If we chose 8443, what would happen on GCP?

**Comment by voor** [comment]
The API server makes the call to a container.

Source is API server in cloud provider space owned by cloud provider 
Destination is container on VM in vpc owned by customer 

Both AWS and GPC look at the port of the container, and use security groups and firewall rules to see if that's acceptable traffic. 

By default they permit 443 (privileged), 8443, 9443, and then some other ones that aren't shared between providers.
