### ISSUE TITLE
PackageRepositories should leverage recursive imgpkg bundles

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kapp-controller#125]
As part of the [imgpkg recursive bundle proposal](https://github.com/k14s/design-docs/blob/37769d97d2f377841d476d9b0c9672635caab5a2/imgpkg/002-recursive-bundles/README.md), imgpkg is not enabling pulling bundles recursively by default. Since package repositories can be recursive bundles (a top level repo made up of more focused offerings), the package repository reconciler needs to be updated to pull bundles recursively to ensure all packages are pulled down.

 Also, since there are no guarantees package repositories exclusively reference other repo bundles, the reconciler should be updated to recursively pull only the bundles that have a particular annotation denoting they are package repositories.

- [ ] Package repository reconciler pulls bundles recursively
- [ ] Package repository reconciler only pulls recursive bundles that are annotated as repositories

**Comment by cppforlife** [comment]
been using "flat" repo approach (aka repo is flattened at the build time instead of kc runtime) and it works great.
