### ISSUE TITLE
First is missing in the documentations

### ISSUE THREAD

**Issue by satyampsoni** [carvel-dev/kapp-controller#1278]
In the Readme.md there should be "good first issues" instead of "good issues"
![image](https://github.com/carvel-dev/kapp-controller/assets/94950988/30809370-391d-4087-adf0-65cd06b50ad6)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment]
Thanks @satyampsoni! Would you like to create a PR for this?

**Comment by satyampsoni** [comment]
Yes! Sure
