### ISSUE TITLE
InstalledPackage controller just selects packages by version and not name

### ISSUE THREAD

**Issue by benmoss** [carvel-dev/kapp-controller#128]
**What steps did you take:**
- Have a repository with two or more images with the same version
- Install one of the packages

**What happened:**
It randomly picks one of them to actually install

**Anything else you would like to add:**
Looking at the code [here](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/b49ffe7a15bd186e927b9709933c50f3a47b472e/pkg/installedpkg/installedpkg.go#L142-L164) it looks like only version selection logic is in place, no name matching.

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`): 0.17.0-alpha.1

**Comment by aaronshurley** [comment]
Thanks, @benmoss! We're going to take a look at this right away.

**Comment by ewrenn8** [comment]
Fixed in `v0.17.0-alpha.2` via this commit 9c8d7d0086d332967a2a8db62d7f9c487352fbd5
