### ISSUE TITLE
Add more debug info to failing InstalledPackages

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kapp-controller#133]
**Describe the problem/challenge you have**
When debugging an installed package that is failing reconciliation, the failure message just states "Reconcile failed: App failed reconciling", which doesn't give much direction to the user. This message also requires the user to move a level below the Packaging APIs and debug an app directly.

**Describe the solution you'd like**
Surface more useful information when an InstalledPackage is failing to reconcile due to the underlying app. One idea is to copy any status fields that have a non zero exit code to the installed package to surface the debug info without having to look at the App CR

- [ ] Add debug info in package CR
- [ ] Add debug tips to docs

Is there more or other info we should surface on the installed package?

**Comment by vibhas** [comment]
We should also document some of these troubleshooting/debugging tips on our Packaging docs.

**Comment by aaronshurley** [comment]
Awaiting the results of https://github.com/vmware-tanzu/carvel-kapp-controller/issues/110 before we decide what to do with this issue.

**Comment by danielhelfand** [comment]
While it is a bit unclear about what the best way to fully close #110 is, there has been some work done in #157 and #159 that we can use to move forward with this issue. The current thought process is to at the very least surface the `UsefulErrorMessage` introduced in #157 through the InstalledPackage status. This will help present the most recent error of the underlying App CR to end users such that they do not also need to look at the App status after seeing the InstalledPackage failed.

**Comment by ewrenn8** [comment]
Released in `v0.19.0-alpha.6`
