### ISSUE TITLE
Documentation to help package consumers install and manage packages (air-gapped)

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kapp-controller#134]
The consumer flow in the case of an air gapped cluster is slightly different and should have its own docs section.

The main differences are in:
- [ ] Repositories must be relocated
- [ ] Repository CRs must point to internal location

**Hopefully the rest of the flow is the same since kapp-controller will handle image ref replacement**

As a part of this issue, we can also do the following:
- [ ] We are still working on a proposal to define how authentication against private registries should work in this [issue](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/145). However, we need to document a workaround on how a user can authenticate against a private registry when installing a package. Lets use this issue to also document that workaround. Details are in this [issue](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/167).

**Comment by aaronshurley** [comment]
If we get to this issue before recursive bundles are available in imgpkg, consider drafting the documentation to inform any design decisions. It's also fine to postpone this documentation until recursive bundles are available in imgpkg.
