### ISSUE TITLE
Determine What Version of kapp-controller is Available on a Cluster

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#139]
**Describe the problem/challenge you have**

Unless I look through logs, there is no simple way to determine what version of kapp-controller is installed on a Kubernetes cluster. 

**Describe the solution you'd like**

In general, this can be further abstracted through client tools, but it might be easy enough for now to add a label to the kapp-controller deployment that has the version of kapp-controller. This would allow client tools to get the value of the label and show what the version is.

An example with `kubectl` would be:

`kubectl get deployment/kapp-controller  -o jsonpath={.metadata.labels['version']} -n kapp-controller`

**Comment by cppforlife** [comment]
currently you can also identify git sha by looking at kbld's images annotation on kapp-controller Deployment and look in the git repo what that sha correlates to.

**Comment by aaronshurley** [comment]
From our discussion...

There are multiple approaches here:
- build time (such as adding an annotation)
- run time (such as kapp-controller creating a ConfigMap in a particular namespace)

**Comment by joe-kimmel-vmw** [comment]
there is now a version annotation if you describe the deployment.   I think this went out with 0.24 or 0.25. 
detailed instructions are here:
https://github.com/vmware-tanzu/carvel/commit/78fb8439e86098f1f1a2bd495c464c299140e6a4
(`kubectl describe deployment kapp-controller -n kapp-controller | grep version`)
