### ISSUE TITLE
pull the kapp-controller continer image with tag equal to release 

### ISSUE THREAD

**Issue by vivekskrishna** [carvel-dev/kapp-controller#1397]
Is there some way i can pull the kapp-controller container image for a specific release say 0.48.1 or 0.48.2 etc. I see images only with some rand tags and in our company we ahve policy which allows images to be pulled if only tagged with release versions. are the container images for releases hosted somewhere from which it can be pulled.

**Comment by praveenrewar** [comment]
@vivekskrishna We are using ghcr to host the images (can be found under [kapp-controller packages](https://github.com/carvel-dev/kapp-controller/pkgs/container/kapp-controller)). I think you should be able to use the sha instead of tags.
