### ISSUE TITLE
Expose configuration to specify app deletion should be a noop.

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kapp-controller#141]
**Describe the problem/challenge you have**
Sometimes it is desirable to have app deletion be a noop instead of running kapp delete.

For example, if kapp-controller is managing apps on a separate workload cluster and the cluster is being deleted, kapp-controller will attempt to delete all apps. Some of the apps that are managed may have installed resources that are critical to the functioning of the cluster (e.g. CNI). Since kapp-controller doesn't order the deletion of apps, and nor should it, it could potentially delete a required app before deleting the other apps on the system, which would cause all subsequent deletes to hang.

**Describe the solution you'd like**
Expose some configuration on the appCR that can be used to mark an app as a noop delete. This will cause kapp-controller to skip issuing the kapp delete command.

This allows users in the case above to avoid managing the order of deletion, and instead specify critical apps as noop delete, so that kapp-controller will not actually delete the app, since the resources will be cleaned up once the cluster itself is deleted.

**Comment by danielhelfand** [comment]
Capturing some notes here from Slack:

> Would also note that during noop deletion we shouldnt try to fetch/template configuration. Also not check for kubeconfig/sa resource. Effectively noop delete turns into just delete the App CR without checking on anything.
