### ISSUE TITLE
Package repo reconciler should pass all the packages it is going to install through kbld before installation

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#143]
Package repo reconciler should pass all the packages it is going to install through kbld before installation (including the images.yml if its a bundle). This is needed for the air-gapped scenario.

**Comment by ewrenn8** [comment]
Added in a7566dd and released in `v0.18.0-alpha.5`. I am going to close this. We can handle multiple nested repos in a post MVP issue.
