### ISSUE TITLE
MetaPackage capability

### ISSUE THREAD

**Issue by alexbarbato** [carvel-dev/kapp-controller#1434]
**Describe the problem/challenge you have**
Currently we install a number of `Packages` - they have interdependencies, but there is currently no codified way to formalize those interdependencies.

**Describe the solution you'd like**
Ideally there'd be some API that allows me codify a series of `Packages` go together. In theory you could do that with a `Package`, but absent the tooling supporting it becomes a bit of a bridge too far for the average user.

In order to seamlessly do that you have to much of the plumbing to pass around values to children packages as an example.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment]
@alexbarbato Do you think solving the problems mentioned in #361 would work for your use case?

**Comment by alexbarbato** [comment]
Oo that does cover the use cases I described! Is there a plan to pick up any of that work?

I guess we can close this one then?

**Comment by praveenrewar** [comment]
We haven't prioritised it yet, however there has been demand from the community for it and we are trying to look more into how we can best solve the dependency management problem. I am okay with keeping this issue open till we have an update.

**Comment by Sarita-Singh** [comment]
Hey @praveenrewar I think if there is bazel support for the project, we can get package dependencies including transitive dependencies through [bazel query](https://bazel.build/query/guide)

**Comment by renuy** [comment]
Closing this, as we are working on dependency management.
https://github.com/carvel-dev/carvel/pull/732
