### ISSUE TITLE
Authentication against private registry when installing a PackageRepository and an PackageInstall

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#145]
**Describe the problem/challenge you have**
It is possible that the Package Repository bundle or the Package contents bundle are located in a registry that requires authentication for access. Currently, the package consumers do not have any way to authenticate against a registry when installing a PackageRepository CR or a PackageInstall CR.

**Comment by aaronshurley** [comment]
Adding `Explore` to this story so that we can define/propose a solution.

**Comment by danielhelfand** [comment]
Documenting some recent conversation around this issue, but there is still no clear consensus on the right approach for this issue.

One interesting point is about whether Package consumers should need to provide credentials to install a Package. From an auditing standpoint, it would make sense to have a private registry be accessible by particular users and then allow that user to provide credentials via a Secret. However, from a UX standpoint this doesn't seem like the best experience. In general though, how Package consumers provide credentials or if at all should be an important factor in the final proposal on this.
