### ISSUE TITLE
kapp-controller should do basic structure validation of values provided in InstalledPackage

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#148]
**Describe the problem/challenge you have**
As a Package Consumer, I need to know the details about the configuration that is accepted by a package and I should be able to have confidence that the values provided by me are in the correct format and valid.

This problem has been divided into three issues:
- Package consumers do not have an easy way to discover the list of configurations that are provided by a package (Issue #104).
- While installing a package, when Package consumers provide their own configuration values of a package, they should get actionable error messages when the provided configuration is not valid.
    - kapp-controller should do basic structure validation of values provided in InstalledPackage (this issue).
    - If Package authors use ytt schemas in their package, kapp-controller should pass on the configuration in the ytt templating step so that ytt can validate the provided configuration (Issue #149).

**Describe the solution you'd like**
- The Package Author should be able to define the schema for their configuration in their package CR. 

- When Package Consumers try to deploy an InstalledPackage CR with their configuration values, kapp-controller should do basic structure validation of the provided configuration.

**Anything else you would like to add:**
We need to consider how overlays might affect this behavior.

**Comment by neil-hickey** [comment]
All topics have been completed. Closing this out
