### ISSUE TITLE
kapp-controller should leverage ytt schemas for configuration validation

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#149]
**Describe the problem/challenge you have**
As a Package Consumer, I need to know the details about the configuration that is accepted by a package and I should be able to have confidence that the values provided by me are in the correct format and valid.

This problem has been divided into three issues:
- Package consumers do not have an easy way to discover the list of configurations that are provided by a package (Issue #104).
- While installing a package, when Package consumers provide their own configuration values of a package, they should get actionable error messages when the provided configuration is not valid.
    - kapp-controller should do basic structure validation of values provided in InstalledPackage (Issue #148).
    - If Package authors use ytt schemas in their package, kapp-controller should pass on the configuration in the ytt templating step so that ytt can validate the provided configuration (this issue).

**Describe the solution you'd like**
- The Package Author should be able to define ytt schema (as YAML) for their configuration in their package contents. 

- When Package Consumers try to deploy an InstalledPackage CR with their configuration values, they should get actionable error messages when the provided configuration is not valid. kapp-controller should leverage ytt schemas for configuration validation.

Short-Term:
- Get meaningful error when provided with an incorrect value (type-checking)

Mid-Term:
- Validations on the configuration such as min/max, text length, etc.

Reference: https://github.com/vmware-tanzu/carvel-ytt/issues/283

**Anything else you would like to add:**

**Comment by aaronshurley** [comment]
ytt schemas were provided in kapp-controller's most recent version [v0.21.0](https://github.com/vmware-tanzu/carvel-kapp-controller/releases/tag/v0.21.0) so this functionality is provided by default.

We have another issue that was created to focus more narrowly on schema error messaging: https://github.com/vmware-tanzu/carvel-kapp-controller/issues/312
