### ISSUE TITLE
Introducing new metadata fields for Package CR

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#156]
**Describe the problem/challenge you have**
Currently, we support _publicName_ and _version_ as first-class fields for metadata that needs to be defined in a Package CR. However, there might be more things that the Package authors will need to provide in their packages. This issue has been created to track all the metadata that needs to be supported as first-class fields in Package CR. 

- **Package Identifier**
Unique name used to identify the package. This name is used to let packaging apis know, at the time of the installation, what package to install.
Example: fluentbit.x.vmware.com
Field: spec.publicName
Required: TRUE

- **Package version**
Semantic version of the package. 
Example: 1.0.1, 1.3.0-vmware.1
Field: spec.version
Required: TRUE

- **Package Icon**
A base64-encoded image or logo for the package or the package publisher. Should be .svg format. 
Field: spec.icon
Required: FALSE

- **Package Name**
User-facing name of the package.
Example: Fluentbit
Field: spec.displayName
Required: TRUE

- **Package provider**
Name of the package author. 
Example: VMware
field: spec.providerName
Required: FALSE

- **Package maintainers**
Name of the package’s maintainers, which could be individuals or a company. You can include an email address or contact information. 
Field: spec.maintainers
Required: FALSE

- **Short Description**
User-facing short description about this package.
Example: "Certificate manager"
Field: spec.shortDescription
Required: FALSE

- **Long Description**
User-facing description about the package, including key features, common use cases, and any limitations. Include any relevant links to more information, like your website or a blog post.  
Field: spec.description
Required: FALSE

- **Version Release Notes**
Description about what’s included in the latest version of your package release, and what’s changed since the last release. Markdown text; can include web links. 
Field: spec.releaseNotes
Required: FALSE

- **Package category**
Field: spec.values
Category of the package
field: spec.category
Required: FALSE

- **Support**
Include information about how the customer can get support. e.g. email, slack workspace, phone number, website, forum, etc..
field: spec.supportDescription
Required: FALSE

- **Minimum capacity requirements description**
Minimum capacity requirements for user to install package on a cluster. General description in text form.
Example: "Requires >5 CPUs, >10GB+ RAM"
field: spec.capacityRequirementsDescription
Required: FALSE

- **License description**
View license information for the package.
Free-form text; can accept a URL
field: spec.licenseDescription
Required: FALSE

As a part of this issue, we should also do the following:
- [ ] We should document these new metadata fields.
- [ ] Update the [schema issue](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/117) with any requirements for validation on these metadata fields.
- [ ] We need to generate the Kubernetes client.

**Comment by vibhas** [comment]
Question during IPM: Should we have character limits for some of these metadata (for eg: Short Description). A benefit of doing that is that we could show the short description in our tabular format when listing packages.

**Comment by ewrenn8** [comment]
Included in `v0.19.0-alpha.7`
