### ISSUE TITLE
If kapp can never connect to remote cluster it can never delete App CR

### ISSUE THREAD

**Issue by voor** [carvel-dev/kapp-controller#16]
Recreate:

Create a kubeconfig that is valid but points to an invalid endpoint (like `api.example.com`).  On first deployment you will get something similar to this:
```
Status:
  Conditions:
    Message:  Deploying: exit status 1
    Status:   True
    Type:     ReconcileFailed
  Deploy:
    Error:       Deploying: exit status 1
    Exit Code:   1
    Finished:    true
    Started At:  2020-07-04T12:08:10Z
    Stderr:      kapp: Error: Creating app:
  Post https://api.example.com:6443/api/v1/namespaces/kube-system/configmaps: dial tcp 10.234.2.190:6443: i/o timeout
    Stdout:      Target cluster 'https://api.example.com:6443'
    Updated At:  2020-07-04T12:09:10Z
  Fetch:
    Exit Code:           0
    Started At:          2020-07-04T12:08:10Z
    Updated At:          2020-07-04T12:08:10Z
  Friendly Description:  Reconcile failed: Deploying: exit status 1
  Inspect:
    Error:      Inspecting: exit status 1
    Exit Code:  1
    Stderr:     kapp: Error: Getting app:
  Get https://api.example.com:6443/api/v1/namespaces/kube-system/configmaps/a-postcreate-ctrl: dial tcp 10.234.0.52:6443: i/o timeout
    Stdout:             Target cluster 'https://api.example.com:6443'
    Updated At:         2020-07-04T12:10:11Z
  Observed Generation:  1
  Template:
    Exit Code:   0
    Updated At:  2020-07-04T12:08:10Z
```

App CR will not sit around indefinitely, because it cannot ever get the status of the app.

**Comment by cppforlife** [comment]
@voor do you think we should try to track if we ever got far enough to deploy, and if not, "fast forward" deletion automatically. in case we did get far enough, im not sure we can do much aside from offering a way to configure a `spec.cluster.unreachable=true` (or something like that) to let kapp-controller know to "fast forward" deletion.

**Comment by voor** [comment]
If you combined those that would probably cover the common scenarios, right?  

1. If it *never* worked, just delete it because there's nothing to clean up.  
1. If it *did* work successfully once a long time ago, but the cluster is now completely unreachable, allow user intervention by allowing deletion of an App CR with `spec.cluster.unreachable=true`

**Comment by ewrenn8** [comment]
Hey @voor, we are currently working on a feature to allow specifying an app should have a noop deletion here #141. Do you think this would solve this use case as well?

**Comment by voor** [comment]
Yes, although we've also gotten into a habit of just removing the finalizer and deleting the App CR.

**Comment by ewrenn8** [comment]
I am going to close this in favor of #141 then. Thanks!
