### ISSUE TITLE
Incorrect URL for kapp controller install instruction 

### ISSUE THREAD

**Issue by rashedkvm** [carvel-dev/kapp-controller#1604]
**What steps did you take:**

Install kapp controller using the install instruction found in the release note.  https://github.com/carvel-dev/kapp-controller/releases/tag/v0.53.0

**What happened:**

kapp controller release.yml download returns 404

```shell
~ kapp deploy -a kc -f https://github.com/carvel-dev/kapp-controller/releases/v0.53.0/download/release.yml
Target cluster 'https://127.0.0.1:40355/' (nodes: test-control-plane)

kapp: Error: Requesting URL 'https://github.com/carvel-dev/kapp-controller/releases/v0.53.0/download/release.yml': 404 Not Found
```

**What did you expect:**

A successful install of kapp controller

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

Looks the kapp controller download URL is flipped. It should be
```shell
https://github.com/carvel-dev/kapp-controller/releases/download/v0.53.0/release.yml
```
![image](https://github.com/user-attachments/assets/3a398e7c-3477-48cd-af2f-0b0a9eeaa8cb)

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`): 0.53.0
- Kubernetes version (use `kubectl version`)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment]
Thanks @rashedkvm! Looks like the bug is present in the url in the release notes template.
