### ISSUE TITLE
Add validations for Packages and PackageVersions

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#165]
**Describe the problem/challenge you have**

Currently, we have no validations on Package CR or PackageVersion CR. In order to promote best practices among package authors, we should add following validations:

- In order to avoid accidental conflicts within packages, Package name should be a FQDN made up of three segments separated by "."s and does not have a trailing "."
- PackageVersion metadata.name is of form <spec.packageName> + "."
- PackageVersion spec.packageName is a valid package name (see above)
- Package Version spec.version is not empty

**Comment by danielhelfand** [comment]
The error returned in this case should probably have some kind of hint to suggest using the naming standard for packages.

**Comment by vibhas** [comment]
Maybe we can handle this validation in this [issue](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/117)?

**Comment by cppforlife** [comment]
> Maybe we can handle this validation in this issue?

schema issue unfortunately will not help us with validating this specific naming requirement.

**Comment by ewrenn8** [comment]
Because it served by agg api?

**Comment by cppforlife** [comment]
oh my bad, i reread the issue. seems like that issue was modified to do more stuff beyond schema. all i was trying to describe that schema by itself cannot check for for this afaik.

**Comment by ewrenn8** [comment]
I was thinking we could use the pattern validation included in the structural schema example in these [docs](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema), but I forgot these aren't CRDs anymore, so we aren't even specifying schemas for them.

**Comment by aaronshurley** [comment]
We're going to block this until the [open proposal](https://github.com/vmware-tanzu/carvel-community/pull/30) is accepted.

In the interim, we should at least capture this guidance in the docs.

**Comment by cppforlife** [comment]
for record keeping, lets also validate that PackageVersion's metadata.name starts with its `spec.packageName + "."`

**Comment by ewrenn8** [comment]
We can probably just leverage [this validation](https://github.com/kubernetes/kubernetes/blob/4d4b530114a6a160c0366673c73de607eeb54453/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L78) for this?

**Comment by cppforlife** [comment]
that might be a bit too strict for version suffix etc.

**Comment by ewrenn8** [comment]
Add in #207 

Validations:
- Package name is FQDN made up of three segments separated by "."s and does not have a trailing "."
- PackageVersion metadata.name is of form <spec.packageName> + "."
- PackageVersion spec.packageName is a valid package name (see above)
- Package Version spec.version is not empty

**Comment by ewrenn8** [comment]
released in `alpha.10`
