### ISSUE TITLE
Merge dev-packaging into develop

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#166]
With release v0.18.0, there should now be no blockers for merging the packaging API work into develop. This issue is mainly serving as a way to track the work to be done to merge this branch in.

Before moving forward with this, some questions we should consider are as follows:
* How would we like to go about reviewing the changes being introduced?
* What should be our approach to squashing commits? (Currently there would be 70+ new commits added)
* What will our release strategy look like once the branch is merged? (Will we keep putting out alpha release candidates instead of GitHub releases?)

**Comment by cppforlife** [comment]
i think this is done. closing.
