### ISSUE TITLE
Documentation should include how packages can authenticate against private registry

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#167]
Currently, the kapp-controller packaging docs do not include recommended examples on how an InstalledPackage can reference a Package that requires authentication against a private registry. 

As of now, it seems like for this to take place, a package author needs to configure the package with a `secretRef` for the image or imgpkg bundle. The user then must have this secret created in the namespace where an InstalledPackage is created so its underlying App can utilize the secret. 

If the above workflow makes sense as we think more about authentication approaches, we should include this in the packaging API docs somewhere to help support users in need of this workflow.

**Comment by ewrenn8** [comment]
Superseded by #244 to capture the new workflow
