### ISSUE TITLE
Rename Packaging API groups

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kapp-controller#172]
In order to make the grouping of packaging resources clearer, we would like to rename the api groups. Here are the suggested names, but these are definitely open to iteration:
```
install.package.carvel.dev => packaging.carvel.dev
L PackageRepository
L Package (used to be InstalledPackage)

package.carvel.dev => data.packaging.carvel.dev
L PackageInfo (used to be Package)
L PackageManifest (used to be PackageVersion)

N/A => internal.packaging.carvel.dev
L InternalPackageInfo
L InternalPackageManifest
```

**Comment by cppforlife** [comment]
where would InternalPackaging live?

**Comment by cppforlife** [comment]
i wonder if PackageRepository and Package should be in the same group because they both configure cluster in particular way. on top of that, we also allow "free range" Package CRs which is equivalent to loading up PackageRepo with bunch of Package CRs.

**Comment by ewrenn8** [comment]
> where would InternalPackaging live?

Not sure I understand. InternalPackage would be under the `internal.packaging.carvel.dev` api group.

> i wonder if PackageRepository and Package should be in the same group because they both configure cluster in particular way

I believe this means PackageRepository would need to be served by the aggregated API server as well, since aggregated api servers are registered by api group.

**Comment by cppforlife** [comment]
it says `# we intend to delete this group` next to internal group. sounds like we keeping it?

> I believe this means PackageRepository would need to be served by the aggregated API server as well, since aggregated api servers are registered by api group.

ah shit, that's too much work.

**Comment by ewrenn8** [comment]
Yea, I just meant later on when we come to a conclusion on storage mechanism for packages, we can delete the internal group.

**Comment by ewrenn8** [comment]
added in #208; released in alpha.10
