### ISSUE TITLE
kapp-controller should not downgrade the installed package if the current Package CR is removed

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#183]
**Describe the problem/challenge you have**
Suppose the following is true on the cluster:

- Repo 1 is available on the cluster with Package CR "my_package v1"
- Repo 2 is also available on the cluster with Package CR "my_package v2"
- An InstalledPackage CR is deployed to install the latest version of the my_package
- Based on the InstalledPackage CR, kapp-controller will install "my_package v2" since it is the latest

Now, lets assume that the Repo 2 is removed from the cluster that will remove the Package CR for "my_package v2"
In the current implementation, kapp-controller might downgrade the installed version of the package to v1 since now that is the latest version available on the cluster.

We need to prevent this from happening so that kapp-controller does not automatically downgrade the version of an installed package.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen. If applicable a visual representation of the UX.]

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Comment by cppforlife** [comment]
included in https://github.com/vmware-tanzu/carvel-kapp-controller/pull/353

**Comment by danielhelfand** [comment]
Available in v0.25.0: https://github.com/vmware-tanzu/carvel-kapp-controller/releases/tag/v0.25.0
