### ISSUE TITLE
Add upgrade testing

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kapp-controller#186]
**Describe the problem/challenge you have**
We dont have any tests that verify upgrading is possible

**Describe the solution you'd like**
A test that will fail if kapp-controller can't be smoothly upgraded

**Anything else you would like to add:**

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by aaronshurley** [comment]
@ewrenn8 @danielhelfand Did we do this? Or have our upgrade tests only been manual so far?

**Comment by ewrenn8** [comment]
Just manual

**Comment by danielhelfand** [comment]
One thing we could think about here is adding a separate GitHub action workflow in CI that spins up a minikube cluster deploys the last released version of kapp-controller and then proceeds with the regular install. This way, it will not completely fail the test workflow if we are expecting breaking changes, but it can give us a warning. We could also run the usual test suite to verify further.
