### ISSUE TITLE
Namespace Packaging API resources

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kapp-controller#203]
**Describe the problem/challenge you have**
Packaging API resources should be namespaced. This will enable more multi-tenant workflows and provide more flexibility to consumers.

**Describe the solution you'd like**
For Packcages, there should be a "global" namespace which will contain packages available to all other namesapces. A combination of namespace and global namespace packages will be presented to the user when listing. Any Packages in a namespace that collide with the global ones will be preferred. 

For PackageRepositories, there will again be a global namespace, but these repos will not be presented to a user when listing repos.

InstalledPackages are already namespaced and will not change.

**Anything else you would like to add:**
This will make repo auth more intuitive as referencing secrets will be less complicated.

For the apiserver implementation, Kubernetes machinery adds the namespace as a value to the context passed in to the REST implementation. This can be accessed using [this function](https://github.com/kubernetes/apiserver/blob/33b1fb2f66fb9d8c07f08f9bbbac6a2054056234/pkg/endpoints/request/context.go). We will also have to update the REST implementation to report that the resource is namespace.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by voor** [comment]
This certainly makes sense how it's phrased here.

If there could be some sort of "sanity check" somewhere that triggers a Package including a CRD as "it's highly recommended this be a global namespace Package" we can provide provide good guidance and best practices to Package developers on the dangers of namespaced Packages.

**Comment by vibhas** [comment]
Adding a note here that we could consider. 

> For PackageRepositories, there will again be a global namespace, but these repos will not be presented to a user when listing repos.

As a consumer, I may want to check the list of Package Repositories added to my cluster before adding a new one. So, it might be helpful to also list the repositories that are available on a global namespace.

**Comment by ewrenn8** [comment]
Release in `v0.20.0-rc.1`
