### ISSUE TITLE
Use `ytt` flag to accept data values as plain YAML file

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#209]
**Describe the problem/challenge you have**
Package consumers do not need to know which templating tool is used by a package. They should be able to provide a plain YAML file when providing data values in an InstalledPackage. In order to support this, `ytt` is going to provide a flag to accept data values as a plain YAML file. kapp-controller should make use of the new flag when installing a package.

For details on ytt, refer to this [ytt epic](https://github.com/vmware-tanzu/carvel-ytt/issues/381)
[A description of the current challenge that you are experiencing.]

**Describe the solution you'd like**
[A clear and concise description of what you want to happen. If applicable a visual representation of the UX.]

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
Added in #216 and released in `v0.19.0-alpha.10`
