### ISSUE TITLE
Packaging Docs Improvements

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#211]
**Describe the problem/challenge you have**
Trying to capture various packaging doc improvements in this issue.

- [ ] We should try to clarify how kapp-controller is going to handle the installed packages when a repository is removed from the cluster. 
- [ ] We should add docs on how to use OpenAPI schema in PackageVersion CR. We can use an example and add it to the "_Terminology & APIs_" page and also on the "_Authoring packages_" page.]
- [ ] We should add docs on how a consumer can install a pre-release version.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
> We should try to clarify how kapp-controller is going to handle the installed packages when a repository is removed from the cluster.

When a PackageRepo and associated Packages/PackageVersions are removed currently, InstalledPackages will continue to sync with the Package/PackageVersion and eventually hit an error saying that no PackageVersions could be found: `Reconcile failed: Expected to find at least one version, but did not`. While the InstalledPackage reconciliation won't go through, the resources that were deployed originally by the InstalledPackage will remain unaffected. 

Not sure where the best place to fit this in is. Was thinking about some sort of FAQ page to capture this. And eventually we can also add other questions to it as well that don't fit perfectly in other packaging docs.

**Comment by danielhelfand** [comment]
> We should add docs on how a consumer can install a pre-release version.

Thinking a good place for this information will be the [packaging api overview docs](https://carvel.dev/kapp-controller/docs/latest/packaging). Similar to how the package author docs link to a small section at the [bottom of the packaging api overview docs](https://carvel.dev/kapp-controller/docs/latest/packaging/#artifact-formats) for supplemental information, the package consumption docs could have some details on installing prereleases. The package consumption workflow docs could link to this section from the [Installing a package section](https://carvel.dev/kapp-controller/docs/latest/package-consumption/#installing-a-package).

**Comment by vibhas** [comment]
> Not sure where the best place to fit this in is. Was thinking about some sort of FAQ page to capture this. And eventually we can also add other questions to it as well that don't fit perfectly in other packaging docs.

I think creating a FAQ page would be super helpful and we can keep on adding things there as we hear more common questions from the users. ytt also has a similar [FAQ page](https://carvel.dev/ytt/docs/latest/faq/).

**Comment by danielhelfand** [comment]
Closing as all associated docs prs were merged.
