### ISSUE TITLE
"Error strings should not be capitalized" - golang wiki

### ISSUE THREAD

**Issue by phil9909** [carvel-dev/kapp-controller#22]
I saw the commit "minor stylistic fixes to git creds error messages" https://github.com/k14s/kapp-controller/commit/04835f7f3db7257bc2e0b8fc9313664f3d6e3979 which actually makes things worse according to  https://github.com/golang/go/wiki/CodeReviewComments#error-strings. Because this project uses capitalized error messages everywhere, that commit might still be valid for consistency.

@cppforlife I can create a PR which changes all errors to lower-case, if you want.

**Comment by cppforlife** [comment]
@phil9909 all error messages in k14s projects are capitalized (e.g. `Wrapper one: Wrapper two: Error`) to make it easier to "see wrapping levels" within long error messages. in this case i would actually disagree with go wiki description.

**Comment by phil9909** [comment]
I don't have a strong opinion on whether capitalizing or not capitalizing is a good idea. But I dislike the idea of having it mixed.

And - without any disrespect here - I don't think k14s has enough power to change the go-ecosystem.

So what we get won't be `Wrapper one: Wrapper two: Error` rather something like this: `Wrapper one: Wrapper two: error` and embedders of k14s projects will get `wrap one: Wrapper two: Wrapper three: error`.

My two cents. In the end, it's up to you.

**Comment by lucaschimweg** [comment]
I would also agree with @phil9909. While capitalized error messages easier to read when every new message is capitalized, having mixed messages makes wrapped error messages quite unreadable. 

You get the feeling you can rely on capital letters to find the start of a new wrapper, which is not always the case. Especially the original error message after all wrappers will usually come from go and will therefor not be capitalized.

**Comment by cppforlife** [comment]
> I don't think k14s has enough power to change the go-ecosystem.

dont think goal is to try to change the ecosystem. most of the error messages we deal with our written by us.

the other challenge here is formatting. we try to guess formatting of error messages that for example come from Kubernetes API server to show them in friendlier ways. 

> You get the feeling you can rely on capital letters to find the start of a new wrapper, which is not always the case.

that's right. but it works ok for formatting without boiling the entire ocean.

**Comment by cppforlife** [comment]
closing for now. if there is more thoughts on this topic feel free to reopen.
