### ISSUE TITLE
Annotate deployed pods with version of component

### ISSUE THREAD

**Issue by vijaykatam** [carvel-dev/kapp-controller#223]
**Describe the problem/challenge you have**
When deploying packages with imgpkg bundles the tag of a container is replaced with sha256 in a deployed pod/deployement/daemonset. This is a challenge for serviceability when I need to figure out what tag of a container is deployed. It requires me look at the sha and comparing in registry and if I don't have access to registry then I have to expand the imgpkg bunde retrived from Package CR and look in .images.yml

**Describe the solution you'd like**
Add a kapp annotation with the tag of the container on the Pod/Deployment/Daemonset objects.

**Anything else you would like to add:**
It would be useful to have something like `imgpkg inspect` instead of me trying to do something like `imgpkg pull -b bundle -o /tmp/bundle && cat /tmp/bundle.imgpkg/images.yml` to inspect tags of containers.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by timothysc** [comment]
:+1: from me.

**Comment by cppforlife** [comment]
kbld in theory already has this capability (it generates kbld.k14s.io/images annotation); however, we are not recording "source" tag information when generating .imgpkg/images.yml. so to address this we need:

- record metadata at the time of .imgpkg/images.yml generation (we got annotations field for each image)
- use this metadata when we apply updated image refs and annotate resources

im 👍 for this feature as well.

cc @aaronshurley @vibhas

**Comment by jorgemoralespou** [comment]
I think this has already been requested: https://github.com/vmware-tanzu/carvel-imgpkg/issues/124, although from the end user point of view, it would probably need to have some UX in the package CLI

**Comment by vijaykatam** [comment]
We can ignore `imgpkg inspect` part in lieu of vmware-tanzu/carvel-imgpkg#124. The other part of the request is still valid.

**Comment by frapposelli** [comment]
👍🏻 from me for this feature.

**Comment by aaronshurley** [comment]
We created [an issue for kbld](https://github.com/vmware-tanzu/carvel-kbld/issues/113) and have prioritized it. Once that is completed and a release is published, kapp-controller will just need to update its kbld.

**Comment by danielhelfand** [comment]
This has been addressed in v0.25.0: https://github.com/vmware-tanzu/carvel-kapp-controller/releases/tag/v0.25.0
