### ISSUE TITLE
Manual End to End Testing of the Packaging APIs

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#232]
**Describe the problem/challenge you have**
Before releasing the new packaging APIs, we should spend dedicated time doing a thorough manual end-to-end testing. Few things to consider here:

- Manual fuzz testing, general workflow UX
  - creating resources with the wrong fields, weird names
  - checking for error messages from the apiserver
  - global namespace and namespace package collisions
  - running various kubectl commands to ensure they work (specifically around the namespace)
- Walkthrough the persona workflow/script (to validate that our docs are sufficient/correct and to check for basic scenario error messages)

**Comment by ewrenn8** [comment]
Changes included in `v0.20.0`
