### ISSUE TITLE
Stress/Load Testing of the Packaging APIs

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#233]
**Describe the problem/challenge you have**
Before releasing the new packaging APIs, we should spend dedicated time doing a stress/load testing to make sure that the APIs scale well. Few things to consider here:

- We could set up a GKE instance and scale it up.
- The main concern is how the PackageInstall and Package APIs hold up.
- We can assume each package has a few versions. A rough upper-bound could be ~1000 for now.
  - We could use this for our end-to-end asset as well.

**Comment by ewrenn8** [comment]
A few PRs have come out of initial testing: #250 #246 #248

We are getting trace logs for `gets` and `lists` of Packages because the endpoints are taking >500ms to respond. I will look into this to see if there are any performance improvements we can make

**Comment by ewrenn8** [comment]
Opened #256 to capture outstanding work
