### ISSUE TITLE
Feature: PackageRepository can automatically auth to private registries when secretgen-controller is in the cluster

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kapp-controller#242]
### Problem Description
Right now, the process of creating a package repository that can auth to a private registry is an entirely manual one. The user needs to create a secret with the authorization details, and then correctly reference it within their repository yaml. The manual nature of this makes it prone to human error.

### Solution Description
kapp-controller is able to automatically handle the auth details of a package repository.

#### 🟢 Public repo

**Given** A repo bundle stored in a public registry
**When** A user adds a PackageRepository CR with the repo's url
**And** Successfully fetches the repository bundle

**Note:** For now, since kapp-controller can't determine if a registry url is public or private, this may require creating a placeholder secret anyways.

---
#### 🟢 Private Repo

**Given** A repo bundle stored in a private registry
**When** A user adds a PackageRepository CR with the repo's url
**Then** kapp-controller creates a placeholder secret for the repository fetch
**And** Eventually kapp-controller successfully fetches the repository bundle

---
#### 🟢 Private Repo with explicit auth

**Given** A repo bundle stored in a private registry
**When** A user adds a PackageRepository CR with the repo's url and explicit auth configuration
**Then** kapp-controller **does not** create a placeholder secret for the repository fetch
**And** Eventually kapp-controller successfully fetches the repository bundle

---
#### 🔴 Credentials are not exported

**Given** a package repository with a fetch stage pulling from a private registry
**And** No secrets are exported (secretgen-controller behavior)
**When** a user creates a PackageRepository CR to fetch the repo
**Then** kapp-controller will create a placeholder secret
**And** Will add an error message detailing the auth failure from the registry when fetching

---
#### 🔴 Credentials are exported but not valid

**Given** a package repository with a fetch stage pulling from a private registry
**And** The exported credentials don't work (secretgen-controller behavior)
**When** a user creates a PackageRepository CR to fetch the repo
**Then** kapp-controller will create a placeholder secret
**And** Will add an error message detailing the auth failure from the registry when fetching

### More Info
To do this, we plan on adding a feature to secretgen-controller (SGC) called placeholder secrets. Essentially, there will be a namespace with some exported secret, and when SGC detects that a placeholder secret matching some criteria has been created in a another namespace, it will fill in the details of the placeholder with the same content as the exported secret. With this feature in place, kapp-controller will just need to create the appropriate placeholder secret and add it to the auth details of a repo during reconciliation.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
We are estimating this as a larger story based on the following considerations:
* We need as a starting point an integration test between kapp-controller and secretgen-controller for the happy path scenario. Seeing as this will be the first test written for this, it will take some time to fully figure out this pattern. 
* Additionally, there is likely to be more than one test needed to fully verify this feature: 
  * multiple registries need auth in this case?
  * failure tests on both the secretgen-controller/kapp-controller sides to verify unhappy paths
  * unit tests where applicable for more quick feedback
* Developing placeholder secret functionality for secretgen-controller (This should potentially be split out into a separate story?)
* Developing the integration between kapp-controller and secretgen-controller
