### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by aaronshurley** [carvel-dev/kapp-controller#245]
_To be filled in..._

**Comment by danielhelfand** [comment]
@aaronshurley Is this epic going to be filled in still?

**Comment by aaronshurley** [comment]
Yeah... Just haven't had a chance to focus on this yet, but thanks for checking in. It's still TBD as to when we'd start this track of work since we have some other higher priorities. I'll chat with @vibhas about when we might give this work some attention.

**Comment by vibhas** [comment]
I have tried to capture the use cases for both upgrades and dependency management in this issue: https://github.com/vmware-tanzu/carvel-kapp-controller/issues/361

I am going to close this issue in favor of that one.
