### ISSUE TITLE
Question: Docs search for latest version is not working temporarily?

### ISSUE THREAD

**Issue by karuppiah7890** [carvel-dev/kapp-controller#253]
On this page, https://carvel.dev/kapp-controller/docs/latest/ , I tried to search for `package repository` but it always said no results

Have the latest docs been indexed?

**Comment by karuppiah7890** [comment]
I remember a similar issue happening in Contour - https://github.com/projectcontour/contour/issues/3742

**Comment by danielhelfand** [comment]
Thanks for reporting @karuppiah7890. 

Not quite sure how the searching is set up in our [carvel.dev repository](https://github.com/vmware-tanzu/carvel.dev), but I can reproduce the search issues you are running into. It's possible enabling search in general for kapp-controller page may have never been set up as the kapp-controller page was hidden as we developed it in parallel to new kapp-controller features. As when I search for anything, no results are coming back. We'll look into this and try to enable search functionality.

**Comment by danielhelfand** [comment]
I have opened https://github.com/algolia/docsearch-configs/pull/4281 for this issue

**Comment by danielhelfand** [comment]
This looks to be fixed now. Thanks again for pointing out this issue @karuppiah7890. Really helped with pointing to right direction for the fix. Let us know if there is any further issue for you.

**Comment by karuppiah7890** [comment]
Thanks a lot @danielhelfand !! It works now !
