### ISSUE TITLE
Need info on how to configure package when deploying 

### ISSUE THREAD

**Issue by qnetter** [carvel-dev/kapp-controller#274]
**Describe the problem/challenge you have**
Need to know configurability of package.

**Describe the solution you'd like**
10. As a user, I want to know what configuration values I can use and what value types these values might take in order to configure my Package when deployed to the cluster.

**Anything else you would like to add:**

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by qnetter** [comment]
tanzu package <package-name> man would be nice to be able to display the package docs and explanation of configurable values.

**Comment by qnetter** [comment]
CLI plugin issue. Closing.

**Comment by qnetter** [comment]
CLI and kappa-controller involvement.

**Comment by ewrenn8** [comment]
This is exposed via the valuesSchema.openAPIV3 field on the Package CR.
