### ISSUE TITLE
Configuration should be validated

### ISSUE THREAD

**Issue by qnetter** [carvel-dev/kapp-controller#275]
**Describe the problem/challenge you have**
I don't want a package deployed or attempted if the config is invalid.

**Describe the solution you'd like**
 11. As a user, I want to get an imperative error if I’m trying to create configuration to a package that is not valid, so that the package is not even tried to be deployed.

**Anything else you would like to add:**

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by ewrenn8** [comment]
Im not quite sure what defines an invalid package, could you expand on that a bit more?

**Comment by danielhelfand** [comment]
Agreed that invalid Package is a bit vague to me as well. 

Is this regarding aspects of the Package schema (i.e. creating a Package with unknown keys or submitting data of an invalid type for a field)?

If so, we have support for this.

If it's not, curious to get more specific pain points of using kapp-controller that we could address through validation.

**Comment by aaronshurley** [comment]
@qnetter any thoughts on the above questions?
