### ISSUE TITLE
Docs: Document support for providing overlays as annotations on PackageInstalls

### ISSUE THREAD

**Issue by qnetter** [carvel-dev/kapp-controller#281]
**Describe the problem/challenge you have**
It should be possible to customize on top of a standard package config.

**Describe the solution you'd like**
21. As a user, I want to provide some customization to an existing package (i.e. provide a user provided overlay) so that I can customize some package behaviour.

**Anything else you would like to add:**
---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by ewrenn8** [comment]
@qnetter is this for providing overlays to the PackageInstall to customize the underlying software, or providing overlays that will actually change the Package definition?

**Comment by qnetter** [comment]
@jorgemoralespou can you qualify this?

**Comment by jorgemoralespou** [comment]
Yes, this is to provide overlays to a PackageInstall to further customize the underlying software.
In kapp-controller this is already tracked: https://github.com/vmware-tanzu/carvel-kapp-controller/issues/123 and AFAIK is implemented, although not documented anywhere. Solution is described here: https://github.com/vmware-tanzu/carvel-kapp-controller/issues/123#issuecomment-848084192

I have tested this from kapp-controller side some weeks back and it works.

**Comment by ewrenn8** [comment]
Ok, I will update this issue to be a docs issue and we can use this to track writing the docs.

**Comment by aaronshurley** [comment]
The current thinking is to incrementally improve the docs. We should [extract this example](https://carvel.dev/kapp-controller/docs/latest/packaging/#adding-paths) to a separate page and consider enhancing the example.
