### ISSUE TITLE
Tests for Integration with secretgen-controller

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#282]
As kapp-controller implements the proposal for authentication to private registries, there will need to be a way to write tests for how kapp-controller works with [secretgen-controller](https://github.com/vmware-tanzu/carvel-secretgen-controller). 

secretgen-controller will be the primary way of supporting authentication to private registries via kapp-controller so it will be important to have a way to support adding secretgen-controller to a cluster to run tests around private registry authentication.

Related issues that this feature will support: 
* #242
* #243

The desired behavior is for adding a testing solution around secretgen-controller is that by default kapp-controller does not run tests where secretgen-controller is assumed to be installed. This is mainly because kapp-controller should still be able to run even without secretgen-controller installed. However, in CI, these new tests should always run.

Some considerations for this issue are as follows:
* Should we create a dedicated Package CR for secretgen-controller so that it can easily be installed for testing?
* How should tests for kapp-controller with secretgen-controller be enabled (e.g. an environment variable?)
* What changes should happen in CI (i.e. [GitHub action](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/7c1bfe00fd9aa229c0356d2ac030709813e759df/.github/workflows/test-gh.yml)/hack scripts) to support this?
* Provide documentation on how to enable the running of these tests

**Comment by aaronshurley** [comment]
Some notes:
- move the packaging of kapp-controller and secretgen-controller outside of this story. this story will focus on making the integration tests configurable
- consider these tests to be disabled by default (requiring the user to enable them)

**Comment by danielhelfand** [comment]
Adding a note of how another Carvel project (kbld) implemented test skipping. Not to say this should be the final approach here, but just an example to consider.

https://github.com/vmware-tanzu/carvel-kbld/blob/b39a5bf1bc8c6bd92e949376554d438123944941/.github/workflows/test-gh.yml#L65

https://github.com/vmware-tanzu/carvel-kbld/blob/5ac3423555fe9e2dd8206f1fb343104e5f2aa0c5/test/e2e/build_kubectl_buildkit_test.go#L61
