### ISSUE TITLE
Review for Helm Chart

### ISSUE THREAD

**Issue by linkdd** [carvel-dev/kapp-controller#283]
# Describe the problem/challenge you have

At our company, [Link Society](https://github.com/link-society), we are currently working on a supervision engine on Kubernetes: [Kubirds](https://kubirds.com).

Its dependencies provide no Helm charts, therefore upgrading and uninstalling becomes an issue.

Fortunately `kapp` and `kapp-controller` resolves this versioning problem.

Since we're looking at integrating our product on the [DigitalOcean Marketplace](https://github.com/digitalocean/marketplace-kubernetes/), we were looking to integrate our dependencies as well.

This means also integrating **kapp-controller** in the marketplace (Work In Progress on our side).

But only `helm` and `kubectl` are officially supported in their workflow (no `kapp`)

# Describe the solution you'd like

To integrate **kapp-controller** to their marketplace, we started writing and maintaining an Helm Chart based on the latest release (`0.20.0`), the PR to our own Helm repository can be found here: [link-society/charts#29](https://github.com/link-society/charts/pull/29).

We would appreciate if people could review this chart and maybe give us insight on how it could be integrated upstream.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
Hey @linkdd! Thank you for opening this.

Think it would be great for some of us in the Carvel community to take a look at Link Society's use of kapp-controller. We can follow up in the pr you have linked.

I had some follow up questions as well based on some of the information provided. Looking forward to your responses.

> Its dependencies provide no Helm charts, therefore upgrading and uninstalling becomes an issue.

> Fortunately kapp and kapp-controller resolves this versioning problem.

To understand a little more about your use case, are you saying Kubirds has dependencies and you are using kapp-controller's [package management API concepts](https://carvel.dev/kapp-controller/docs/latest/packaging/) to address this? Something else? Just trying to gain more understanding of how you are all using kapp-controller.

> Since we're looking at integrating our product on the DigitalOcean Marketplace, we were looking to integrate our dependencies as well.

> This means also integrating kapp-controller in the marketplace (Work In Progress on our side).

> But only helm and kubectl are officially supported in their workflow (no kapp)

I am curious to learn a bit more about the process of integrating a product into the DigitalOcean Marketplace. What is the workflow that is used for including products in the marketplace? Perhaps it might be worth trying to include kapp.

>  We would appreciate if people could review this chart and maybe give us insight on how it could be integrated upstream.

As far as contributing upstream, is your thought that the helm chart should be maintained as part of the kapp-controller repository itself? Something else?

**Comment by linkdd** [comment]
Thanks for the reply @danielhelfand ! 😄 

> We can follow up in the pr you have linked.

That would be awesome, we would like confirmation about some aspects of the chart, like:

 - is more than 1 replica supported? (leader election)
 - are the annotations correct/useful, and how are they used by the source code?

> To understand a little more about your use case, are you saying Kubirds has dependencies and you are using kapp-controller's package management API concepts to address this? Something else? Just trying to gain more understanding of how you are all using kapp-controller.

Kubirds relies on other technologies, like TektonCD, RabbitMQ and Redis.

 - TektonCD's upstream only provides a YAML to `kubectl apply` in your cluster
 - we install RabbitMQ via the official Cluster Operator, upstream only provides a YAML to `kubectl apply` as well
 - we install Redis via this [Redis Operator](https://github.com/spotahome/redis-operator), which provides an Helm Chart

Using `kapp` or the `Application` resource from `kapp-controller`, instead of `kubectl apply` allows easy upgrade/uninstall of those technologies.

> I am curious to learn a bit more about the process of integrating a product into the DigitalOcean Marketplace. What is the workflow that is used for including products in the marketplace? Perhaps it might be worth trying to include kapp.

As described in this [document](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md), it is required to provide the following scripts:

 - `deploy.sh` to install the application
 - `upgrade.sh` to upgrade it
 - `uninstall.sh` to uninstall it

**NB:** It seems not all the stacks follows the rules

Using the **kapp-controller** would ease even more the integration of other stacks (such as the RabbitMQ Cluster Operator or TektonCD), because we would not need to maintain unofficial Helm charts for those.

> As far as contributing upstream, is your thought that the helm chart should be maintained as part of the kapp-controller repository itself? Something else?

As for now, Link Society will maintain this chart, because it seems the deployment options of the **kapp-controller** are generated for each release. So adding the chart as-is upstream would only add burden to the team.

I was looking at the scripts in the `hack/` folder of the repository that are used to generate the YAML manifests, and was wondering how we could write a script to generate the Helm Chart.

This would be, in my opinion, the best option.

**Comment by danielhelfand** [comment]
Hey @linkdd,

Sorry for the late reply here. We'll be taking a look at your pr this week some time and thanks for the patience. To answer a few questions:

> is more than 1 replica supported? (leader election)

Not at this time. We currently only ship with 1 replica. Is this something you are interested in seeing with kapp-controller? 

> are the annotations correct/useful, and how are they used by the source code?

Do you have an example of what annotations you are referring to? Do you mean the ytt data values found in the configuration (e.g. https://github.com/vmware-tanzu/carvel-kapp-controller/blob/84fbfc9e426bfc9b4200319c38de29b0b7f82598/config/deployment.yml#L25)?

> As for now, Link Society will maintain this chart, because it seems the deployment options of the kapp-controller are generated for each release. So adding the chart as-is upstream would only add burden to the team.

That works for us as our team does not currently have much work planned around officially supporting a helm chart. But we can definitely answer questions for kapp-controller itself in your personal maintenance of the chart.

**Comment by linkdd** [comment]
Hey @danielhelfand, thanks for the review!

I'm gonna upgrade the chart to the latest release (v0.21.0) before merging it.

> Not at this time. We currently only ship with 1 replica. Is this something you are interested in seeing with kapp-controller?

Ok so I'll remove the variable `replicaCount` to avoid wrong configurations.

It's always interesting to allow multiple replicas for high availability. But leader election can be tricky 😄  (well, in Elixir, thanks to [libcluster](https://hexdocs.pm/libcluster/readme.html) and [horde](https://hexdocs.pm/horde/getting_started.html), you can avoid leader election and have multiple replicas out of the box).

> Do you have an example of what annotations you are referring to?

I was referring to this snippet in the Chart:

```yaml
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Type: git
          Dirty: false
          RemoteURL: {{ .Values.metadata.images.remote }}
          SHA: {{ .Values.metadata.images.revision }}
        URL: {{ .Values.image.repository }}:{{ .Values.image.tag }}
```

In the `release.yml` file you can find:

```yaml
        - Path: /Users/embp/go/src/github.com/vmware-tanzu/carvel-kapp-controller
          Type: local
```

But I removed it, and I'm not sure what it does.

Also, in the CRD `PackageRepository`, there is this annotation:

```yaml
  annotations:
    packaging.carvel.dev/global-namespace: {{ .Release.Namespace }}-packaging-global
```

Since its value is dynamic, it cannot resides in the `crds` folder of the chart (not templated). Forcing me to use a subchart (I still need to test every scenarios to ensure it works as expected).

But should it be dynamic? As of now, multiple instance of the same chart cannot all create/manage CRDs.

I'm not sure how this annotation is used and why it would be on the CRD.

IMHO, configuration options such as this should be in a ConfigMap and not as annotations.

**Comment by linkdd** [comment]
Hello @danielhelfand,

Sorry to bother you again 😅

After installing the controller with my Helm chart, I get the following error:

```
{"level":"error","ts":1627479059.0715973,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"Package.data.packaging.carvel.dev","error":"no matches for kind \"Package\" in version \"data.packaging.carvel.dev/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\tsigs.k8s.io/controller-runtime@v0.7.0/pkg/source/source.go:117\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tsigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:159\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\tsigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:205\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\tsigs.k8s.io/controller-runtime@v0.7.0/pkg/manager/internal.go:691"}
{"level":"error","ts":1627479059.0721104,"logger":"controller-runtime.manager","msg":"error received after stop sequence was engaged","error":"Timeout: failed waiting for *v1.Secret Informer to sync","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1\n\tsigs.k8s.io/controller-runtime@v0.7.0/pkg/manager/internal.go:547"}
{"level":"error","ts":1627479059.072306,"logger":"controller-runtime.manager","msg":"error received after stop sequence was engaged","error":"Timeout: failed waiting for *v1.Secret Informer to sync","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1\n\tsigs.k8s.io/controller-runtime@v0.7.0/pkg/manager/internal.go:547"}
{"level":"error","ts":1627479059.072353,"logger":"controller-runtime.manager","msg":"error received after stop sequence was engaged","error":"context canceled","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1\n\tsigs.k8s.io/controller-runtime@v0.7.0/pkg/manager/internal.go:547"}
{"level":"error","ts":1627479059.0726852,"logger":"kc.controller","msg":"unable to run manager","error":"no matches for kind \"Package\" in version \"data.packaging.carvel.dev/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.2.0/zapr.go:132\ngithub.com/vmware-tanzu/carvel-kapp-controller/cmd/controller.Run\n\tgithub.com/vmware-tanzu/carvel-kapp-controller/cmd/controller/run.go:240\nmain.main\n\tcommand-line-arguments/main.go:42\nruntime.main\n\truntime/proc.go:225"}
{"level":"error","ts":1627479059.0815861,"logger":"kc.init","msg":"Could not start controller","error":"exit status 1","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.2.0/zapr.go:132\ngithub.com/vmware-tanzu/carvel-kapp-controller/cmd/controllerinit.Run\n\tgithub.com/vmware-tanzu/carvel-kapp-controller/cmd/controllerinit/run.go:38\nmain.main\n\tcommand-line-arguments/main.go:46\nruntime.main\n\truntime/proc.go:225"}
```

It seems there is a CRD `Package` missing, and I can't find it either in the `release.yml` nor in the `config/crds.yml` file from the repository.

Am I missing something?

**Comment by danielhelfand** [comment]
```yaml
annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Type: git
          Dirty: false
          RemoteURL: {{ .Values.metadata.images.remote }}
          SHA: {{ .Values.metadata.images.revision }}
        URL: {{ .Values.image.repository }}:{{ .Values.image.tag }}
```

This is added by [`kbld`](https://carvel.dev/kbld/), which we use to build the kapp-controller container image and include specific details on the image (e.g. the image digest).

```
annotations:
    packaging.carvel.dev/global-namespace: {{ .Release.Namespace }}-packaging-global
```

This annotation is used to help denote the global namespace for kapp-controller. Any repository or individual package installed to this namespace has global scope and can be seen across any namespace on the cluster. More here: https://carvel.dev/kapp-controller/docs/latest/packaging/#namespacing

It's mainly used for clients at this point (e.g. a CLI that is looking to list global resources).

> It seems there is a CRD Package missing, and I can't find it either in the release.yml nor in the config/crds.yml file from the repository.

> Am I missing something?

The Package resource is served by an aggregated API server that is backed by an internal CRD (i.e. [InternalPackage](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/8b86a7b15379c94c96ce6a6de31fb966e2e1cd3c/config/crds.yml#L60))

**Comment by linkdd** [comment]
Ok thanks, looking at the source code, I  found the problem:

https://github.com/vmware-tanzu/carvel-kapp-controller/blob/65963fdeca26912025d0aa5ab167cda2c3440f60/pkg/apiserver/apiserver.go#L201

The name of the service is statically defined, and in my chart the service is named `{{ include "kapp-controller.fullname" . }}-packaging-api`

So the API server cannot find the service which triggers a `FailedDiscoveryCheck` in the `APIService` resource.

Also: https://github.com/vmware-tanzu/carvel-kapp-controller/blob/65963fdeca26912025d0aa5ab167cda2c3440f60/pkg/apiserver/apiserver.go#L46

This line defines statically the name of the `APIService` resource, so I will not be able to make it a dynamic name in the Helm chart.

This means there is a tight coupling between the name of the resources and the operator, which prevents multiple release of the same chart in the cluster.

**NB:** Using an `APIService` would anyway prevents multiple release.

**NB2:** Using the name `packaging-api` could produce name clashes if the operator is installed in another namespace than `kapp-controller` (for example: `default`).

This means that, as of now, Helm should not be used to deploy the operator, which is a problem since we need to be able to upgrade/uninstall the operator and the `kubectl apply` method doesn't provide anything to support that.

**Comment by linkdd** [comment]
@danielhelfand So, I've started a PR to parametrize those values. This would help greatly to finalize this Helm Chart 🙂

**Comment by linkdd** [comment]
The PR has been merged, I'm waiting for the next release (I just upgraded from v0.21.0 to v0.24.0) then I'll close this issue 🙂

Also, would you be open to a PR adding this chart as an installation method on [this page](https://carvel.dev/kapp-controller/docs/latest/install/)?

**Comment by danielhelfand** [comment]
> The PR has been merged, I'm waiting for the next release (I just upgraded from v0.21.0 to v0.24.0) then I'll close this issue 🙂
> 
> Also, would you be open to a PR adding this chart as an installation method on [this page](https://carvel.dev/kapp-controller/docs/latest/install/)?

Sorry for late reply here. 

I think our preference is still to suggest using just the release YAML at this time as documented at https://carvel.dev/kapp-controller/docs/latest/install/. 

The helm chart usage seems like a specific requirement for adding to the Digital Ocean Marketplace.

**Comment by linkdd** [comment]
I finished the Helm chart with the latest version (`0.27.0`).

FYI, I created the PR to the DigitalOcean Marketplace: https://github.com/digitalocean/marketplace-kubernetes/pull/270
