### ISSUE TITLE
Better UX for Including Prereleases in PackageInstall versionSelection 

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#300]
**Describe the problem/challenge you have**

For PackageInstall's referencing a [prerelease package](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/84fbfc9e426bfc9b4200319c38de29b0b7f82598/test/e2e/assets/kc-e2e-test-repo/packages/pkg.test.carvel.dev/pkg.test.carvel.dev.3.0.0-rc.1.yml), a user must provide the following as part of a PackageInstall `.spec.packageRef` to successfully install the prerelease version:

```yaml
versionSelection:
  constraints: 3.0.0-rc.1
  prereleases: {} # <----------
```

Prereleases must not be null as documented in #116. As of the current implementation in kapp-controller, the user is responsible for configuring this setting via the PackageInstall `.spec.packageRef.versionSelection` property.

For users specifying a specific version to install (like above), it might be a nice enhancement to just always consider prereleases as opposed to making users configure this prerelease behavior. 

**Describe the solution you'd like**

To install a prerelease when a specific version is passed, I should not need to specify the `prereleases: {}` property above to install a prerelease version like below:

```yaml
versionSelection:
  constraints: 3.0.0-rc.1
```

**Anything else you would like to add:**

We should consider if there are other cases should have prereleases considered by default. 

We also have a test for the current behavior in place which can be adapted to TDD this feature out: https://github.com/vmware-tanzu/carvel-kapp-controller/blob/84fbfc9e426bfc9b4200319c38de29b0b7f82598/pkg/packageinstall/packageinstall_test.go#L19

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by aaronshurley** [comment]
@danielhelfand I noticed that the GH actions bot closed this out but I think it's still relevant?
