### ISSUE TITLE
Investigate whether the sync default (30s) is appropriate

### ISSUE THREAD

**Issue by aaronshurley** [carvel-dev/kapp-controller#309]
**Describe the problem/challenge you have**
During some general discussions, it's been suggested that the sync default of 30 seconds could create scalability/performance issues in larger environments. Could this be relaxed to a less frequent interval?

**Describe the solution you'd like**
A recommendation and code change, if needed, for a sane sync interval default.

**Anything else you would like to add:**
If anyone from the community has input on this, we'd love to hear your thoughts.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help work on this issue.

**Comment by danielhelfand** [comment]
Seems like this could be solved by making the sync period configurable as mentioned in #373. Going to close this in favor of that issue.
