### ISSUE TITLE
Pin binary dependency versions in source

### ISSUE THREAD

**Issue by lucaschimweg** [carvel-dev/kapp-controller#31]
Right now, kapp-controller builds package the latest version of kapp. This makes it impossible to conclude the kapp version from kapp-controller's version. 

Should we consider pinning kapp's version per kapp-controller release?

tagging my pair @Haegi

**Comment by cppforlife** [comment]
> Should we consider pinning kapp's version per kapp-controller release?

isn't it implicitly "pinned" to version that was included at the time of the build of kapp-controller? may be you have something for pinning?

> This makes it impossible to conclude the kapp version from kapp-controller's version.

how would you want to surface this information? release notes, logs, etc?

i dont think having one product version be dependent on another (eg they always match or something like that) is a good idea since they are two distinct products and evolve independently.

**Comment by lucaschimweg** [comment]
> isn't it implicitly "pinned" to version that was included at the time of the build of kapp-controller? may be you have something for pinning?

The problem is that builds are not reproducible at the moment. I cannot build an old version of the controller if I would want to (at least not the original version with the old Kapp version).

> how would you want to surface this information? release notes, logs, etc?

Maybe? I mean we have release notes for every release, why not use them for that?


> i dont think having one product version be dependent on another (eg they always match or something like that) is a good idea since they are two distinct products and evolve independently.

If the products do evolve independently, they should not be packaged together in my opinion. 

We should also consider Kapp evolving. What if kapp has a breaking change in the way it communicates with the controller? All old versions would be broken and no new builds of old versions could be created.

**Comment by cppforlife** [comment]
> The problem is that builds are not reproducible at the moment. I cannot build an old version of the controller if I would want to (at least not the original version with the old Kapp version).

👍 i understand now what you are after.

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/kapp-controller/commit/9c220933af6585fd30cff50d48979e1c959f3625

**Comment by cppforlife** [comment]
included in https://github.com/k14s/kapp-controller/releases/tag/v0.10.0
