### ISSUE TITLE
Support kapp-controller Proxy Configuration via a Secret

### ISSUE THREAD

**Issue by soumyapanigrahi-code** [carvel-dev/kapp-controller#310]
**Describe the problem/challenge you have**
Kapp controller exposes the ability to configure the controller via a config map which kapp controller will look for and apply as part of the startup processes. However some of the proxy information including passwords are sensitive in nature.

**Describe the solution you'd like**
Kapp controller exposes the ability to configure the controller via a secret.

**Anything else you would like to add:**
Given that kapp controller is gaining popularity and expected to be widely used in air-gapped environments as well, it would be great if this feature request is prioritised.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by aaronshurley** [comment]
@soumyapanigrahi-code Thank you for surfacing this. We understand the use case and are discussing prioritization right now. We'll update this issue soon once we have a better idea of when we'd be able to start working on this.

**Comment by danielhelfand** [comment]
Following up here with some initial design thoughts on how to approach this:
* We will continue to support ConfigMap configuration, but we will recommend the use of Secrets moving forward. We will also reinforce this idea by having kapp-controller prefer using the Secret in a scenario where both the kapp-controller-config ConfigMap/Secret exist. Additionally, [documentation](https://carvel.dev/kapp-controller/docs/latest/controller-config/) should be changed to push the use of Secrets.
* As a means of testing this feature, one thing we should consider is converting our [kapp-controller-config ConfigMap](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/8873d1b0e91aac089536f6050a5835d4b301734b/config-test/config-map.yml) to a Secret.

**Comment by aaronshurley** [comment]
Due to the proposed security improvement of this request, we have moved this to the top of the backlog and will begin working on this today.

**Comment by danielhelfand** [comment]
This feature is available in release v0.22.0: https://github.com/vmware-tanzu/carvel-kapp-controller/releases/tag/v0.22.0

I will keep this open as a reminder to add documentation changes and close once those updates are made.

**Comment by soumyapanigrahi-code** [comment]
Thanks a lot everyone. The quick turn-around time is much appreciated.
