### ISSUE TITLE
Package Authors should be able to provide an icon without degrading the readability of the PackageMetadata CR

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#315]
**Describe the problem/challenge you have**
Package Authors can provide an icon as an SVG Base64 encoded image in the `iconSVGBase64` field of PackageMetadata CR. However, these Base64 encoded strings can be quite long depending on the image size. This can make the YAML file difficult to read and edit.

**Describe the solution you'd like**
We need to figure out a way where authors can provide an icon for their package without degrading the readability of the YAML file itself.

**Anything else you would like to add:**
Currently, we only support the SVG format. It might be also worth looking into how we can support multiple image formats.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
i would recommend putting this issue in "collecting info" bucket (>=6mo) until we have folks use the API for some time.

> Currently, we only support the SVG format. It might be also worth looking into how we can support multiple image formats.

this is intentional so that clients only have to bother with supporting one "resizable" format. it does put the burden on package authors to provide necessary media in said format, but i think that trade off is reasonable since icon is optional.

**Comment by cppforlife** [comment]
closing as stale for now. if new concerns arise, lets reopen.
