### ISSUE TITLE
Move kapp-controller Image from DockerHub to New Registry to Avoid Rate Limiting

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#319]
As kapp-controller continues to gain wider adoption, an issue that has come up is [DockerHub's rate limiting](https://www.docker.com/increase-rate-limits). In order to assure users can successfully pull the kapp-controller image when deploying kapp-controller to a Kubernetes cluster without hitting rate limits, the kapp-controller image should be relocated to a new image registry. 

There are no hard requirements on which registry should be used. There should be some initial research into DockerHub alternatives with the main requirement being avoiding rate limiting errors for kapp-controller users. 

One option that has been suggested is GitHub's container registry, which is free to public images: https://github.com/features/packages

**Comment by aaronshurley** [comment]
Thanks for creating this. We're prioritizing it as `important-soon` so that we can have a more sustainable solution than DockerHub's free capabilities.

**Comment by danielhelfand** [comment]
Just wanted to note here that this will also apply to secretgen-controller, which is stored under the k14s repository. We should open a separate issue there to track this work.

**Comment by vdesikanvmware** [comment]
This would also affect my team. For installing our repo bundle, kapp-controller is required. Can we prioritize and have this fixed?

**Comment by joe-kimmel-vmw** [comment]
i'm looking at ~quay.io~ github registry to understand if it could offer a drop-in replacement.

**Comment by joe-kimmel-vmw** [comment]
note from dmitriy to look at imgpkg release process
