### ISSUE TITLE
Update Carvel Setup Action to Use exclude Instead of only 

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#320]
As part of Carvel's test-gh workflow, most of the Carvel tool suite is installed to build/test kapp-controller on pull request submissions/updates. Since most of the tool suite is installed, it might be simpler to use the carvel-setup-actions [exclude](https://github.com/vmware-tanzu/carvel-setup-action/issues/90) property as opposed to only as shown here: https://github.com/vmware-tanzu/carvel-kapp-controller/blob/d94984a77fa907ac5ecc681e9a842b9877766a6b/.github/workflows/test-gh.yml#L32

Using exclude instead of only, the line could be simplified to the following:

```yaml
exclude: kwt
```

**Comment by aaronshurley** [comment]
Makes sense. Moving this to the unprioritized backlog as _I think_ the impact would be limited to slightly shortening PR feedback loops.  Please let me know if you have any concerns regarding the prioritization. Contributions for this are welcome.

**Comment by neil-hickey** [comment]
We have moved away from using the carvel action for setting up tools in the workflows. We moved to using the install-deps.sh script, so we have one point of declaration for all tool versions instead.

https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/.github/workflows/test-gh.yml#L26-L27
