### ISSUE TITLE
Feature: Allow specifying auth details in PackageInstall annotation

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kapp-controller#325]
**Describe the problem/challenge you have**
There is no escape hatch for providing authentication details to package fetch stages via a PackageInstall

**Describe the solution you'd like**
An annotation that allows specifying the secret containing auth details and the fetch stage the secret should be used in. This will also stop kapp-controller from creating a placeholder secret and using it for that fetch stage

**Anything else you would like to add:**

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by aaronshurley** [comment]
Sounds like this made it into the last release but it needs to be documented.

**Comment by vibhas** [comment]
This was released in v0.23.0
Docs can be found here: https://carvel.dev/kapp-controller/docs/latest/private-registry-auth/#packageinstall
