### ISSUE TITLE
Expose reconcile status as metrics to allow monitoring 

### ISSUE THREAD

**Issue by mhoshi-vm** [carvel-dev/kapp-controller#337]
**Describe the problem/challenge you have**
One thing we need is at least be able to expose the reconcile status to an external monitoring sysytem. We have seen a cluster that was running fine for several days until we realized that it was actually failing to reconcile due to someone mistakenly changed the service account role.

This cannot be identified until somebody executes `kubectl get apps`

**Describe the solution you'd like**
Something like `kubernetes_apps_reconcile_status` metrics being exposed where 0 = success , 1 = fail , 2 = unknown then i think it's easy to monitor

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by mhoshi-vm** [comment]
Hi, 
I am currently trying to develop a pull request. Will try to submit in few days for review.

**Comment by aaronshurley** [comment]
Thanks for creating this issue and submitting a PR!

**Comment by cppforlife** [comment]
PR was merged and shipped some time ago. thank you again @mhoshi-vm
