### ISSUE TITLE
Ensure that private registry authentication documentation mentions IaaS preauth capabilities

### ISSUE THREAD

**Issue by aaronshurley** [carvel-dev/kapp-controller#338]
**Describe the problem/challenge you have**
`imgpkg` recently introduced the capability to [leverage preauthed IaaS registries](https://carvel.dev/imgpkg/docs/latest/auth/#via-iaas). This issue is to ensure that kapp-controller [documentation](https://carvel.dev/kapp-controller/docs/latest/private-registry-auth/) notes this workflow.

**Describe the solution you'd like**
The minimum necessary docs are added to [kapp-controller's private registry auth docs](https://carvel.dev/kapp-controller/docs/latest/private-registry-auth/) to ensure coverage of this use case. Try to point to the source of truth (i.e. imgpkg) when possible.

**Anything else you would like to add:**
Note: This issue was originally written to detail a blog post but we have since decided against that in favor of focusing on our documentation.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
Further work on this story is blocked by a new release of imgpkg/kapp-controller with the bump of imgpkg. We would like to mention the [support for support iaas pre-authed registries](https://github.com/vmware-tanzu/carvel-imgpkg/issues/202) in imgpkg as part of the blog post.

There is a draft available with the initial feature so including information about this new imgpkg feature in there will just need to be added.

**Comment by aaronshurley** [comment]
We're planning to repurpose this issue to add further information to the docs rather than create a blog post.

**Comment by aaronshurley** [comment]
There is a PR for this https://github.com/vmware-tanzu/carvel/pull/242

**Comment by neil-hickey** [comment]
hey @aaronshurley it looks like this one might be done as the PR was merged in. Good to close out?

**Comment by aaronshurley** [comment]
@neil-hickey nice catch! Closing.
