### ISSUE TITLE
Change e2e Tests Retry to iteration count

### ISSUE THREAD

**Issue by joe-kimmel-vmw** [carvel-dev/kapp-controller#351]
Currently our e2e tests use a time-based retry (see e.g. https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/test/e2e/kappcontroller/app_secret_configmap_reconcile_test.go#L98 )  ,  but time is notoriously slippery, especially in "the cloud" (see also https://gist.github.com/timvisee/fcda9bbdff88d45cc9061606b4b923ca ).

Very likely we can replace the existing retry function with a counter that takes an integer (e.g. 10) instead of a time duration (e.g. `10 * time.seconds`) and still calls Sleep(1) ten times.   

Ideally after this task none of our e2e tests will rely on comparing a start time with the current time to determine whether they've retried enough,  but if there's one or two cases that are thornier i think an incremental improvement will also be greatly appreciated.

**Comment by aaronshurley** [comment]
Thanks for creating this @joe-kimmel-vmw! Accepting this and prioritizing it as `important-longterm` since this will provide engineering improvements but isn't something that we need to address too soon. Moving it towards the bottom of the prioritized backlog. We're open to contributions!

**Comment by satyazzz123** [comment]
hello @joe-kimmel-vmw  I am new to carvel-dev can you guide me a little on how to resolve this issue . Thank you.

**Comment by jignyasamishra** [comment]
@joe-kimmel-vmw I have raised a PR . Please have a look. Thank you!
