### ISSUE TITLE
GitHub worklow tests should test latest (or a more recent) version of minikube/k8s

### ISSUE THREAD

**Issue by aaronshurley** [carvel-dev/kapp-controller#352]
**Describe the problem/challenge you have**
I noticed a [kapp PR](https://github.com/vmware-tanzu/carvel-kapp/pull/274/files) was submitted to test against the latest version of minikube, and therefore a recent version of kubernetes. I noticed that [kapp-controller's version of minikube/k8s is manually updated](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/.github/workflows/test-gh.yml#L48). This creates overhead in ensuring that kapp-controller is testing against a recent version of minikube/k8s. If the k8s version that kapp-controller tests against falls out of date then it creates a reduced sense of confidence in kapp-controller's ability to work with k8s.

**Describe the solution you'd like**
An automated way for kapp-controller to test against the latest, or at least a recent version, of kubernetes.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
I think it would be reasonable to always run against the latest minikube version. We are pretty up to date (using 1.21 while latest is 1.23), but making sure kapp-controller is always working against latest moving forward would be nice.

Something to factor in with this is also running kapp-controller against an older version of Kubernetes to have a better understanding if our changes are failing on older versions. This is what kapp also does in this [workflow](https://github.com/vmware-tanzu/carvel-kapp/blob/f3d76470551a142b6a190e6337c38bdb9a87e55b/.github/workflows/test-gh-k8s-1.16.yml). Moving forward, it would be helpful to understand what minimum version of k8s kapp-controller works with.

**Comment by danielhelfand** [comment]
One possible downside to the approach in kapp's CI though is that it would make checksum validation of the minikube binary challenging.
