### ISSUE TITLE
kapp-controller website improvements

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#357]
**Describe the problem/challenge you have**
We made many changes to the kapp-controller website when we launched it as a Package Manager. However, there are still a few more changes that could be made in order for our new users to get a better understanding of the tool and help them get started quickly.

- [ ] Create a custom slug such as "carvel.dev/kubecon" that could be shared in the Kubecon video. This will redirect to kapp-controller's site. We could customize where we want to navigate users to since the contents of the video can't be changed later.
- [ ] The demo video is quite long. Can we do a shorter video something like [this](https://asciinema.org/a/uIcSZvdbrFKKeH2sqrLsFdXym)?
- [ ] Link all the docs appropriately. For eg: The Install Extensions is not linked from Consuming Walkthrough.
- [ ] Re-order the sub-menu in Package Management
- ~[ ] Taking inspiration from ytt vs x doc, we should also have a similar section.~
- ~[ ] Kapp-controller currently uses mostly Carvel tools. However, the vision is that a user could swap some of the tools with the tools of their choice. We need to be clear that it's coming up.~
- [ ] The Katakoda tutorial is still behind authentication. We should try to change it so that users do not need to sign in. If this cannot be done, please capture the reasoning.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
Rationale for not removing katacoda tutorial authentication is that katacoda does not have much documentation on the subject. In general, we should probably consider an alternative to katacoda that will allow for more flexibility and easier maintenance in the long run.
