### ISSUE TITLE
Community meeting demo for private registry authentication 

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#359]
**Describe the problem/challenge you have**
Now that we support private registry authentication on kapp-controller + secretgen-controller, we should share with the community how this feature works.

**Describe the solution you'd like**
During a Carvel community meeting, let's present a short demo about the feature.
- Push a package repository bundle and the package content bundle to a registry that needs authentication
- Try creating a package repository and install a package - it should fail 
- Create a secret that can be exported to all namespace
- Add a package repository
- Install a package

**Comment by aaronshurley** [comment]
After some discussion, we decided that we're not going to perform this demo as the documentation will be sufficient. Closing.
