### ISSUE TITLE
Bump vendir to 0.23.0

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#362]
Once vendir 0.23.0 is available, it will include the following feature: https://github.com/vmware-tanzu/carvel-vendir/pull/107

Including this will be useful to users of kapp-controller's [private authentication workflows](https://carvel.dev/kapp-controller/docs/latest/private-registry-auth/). 

A follow up to this would be #360 which covers the documentation aspect of this new feature.

Bumping the vendir version can be done as follows:
1. Update the vendir version here: https://github.com/vmware-tanzu/carvel-kapp-controller/blob/22299af8dd26423d997c6fefd60d2ba1cd28591a/hack/install-deps.sh#L32
2. Change the checksums: 
* [Darwin](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/22299af8dd26423d997c6fefd60d2ba1cd28591a/hack/install-deps.sh#L40)
* [Linux](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/22299af8dd26423d997c6fefd60d2ba1cd28591a/hack/install-deps.sh#L47)
* These can be grabbed from the [vendir releases page](https://github.com/vmware-tanzu/carvel-vendir/releases) where the checksums are published
3. Submit pull request and verify that CI runs successfully

**Comment by Atharva321** [comment]
Hii, I am interested work on this issue.

**Comment by danielhelfand** [comment]
Hi @Atharva321!

We would be grateful for your help. Please feel free to submit a pull request. The vendir release should be available and this work should be ready to go.

**Comment by Atharva321** [comment]
Done . is it ok?
