### ISSUE TITLE
Enable trivy scan as part of nightly build

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#368]
As described in https://github.com/vmware-tanzu/carvel-kapp/issues/315, it might be helpful for us to consider adding a security scan as part of a nightly build process. This would help us monitor and triage security alerts better for kapp-controller. In particular, conducting a scan of the kapp-controller image could be helpful.

**Comment by cppforlife** [comment]
related: https://github.com/vmware-tanzu/carvel-kapp/issues/315

**Comment by danielhelfand** [comment]
Related work for kapp with their trivy implementation is in the following pr: https://github.com/vmware-tanzu/carvel-kapp/pull/346

**Comment by neil-hickey** [comment]
If noone else is looking, I will spend an hour or so today trying to modify kapp's usage of trivy for kapp-controller 👍

**Comment by neil-hickey** [comment]
I started looking at this, implemented the scanning for kapp-controller filesystem only (on a branch). The docker images are not scanned yet. Will come back to this when priority shifts 👍. 

https://github.com/vmware-tanzu/carvel-kapp-controller/tree/enable-trivy-scan
