### ISSUE TITLE
Add support for required Kubernetes version on packages and enforce a check in `kapp-controller`

### ISSUE THREAD

**Issue by joshrosso** [carvel-dev/kapp-controller#369]
## Feature Request

Packages may require specific features or APIs to be available in Kubernetes for proper installation. As such, a package should be able to declare its required Kubernetes version. `kapp-controller` should enforce this check before allowing a `PackageInstall` to be satisfied.

## Describe alternatives you've considered

This could happened entirely client-side. However, it seems having this server-side (`kapp-controller`) is the appropriate solution.

## Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
Thanks for opening this. 

The case of depending on specific APIs for kapp-controller Packages (e.g. group version kind) seems like something which will definitely be supported as part of our upcoming work on dependency management. 

The Kubernetes version is an interesting case that I think we should further consider and come up with a way to support as well. Thanks for calling this out as we hadn't had a request for this yet.

**Comment by danielhelfand** [comment]
Closing this in favor of #484 where there are some more concrete use cases mentioned.
