### ISSUE TITLE
consider global kapp-controller flag to raise default sync period

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#373]
**Describe the problem/challenge you have**
By default sync period is 30s on App CRs. It might be useful for an administrator to set higher default syncPeriod.

**Describe the solution you'd like**
- add --app-default-sync-period=X flag on kapp-controller (defaulted to 30s)
- add --app-minimum-sync-period=X flag as well (defaulted to 30s)
- add --package-install-default-sync-period=X flag as well (defaulted to 5m)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
Think this would be a good addition. For anyone picking up this issue, a good place to start might be looking at the flags for the controller [here](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/8e1ab43ea190d32f11c0980202b303f762d7be4a/cmd/main.go#L25).

**Comment by joe-kimmel-vmw** [comment]
@danielhelfand @cppforlife the suggestion above to look at the flags is helpful but i think not the full story.   

 The other end of the change imo is that [this hardcoded](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/pkg/app/reconcile_timer.go#L64)`30` wants to be read from some global-state store.  
 
 Off the top of my head I can't think of prior art for something like this, though maybe I'm forgetting something.   Where could we keep information that we can access from the ReconcileTimer (or maybe via its `.app`)?      ...  e.g. could we use `os.SetEnv` to write it at initialization time and then look it up when we're in the reconcile timer?      or could we add it to the [kcconfig](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/pkg/config/config.go#L31),  and if so how is that available from the ReconcileTimer?

**Comment by joe-kimmel-vmw** [comment]
TODO:  reach out to users (proactively reach out to internal users, TKG,  other users welcome to comment on this ticket). to see the personas of who is setting the config: 
https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/pkg/config/config.go#L38
vs. the deployment flags, 
to see if there's a more or less reasonable place to put these additional knobs.

**Comment by aaronshurley** [comment]
I had a brief chat with @shyaamsn about this and he expressed a preference for the ability to set these properties via [the config](https://carvel.dev/kapp-controller/docs/latest/controller-config/). The reasons being that it would align with how they currently configure things and it would be easier to track changes.

**Comment by aaronshurley** [comment]
To consolidate some updates on this issue:
- v0.26.0 changed the default sync periods to 10m from 30s ([release notes](https://github.com/vmware-tanzu/carvel-kapp-controller/releases/tag/v0.26.0)). So, the urgency for this issue has been reduced but it would still be helpful to expose this for users to customize.
- We would like to provide expose this configuration via [the config](https://carvel.dev/kapp-controller/docs/latest/controller-config/).
- The property names could still be ironed out, feel free to discuss this here or in Slack.

**Comment by cppforlife** [comment]
closing for now. will reopen if we need to provide more configurability to admins.
