### ISSUE TITLE
Include ./hack/gen.sh and ./hack/gen-apiserver.sh in ./hack/verify-no-dirty-files.sh or ./hack/build.sh

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#374]
As part of kapp-controller's CI process, a [script is run](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/8e1ab43ea190d32f11c0980202b303f762d7be4a/.github/workflows/test-gh.yml#L45) called [`./hack/verify-no-dirty-files.sh`](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/8e1ab43ea190d32f11c0980202b303f762d7be4a/hack/verify-no-dirty-files.sh). This script is used to determine if there are any unchecked in files as part of a pull request. 

In addition to making sure there is no git diff from [`./hack/build.sh`](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/8e1ab43ea190d32f11c0980202b303f762d7be4a/hack/build.sh), it would be beneficial to also add [`./hack/gen.sh`](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/8e1ab43ea190d32f11c0980202b303f762d7be4a/hack/gen.sh) and [`./hack/gen-apiserver.sh`](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/8e1ab43ea190d32f11c0980202b303f762d7be4a/hack/gen-apiserver.sh). These two scripts run kapp-controller's Kubernetes generators. 

In order to prevent code from being check in without running these generators, CI should fail and tell the user what scripts to run and to check in changes to the pull request.

Additional considerations:
* **NOTE**: For testing this locally, users should work on their GOPATH (i.e. $GOPATH/go/src/github.com/vmware-tanzu/kapp-controller. This is needed so the generators update code properly.
* protobuf may need to be installed on the Ubuntu image used in CI to support this. This usually manifests as the following error if not installed `protoc: command not found.`. For anyone testing locally, it will definitely need to be installed.
* Whether these generator scripts should be added to `./hack/build.sh` or elsewhere I think can be left up to whoever picks up this issue/discussed in the eventual pull request.

**Comment by cppforlife** [comment]
> Whether these generator scripts should be added to ./hack/build.sh or elsewhere I think can be left up to whoever picks up this issue/discussed in the eventual pull request.

./hack/build.sh is meant for a quick dev iteration. i would be opposed to adding it there.
