### ISSUE TITLE
Support apiextensions.k8s.io/v1 App CRD

### ISSUE THREAD

**Issue by jessehu** [carvel-dev/kapp-controller#38]
When using kubectl 1.19.1 to install kapp-controller in a Kubernetes v1.19.1 cluster, we got this warning:   `apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition.` Using kubectl 1.18.x doesn’t get the warning.

Shall we provide the apiextensions.k8s.io/v1 App CRD? Thanks.

Reference: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition

**Comment by pivotaljohn** [comment]
Also: https://vmware.slack.com/archives/CUK1X0Z8Q/p1606317265094900

**Comment by jessehu** [comment]
👍  Also: https://vmware.slack.com/archives/CUK1X0Z8Q/p1606317265094900 :
Dmitriy Kalinin:  5 hours ago
we have plans to switch to v1 CRD api and add schema for the CR fields which would catch this problem i believe.

**Comment by danielhelfand** [comment]
Making a note for this issue that we should update docs for users who install kapp-controller via kubectl instead of kapp. If upgrading to a version of kapp-controller with the updated crd versions, it may not delete old versions of the crds. We should document how to remove these old versions as part of the installation docs.

**Comment by danielhelfand** [comment]
> Making a note for this issue that we should update docs for users who install kapp-controller via kubectl instead of kapp. If upgrading to a version of kapp-controller with the updated crd versions, it may not delete old versions of the crds. We should document how to remove these old versions as part of the installation docs.

After further investigating, this does not appear to be an issue for kubectl users as the newer crds versions will simply replace the older versions.
