### ISSUE TITLE
Update tests to use testify/require instead of value comparisons and Fatal

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#393]

**Comment by krishnaindani** [comment]
could I work on this? Would you be able to assign to me?

**Comment by cppforlife** [comment]
@krishnaindani all yours, thanks for contributing!

**Comment by krishnaindani** [comment]
Thank you

**Comment by krishnaindani** [comment]
I am trying to run tests locally, do I need to set up some proxy server. I am not able to find the instructions to run the tests. Would you guide me here?

**Comment by cppforlife** [comment]
here is some docs about it: https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/docs/dev.md. running unit tests (./hack/test.sh) should not require any dependencies. running e2e tests (./hack/test-e2e.sh) requires a kubernetes cluster (we typically use minikube) and secret gen controller (covered by ./hack/deploy-test.sh).

**Comment by krishnaindani** [comment]
Thank you, I will go through

**Comment by Stuie** [comment]
Hey, I was taking a look at this out of interest, is [this](https://github.com/Stuie/carvel-kapp-controller/commit/7e5b79fe6c95db7804223aaccc227cbb96bca932) the sort of thing you're looking for? Would you be expecting all test cases to be updated?

**Comment by cppforlife** [comment]
@Stuie yup.

> Would you be expecting all test cases to be updated?

thats the goal, but we can do updates in smaller chunks -- PR for a package/group-of-packages is totally fine.

not sure if @krishnaindani is still working on it though...
