### ISSUE TITLE
kapp-controller should allow configuration of metrics service port

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#394]
**Describe the problem/challenge you have**
if kapp-controller is run with hostNetwork=true on the Deployment, default metrics service port 8080 may conflict with other services running on the node. need to determine whats the best configuration -- should port be some high numbered port? should it be configurable via flag?

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joe-kimmel-vmw** [comment]
should we put this config in the same place as the other config we've been discussing? 
https://github.com/vmware-tanzu/carvel-kapp-controller/issues/373

**Comment by cppforlife** [comment]
this particular one im not so sure. i think this might be a lower level type of config... not sure.

**Comment by danielhelfand** [comment]
> lower level type of config

Can we add some details in here on what we are thinking about with regards to a `lower level type of config`?

**Comment by cppforlife** [comment]
> should it be configurable via flag?

that's the lower level config im talking about.

**Comment by danielhelfand** [comment]
Leaving some notes here on implementation details.

The metrics service port can be configured here: https://github.com/vmware-tanzu/carvel-kapp-controller/blob/69c59a6e0d9007213ecddd8b8d934c3e47f822f9/cmd/controller/run.go#L56

It can be set using the `MetricsBindAddress`:  
```go
property: mgr, err := manager.New(restConfig, manager.Options{Namespace: opts.Namespace, 
    Scheme: kcconfig.Scheme, MetricsBindAddress: "8080"})
```

Flags for kapp-controller can be found here: https://github.com/vmware-tanzu/carvel-kapp-controller/blob/69c59a6e0d9007213ecddd8b8d934c3e47f822f9/cmd/main.go#L25
