### ISSUE TITLE
Remove helm v2 support

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#396]
**Describe the problem/challenge you have**

kapp-controller currently supports helm 2, which has been deprecated for close to a year now: https://helm.sh/blog/helm-v2-deprecation-timeline/

kapp-controller did add support for helm 3 in #158, but we chose to not immediately drop support for helm 2 as v2 to v3 aren't 1 to 1 matches.

**Describe the solution you'd like**

We should drop maintaining helm v2 support. This will have no consequences as far as API changes, but it will require the removal of the helm v2 binary and minor changes like shown below:
* https://github.com/vmware-tanzu/carvel-kapp-controller/blob/9481171be83cf55c91271b1d146b772259c54e8f/Dockerfile#L32
* https://github.com/vmware-tanzu/carvel-kapp-controller/blob/9481171be83cf55c91271b1d146b772259c54e8f/pkg/template/helm_template.go#L64
* https://github.com/vmware-tanzu/carvel-kapp-controller/blob/9481171be83cf55c91271b1d146b772259c54e8f/pkg/template/helm_template.go#L115

Additionally, tests will need to be removed for v2: 
* https://github.com/vmware-tanzu/carvel-kapp-controller/blob/9481171be83cf55c91271b1d146b772259c54e8f/pkg/template/helm_template_test.go
* https://github.com/vmware-tanzu/carvel-kapp-controller/blob/9481171be83cf55c91271b1d146b772259c54e8f/test/e2e/kappcontroller/helm_test.go

**Anything else you would like to add:**

We should consider how to announce this to the community and what breaking change process for kapp-controller should be moving forward. As of now, we have little definition around breaking changes, and this might be a simple enough issue to help form some practices around this process.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
Accepting this for now. It's not clear when the right time will be to officially remove support, but we will follow up here when we have a clearer timeline.

**Comment by nicholasmhughes** [comment]
I think now is probably the time to remove support for Helm v2 since since it's been [over a year since the code freeze](https://helm.sh/blog/helm-v2-deprecation-timeline/). I've run across some charts that still have `apiVersion: 1` set, but are incompatible with Helm 2... which creates problems for kapp-controller. The latest occurrence I found was with Rancher, documented in this PR: https://github.com/rancher/rancher/pull/36838

**Comment by cppforlife** [comment]
agreed.

**Comment by joe-kimmel-vmw** [comment]
fixed in https://github.com/vmware-tanzu/carvel-kapp-controller/pull/590.
