### ISSUE TITLE
Packaging API: Just ignore the v at the beginning of invalid versions

### ISSUE THREAD

**Issue by voor** [carvel-dev/kapp-controller#408]
**Describe the problem/challenge you have**
When creating a package and letting `v` slip into the Package `spec.version` you get an error message:
```
        Invalid value: "v0.15.4": must be valid semver:
          Invalid character(s) found in major number "v0" (reason: Invalid)
```

**Describe the solution you'd like**
Just ignore the v at the begnning of the versioning, that's what [vendir](https://carvel.dev/vendir/docs/latest/versions/#sort-semver-command) does, so the experience becomes inconsistent across Carvel.

**Anything else you would like to add:**
I am passing the GitHub tag directly down to the Package through vendir using ytt with the kbld `BundleLock` as a `--data-values-file` 

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by voor** [comment]
We're remediating this for now with `lstrip`

https://carvel.dev/ytt/#gist:https://gist.github.com/voor/0439c6d4c504959a9f0cafc08e749044

**Comment by cppforlife** [comment]
challenge with allowing more flexibility here is that suddently you could have 2 package crs: one with name foo.pkg.com.0.0.1 and another with foo.pkg.com.v0.0.1. this leads to ambiguity and possible mistakes down the line.

im -1 on allowing this.
