### ISSUE TITLE
[fetch] support custom ca cert for git repo

### ISSUE THREAD

**Issue by poblin-orange** [carvel-dev/kapp-controller#42]
Using kapp-controller in coroporate on premise environement requires to be able to set corporate ca cert on git configuration

**Comment by cari-lynn** [comment]
Hey @poblin-orange, thanks for opening this issue.

How do you expect the git properties under fetch to change to support this?

Would you be able to provide a description of your specific use case?

**Comment by poblin-orange** [comment]
hello @pivotal-dean 
in my context, the git repo to access is in intranet/on premise, with a corporte https certificate (CA is orange specific, not public CA). To fix, i had to add volume / volume mount to the deployment (targeting /etc/ssl/certificate to put our corporate ca cert file, i dont think it can be done from git properties ? )

**Comment by cppforlife** [comment]
> i dont think it can be done from git properties

that's right. and btw are you ok with trusting that CA for all Apps?

**Comment by poblin-orange** [comment]
In a corporate env, its ok for us. Problem is if we had a mix of public repo / private repos.

**Comment by cppforlife** [comment]
available in https://github.com/vmware-tanzu/carvel-kapp-controller/releases/tag/v0.14.0
