### ISSUE TITLE
[Docs] How to use the package management APIs with GitOps workflow

### ISSUE THREAD

**Issue by aaronshurley** [carvel-dev/kapp-controller#445]
**Describe the problem/challenge you have**
We have heard from several Carvel (and TAP) users that they would like to be able to manage their TAP installation using GitOps practices. In addition, we (Carvel) also want to encourage our users to manage their Packages using GitOps practices. Being able to do this using declarative APIs and without needing additional tooling is an advantage of using Carvel. Our docs don't call this out explicitly today and we don't have any guides/content to help users set it up. If we can add docs around this, then these docs can be referenced from TAP docs.

**Describe the solution you'd like**
When I navigate to [kapp-controller's docs](https://carvel.dev/kapp-controller/docs/latest/), I can find a link to a guide that demonstrates how to use the Package Management APIs in a GitOps workflow.

**Anything else you would like to add:**
Feel free to reach out to users to discover some of the best practices folks have developed.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help work on this issue.

**Comment by danielhelfand** [comment]
Here's some notes on the GitOps approach we are going to document for this issue: 

> Package consumers are provided a package repository URL. Consumers create a PackageRepository CR pointing to that URL. They also create several PackageInstall CRs describing which package/version to install. They commit these yaml files (PackageRepository and PackageInstalls) in a Git repo and tell kapp-controller to install these yaml files on the cluster (via App CR).

Basically, an App CR will be pointed at a git repository containing the PackageRepository/PackageInstalls. The App CR will then reconcile the updates regularly based on the App's syncPeriod.

A user can then update versions or add additional PackageInstalls by opening a pull request and merging the pr into the main branch of the repository. Additionally, a consumer can update the version of the imgpkgBundle for the PackageRepository in the git repository to make new versions of Packages available.
