### ISSUE TITLE
TestHelm is Failing Since Redis Chart is Unavailable 

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#46]
As discovered in #45, [`TestHelm`](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/c36ee5e96e742c53395a92cebbc144fea8f999de/test/e2e/helm_test.go) is failing. Logs from GitHub actions are shown [here](https://github.com/vmware-tanzu/carvel-kapp-controller/runs/1408252458).

This is related to [Helm 2 no longer being supported](https://helm.sh/blog/helm-2-becomes-unsupported/). The test should be updated to account for [stable/redis](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/c36ee5e96e742c53395a92cebbc144fea8f999de/test/e2e/helm_test.go#L35) no longer being available.

**Comment by cppforlife** [comment]
fixed in https://github.com/vmware-tanzu/carvel-kapp-controller/commit/9dbb595888d5c5aa992b17151114d10a17c91ae7

**Comment by danielhelfand** [comment]
Verified in [CI logs](https://github.com/vmware-tanzu/carvel-kapp-controller/runs/1431845962) that test is now passing.
