### ISSUE TITLE
Support the docker registry repo with self-signed certificate

### ISSUE THREAD

**Issue by jessehu** [carvel-dev/kapp-controller#47]
1. When executing 'imgpkg' on a local machine, we can add the self-signed CA certificate on the local machine to fix it.
2. When executing 'imgpkg' in a container (e.g. kapp-controller), does it work? If not, we might need to add an option in App CR (around fetch.image.url) for specifying CA cert.

This is simliar to https://github.com/vmware-tanzu/carvel-kapp-controller/issues/42

**Comment by cppforlife** [comment]
dup of #39. closing, but moving your comment there.
