### ISSUE TITLE
Update module name to reflect new repository

### ISSUE THREAD

**Issue by bryanl** [carvel-dev/kapp-controller#48]
With the project being moved to a new location, I don't believe you will be able to do a `go get github.com/vmware-tanzu/carvel-kapp-controller`. It'll fail because the module declared in go.mod is `github.com/k14s/kapp-controller`. In the short term, folks can still do a `go get github.com/k14s/kapp-controller`. Perhaps this could be highlighted in the readme.

**Comment by cppforlife** [comment]
👍 we are planning to update imports shortly for moved repos.

**Comment by pivotaljohn** [comment]
Being worked through: https://www.pivotaltracker.com/story/show/175767212

**Comment by cppforlife** [comment]
kapp-controller go module renamed in https://github.com/vmware-tanzu/carvel-kapp-controller/commit/9abbd5de22aee30cdd6544e89ce648089d09516c some time ago.
