### ISSUE TITLE
Support k8s version compatibility

### ISSUE THREAD

**Issue by pk89** [carvel-dev/kapp-controller#484]
**Describe the problem/challenge you have**
We would like a way to check if upgrading a kubernetes cluster would render some of the installed packages incompatible. When building tooling on top of Carvel, it would also be nice to prevent users from attempting to install the Carvel packages on incompatible kubernetes clusters.

**Describe the solution you'd like**
Standardize a format for package authors to specify k8s version compatibility range in the PackageMetadata, for tooling on top of it to parse.  

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
Thanks again for opening this @pk89.

I wanted to add in some notes on some considerations for this issue:

1. The idea of checking if a package can be installed on a cluster of a particular version becomes interesting when a Package is compatible on any k8s version, but may need conditional changes based on the k8s version. An example may be a [fluent-bit package](https://docs.fluentbit.io/manual/installation/kubernetes#note-for-kubernetes-less-than-v1.16), which relies on the DaemonSet resource that changed its apiVersion in 1.16. 

We should think about supporting this case with this issue. Some previous ideas have been the ability to template underlying package based on information available at install time.

2. How will we think about handling versions for various Kubernetes distributions that may not align perfectly with underlying k8s version?

Additional notes:

Another known piece of software that has been added as a Package is Tekton, which relies on [k8s 1.19 or greater](https://tekton.dev/docs/pipelines/install/#before-you-begin). It might be helpful in guiding some ideas around preflight checks to prevent the installation of a package on an incompatible version.

**Comment by joe-kimmel-vmw** [comment]
see design proposal: https://hackmd.io/6FQhzRIPR_uceqtTqSIXaA

**Comment by joe-kimmel-vmw** [comment]
we will likely solve this alongside #577
