### ISSUE TITLE
Make `kubectl explain` work with kapp-controller CRDs

### ISSUE THREAD

**Issue by alexbrand** [carvel-dev/kapp-controller#49]
The `kubectl explain` command is a great way to get documentation about resources.

Currently, the App CRD does not provide documentation via `kubectl explain`:

```
$ kubectl explain app.spec
KIND:     App
VERSION:  kappctrl.k14s.io/v1alpha1

DESCRIPTION:
     <empty>
```

**Comment by danielhelfand** [comment]
Thanks for opening this @alexbrand. I think it makes sense to provide descriptions for our CRDs. 

I haven't fully looked into it yet, but we can look into how [knative eventing approached the problem](https://github.com/knative/eventing/issues/3054) for more consideration into it.

**Comment by cppforlife** [comment]
yeah, should be able to do that with bump to CRD v1 (https://github.com/vmware-tanzu/carvel-kapp-controller/issues/38) and addition of openapiv3schema field.

**Comment by cirocosta** [comment]
also, [`controller-gen crd`](https://github.com/kubernetes-sigs/controller-tools) now supports `v1`, so that could be all auto generated

**Comment by danielhelfand** [comment]
This should now be available with our upgrade to CRD v1. With regard to the example above (`kubectl explain app.spec`), it would be nice for us to add description comments for each field and regenerate the CRD schemas using the `./hack/gen-crds.sh`. Currently, we have limited comments for fields:

```
$ k explain app.spec    
KIND:     App
VERSION:  kappctrl.k14s.io/v1alpha1

RESOURCE: spec <Object>

DESCRIPTION:
     <empty>

FIELDS:
   canceled     <boolean>
     Canceled when set to true will stop all active changes

   cluster      <Object>

   deploy       <[]Object>

   fetch        <[]Object>

   noopDelete   <boolean>
     When NoopDeletion set to true, App deletion should delete App CR but
     preserve App's associated resources

   paused       <boolean>
     Paused when set to true will ignore all pending changes, once it set back
     to false, pending changes will be applied

   serviceAccountName   <string>

   syncPeriod   <string>
     Controls frequency of app reconciliation

   template     <[]Object>

```

We do have descriptive comments on our website for each CR that could be added above each field in the source:
* https://carvel.dev/kapp-controller/docs/latest/app-spec/ 
* https://carvel.dev/kapp-controller/docs/latest/packaging/

This way descriptions will show up with each field using kubectl explain.

**Comment by aaronshurley** [comment]
Moving this to the unprioritized-backlog for now but we'll accept contributions for this.

**Comment by cppforlife** [comment]
confirmed that this has been resolved (probably in 0.20.0)

**Comment by danielhelfand** [comment]
I am going to reopen this as we still want to track work mentioned in [comment above](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/49#issuecomment-890043648). Part of this issue is that there are also not a lot of field descriptions for our CRs through kubectl explain.

**Comment by danielhelfand** [comment]
This is still relevant and is ready to be picked up.

**Comment by aaronshurley** [comment]
Removed the `carvel-triage` label to prevent the GH actions bot from adding the `stale` label.
