### ISSUE TITLE
cue as a templating option

### ISSUE THREAD

**Issue by aaronshurley** [carvel-dev/kapp-controller#514]
**Describe the problem/challenge you have**
We've been hearing some excitement about [cue](https://cuelang.org/). It'd be a great opportunity to increase kapp-controller's extensibility by enabling cue as a templating option.

**Describe the solution you'd like**
cue works with kapp-controller.

**Anything else you would like to add:**
This is not a prescriptive issue. Feel free to work out the details in Slack.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by benmoss** [comment]
One problem I'm running into is that cue is not exactly a templating tool. In the Kubernetes examples, they show for instance [how you would create a custom tool](https://github.com/cue-lang/cue/blob/v0.4.2/doc/tutorial/kubernetes/README.md#dumping-a-yaml-stream) (in Cue terms) to export a multi-document YAML stream.

We could expose something like 

```yaml
template:
  cue:
    command: "dump"
```

but not sure that giving users control over the command invoked is what we want to expose as an API.
