### ISSUE TITLE
Add more metrics to the metrics we expose

### ISSUE THREAD

**Issue by joe-kimmel-vmw** [carvel-dev/kapp-controller#517]
**Describe the problem/challenge you have**
As a package author who is frequently installing new packages to test the packages I am writing, I want to see when I've added so many "problem" packages that the performance of kapp-controller is degraded.

**Describe the solution you'd like**
We expose[ some metrics](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/pkg/metrics/app_metrics.go) but what if we had more? 

Particularly the request is around:
> mainly reconciliation metrics, specially the  reconciliation times and success rate which hints us when there might be throughput issues. The reconciliation queue is also another one we pay attention to. Number of reconciliations per minute, failed, successful, those are useful too.
**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by benmoss** [comment]
Maybe we should investigate how users can emit/consume Kubernetes events instead of adding more metrics
