### ISSUE TITLE
Investigate whether subprocesses can be run as less-privileged users

### ISSUE THREAD

**Issue by benmoss** [carvel-dev/kapp-controller#518]
We launch a bunch of subprocesses for running ytt, kapp, etc, should these be run as less-privileged users than the default kapp-controller user?

**Comment by neil-hickey** [comment]
We do most if not all of the less secure work (third party / external tools for fetching, templating etc) in a sidecar now:

https://github.com/vmware-tanzu/carvel-kapp-controller/pull/775

I think this goes some way towards a less privileged user request. The sidecar is something we are going to improve on, so I'm going to close out this issue
