### ISSUE TITLE
**Explore:** From commandline, provide ability to capture output and wait for a reconciliation that is in progress

### ISSUE THREAD

**Issue by doddatpivotal** [carvel-dev/kapp-controller#56]
When kapp-controller is reconciling, I want the ability to issue a command that will allow me to track the progress of the reconciliation as if I did the deployment myself.

Essentially I want to stream the progress in a similar way that I get with `kapp deploy...`

Output would stream the progress of the reconciliation until complete.

**Comment by ewrenn8** [comment]
Hey @doddatpivotal, thanks for the request!

Do you imagine this command is something that gets added to kapp?

**Comment by doddatpivotal** [comment]
@ewrenn8 either kapp or a kapp-controller specific cli

**Comment by aaronshurley** [comment]
Adding `Explore` to this issue to further define/propose a solution.

Some things to explore:
- events API
- client-side vs server-side considerations
- whether this should live in kapp itself?

Blocking this on #110.

**Comment by cppforlife** [comment]
(being covered by kctrl -- https://github.com/vmware-tanzu/carvel-kapp-controller/issues/412)
