### ISSUE TITLE
package should be able to specify acceptable kapp-controller and k8s version required

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#577]
**Describe the problem/challenge you have**
[A description of the current challenge that you are experiencing.]

package authors want ability to specify that particular package can only be installed on kapp-controllers version X and above. example case: im using particular new ytt feature that it's only available in kc v0.45.0+ and want to prevent somebody from trying to install it on kapp-controller v0.43.0 because it will fail or do something terrible.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen. If applicable a visual representation of the UX.]

we do have some prior art in other carvel tools (vendir, kbld, kapp, ytt) e.g. https://github.com/vmware-tanzu/carvel-vendir/blob/develop/pkg/vendir/config/config.go#L25

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

questions/related areas:
- should we introduce max version as well?
- is this a App CR feature as well?
- similar topic: min/max kubernetes version for a package

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by jorgemoralespou** [comment]
While this, as I see it, is metadata that will need to be defined in the Package, it would be awesome to look at other issues that would provide similar/related functionality (e.g. https://github.com/vmware-tanzu/carvel-kapp-controller/issues/201)

**Comment by neil-hickey** [comment]
Some questions from our triage meeting:

1. Do we allow ranges? e.g `v1.0.0 - v1.2.0`
2. Should this be a top-level field on the [PackageCR](https://carvel.dev/kapp-controller/docs/v0.34.0/packaging /#package) or an annotation?

**Comment by cppforlife** [comment]
> it would be awesome to look at other issues that would provide similar/related functionality

both features would be nice :)

> Do we allow ranges? e.g v1.0.0 - v1.2.0

i dont think we need to get too fancy. by providing both min and max checks (optionally provided) that allows to define one range. i havent seen much use for multiple ranges.

**Comment by joe-kimmel-vmw** [comment]
see design proposal here: https://hackmd.io/6FQhzRIPR_uceqtTqSIXaA
