### ISSUE TITLE
Expected to find at least one version (details: all=0 -> after-prereleases-filter=0 -> after-constraints-filter=0)))**

### ISSUE THREAD

**Issue by ramkrishna2k3** [carvel-dev/kapp-controller#581]
**What steps did you take:**
As per the customer requirement we needed to remove **helm.sh/chart: tomcat-10.1.12** from the yaml file.

**What happened:**
got an error:
**kapp: Error: waiting on reconcile packageinstall/tomcatapp-demo (packaging.carvel.dev/v1alpha1) namespace: default:
  Finished unsuccessfully (Reconcile failed:  (message: Expected to find at least one version, but did not (details: all=0 -> after-prereleases-filter=0 -> after-constraints-filter=0)))**

**What did you expect:**
Reconcile succeed

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- kapp version (use `kapp --version`):  kapp version 0.46.0
- OS (e.g. from `/etc/os-release`): NAME="Ubuntu"
                                                     VERSION="20.04.4 LTS (Focal Fossa)"
- Kubernetes version (use `kubectl version`)
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", 

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by 100mik** [comment]
It looks like this issue belongs to the `kapp-controller` repo.
Looks like you were trying to wrap a helm chart in a package.
Could you elaborate on the issue?

**Comment by renuy** [comment]
@ramkrishna2k3 , this looks a kapp-controller issue to transferred it to the kapp-controller repo.

**Comment by ramkrishna2k3** [comment]
> It looks like this issue belongs to the `kapp-controller` repo. Looks like you were trying to wrap a helm chart in a package. Could you elaborate on the issue?

[config.yml.txt](https://github.com/vmware-tanzu/carvel-kapp-controller/files/8303305/config.yml.txt)
[pkginstall.yml.txt](https://github.com/vmware-tanzu/carvel-kapp-controller/files/8303306/pkginstall.yml.txt)
[values.yml.txt](https://github.com/vmware-tanzu/carvel-kapp-controller/files/8303307/values.yml.txt)

**Comment by ramkrishna2k3** [comment]
any help in this regard

**Comment by ramkrishna2k3** [comment]
root@Master-VM:~/tomcat# kubectl describe packageinstall.packaging.carvel.dev/tomcat-demo

Status:
  Conditions:
    Message:             Expected to find at least one version, but did not (details: all=0 -> after-prereleases-filter=0 -> after-constraints-filter=0)
    Status:              True
    Type:                ReconcileFailed
  Friendly Description:  Reconcile failed: Expected to find at least one version, but did not (details: a...
  Observed Generation:   1
Events:                  <none>
root@Master-VM:~/tomcat#

**Comment by ramkrishna2k3** [comment]
> It looks like this issue belongs to the `kapp-controller` repo. Looks like you were trying to wrap a helm chart in a package. Could you elaborate on the issue?

Yes, we are using helm bitnami chart and creating a package. can u please help in this.

**Comment by cppforlife** [comment]
helping over slack. closing here.

**Comment by benjaminapetersen** [comment]
Was there ever clarification about what this means?  I've seen the same as well.

**Comment by joe-kimmel-vmw** [comment]
Hi @benjaminapetersen  -  the gist of the error message is "you have created a PackageInstall resource, but there is not an appropriate corresponding Package resource."

  I think if you're getting this I would check things like `kubectl get packages -A`,  and also check the namespace that your PackageInstall is targeting to see if the package is available from that namespace.  Check the versions of the package vs. any version constraints specified by the PackageInstall,   etc.

**Comment by benjaminapetersen** [comment]
Perfect, thats crystal clear, and lines up with what I eventually realized as well. Thanks!
