### ISSUE TITLE
kctrl should provide autocomplete capabilities

### ISSUE THREAD

**Issue by jorgemoralespou** [carvel-dev/kapp-controller#586]
**Describe the problem/challenge you have**
Sometimes, typing a kctrl command is too long, and requires the user to go back and forth to other terminal to see the appropriate package or version. It would be awesome if kctrl could provide autocomplete capabilities like other tools (e.g. kubectl) where it even inspects the cluster on autocompletion so that a `tab` keystroke would help the user to find package-names, package-versions and even commands.

**Describe the solution you'd like**
Add autocompletion capabilities

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment]
@jorgemoralespou Thank you so much for the suggestion.
