### ISSUE TITLE
Incomplete help for "kctrl package available get" command.

### ISSUE THREAD

**Issue by GrahamDumpleton** [carvel-dev/kapp-controller#604]
**What steps did you take:**

Run:

```
kctrl package available get --help
```

This outputs:

```
Get details for an available package or the openAPI schema of a package with a specific version

Usage:
  kctrl package available get [flags]

Aliases:
  get, g

Examples:
# Get details about an available package 
kctrl package available get -p cert-manager.community.tanzu.vmware.com

# Get the values schema for a particular version of the package 
kctrl package available get -p cert-manager.community.tanzu.vmware.com --values-schema

Flags:
  -h, --help               help for get
  -n, --namespace string   Specified namespace ($KCTRL_NAMESPACE or default from kubeconfig)
  -p, --package string     Set package name (required)
      --values-schema      Values schema of the package (optional)

Global Flags:
      --color                       Set color output (default true)
      --column strings              Filter to show only given columns
      --debug                       Include debug output
      --json                        Output as JSON
      --kube-api-burst int          Set Kubernetes API client burst limit (default 1000)
      --kube-api-qps float32        Set Kubernetes API client QPS limit (default 1000)
      --kubeconfig string           Path to the kubeconfig file ($KCTRL_KUBECONFIG)
      --kubeconfig-context string   Kubeconfig context override ($KCTRL_KUBECONFIG_CONTEXT)
      --kubeconfig-yaml string      Kubeconfig contents as YAML ($KCTRL_KUBECONFIG_YAML)
      --tty                         Force TTY-like output (default true)
  -y, --yes                         Assume yes for any prompt

Succeeded
```

Following example given, eg.:

```
kctrl package available get -p cert-manager.community.tanzu.vmware.com --values-schema
```

Replace `cert-manager.community.tanzu.vmware.com` with some package name you do have available.

**What happened:**

The command above gives an error of:

```
Target cluster 'https://127.0.0.1:59117' (nodes: xxx)

kctrl: Error: Package version is required when --values-schema flag is declared
```

**What did you expect:**

The help string does say `package with a specific version`, but nowhere in the help string does it give an example of how to say what version you want the information for, nor is there an obvious command line option to pass the version. There is no ``--version`` option like other commands when doing an install of a package.

I would expect the help string to show how you specify the version.

**Anything else you would like to add:**

Note that all I have in the cluster is a `Package` and `PackageMetadata` resource. There are no package repositories etc. I have no idea if this affects anything.

**Environment:**

```
% kctrl version
kctrl version 0.34.0
```

```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-03-06T21:32:53Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

cc @jorgemoralespou

**Comment by praveenrewar** [comment]
`value-schema` needs version of the package, `kctrl package available get -p cert-manager.community.tanzu.vmware.com/1.0.0 --values-schema` should work. The example needs to be updated. 

Also, another concern is that if we should use `--version` flag like the installed command.
