### ISSUE TITLE
Custom resources should never be added to the Kubernetes "all" alias.

### ISSUE THREAD

**Issue by GrahamDumpleton** [carvel-dev/kapp-controller#605]
**What steps did you take:**

Operate against a Kubernetes cluster using a service account/user which has restrictive RBAC.

Run:

```
kubectl get all
```

**What happened:**

You get errors of:

```
Error from server (Forbidden): apps.kappctrl.k14s.io is forbidden: User "system:serviceaccount:lab-k8s-fundamentals-w01:lab-k8s-fundamentals-w01-s001" cannot list resource "apps" in API group "kappctrl.k14s.io" in the namespace "lab-k8s-fundamentals-w01-s001"
Error from server (Forbidden): packagerepositories.packaging.carvel.dev is forbidden: User "system:serviceaccount:lab-k8s-fundamentals-w01:lab-k8s-fundamentals-w01-s001" cannot list resource "packagerepositories" in API group "packaging.carvel.dev" in the namespace "lab-k8s-fundamentals-w01-s001"
Error from server (Forbidden): packageinstalls.packaging.carvel.dev is forbidden: User "system:serviceaccount:lab-k8s-fundamentals-w01:lab-k8s-fundamentals-w01-s001" cannot list resource "packageinstalls" in API group "packaging.carvel.dev" in the namespace "lab-k8s-fundamentals-w01-s001"
```

**What did you expect:**

It is generally regarded as bad practice to add additional Kubernetes resources to the `all` alias. The `all` alias is more or less reserved for Kubernetes core resources only and custom resources should never be added to the `all` alias. As a result, `kapp-controller` package should not be adding its custom resources to the `all` alias. By doing so you get errors like the above, which can in some cases throw out scripted automation and in general create excessive noise in the output of `kubectl` which can annoy users greatly.

**Anything else you would like to add:**

It can't be over emphasised that adding extra resources to the `all` alias is very bad practice. Other Tanzu/VMware products have done this in the past but they have since removed them because of it being bad practice.

**Environment:**

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-03-06T21:32:53Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

cc @jorgemoralespou

**Comment by neil-hickey** [comment]
Thanks for that background @GrahamDumpleton ! This seems like a potential breaking change for anyone relying on that behaviour today.

@cppforlife any background on why this was added? If there's no compelling reason to have this information shown in `kubectl all` then this story is available for pickup and probably a small change.

**Comment by cppforlife** [comment]
was added in this https://github.com/vmware-tanzu/carvel-kapp-controller/pull/483. i dont have strong preference either way.

**Comment by benmoss** [comment]
@GrahamDumpleton I added this, I'm sorry if it is causing you trouble. I don't think it's necessarily common knowledge or widely accepted that custom resources should never be added to the "all" category, here are two examples:

https://github.com/knative/serving/blob/e73e83bcfd7acba1c16193963a49649f7445a6ab/config/core/300-resources/service.yaml#L34
https://github.com/rabbitmq/cluster-operator/blob/3d1c94e1ceedeabc44f1ac1fd1c92d86303263f7/config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml#L20

That said I think I understand how this could cause users problems, it's kind of unfortunate that categories work this way.

**Comment by GrahamDumpleton** [comment]
Did knative people add it back again!

Pretty sure I had this discussion with them a few years ago and they saw the wisdom in removing their CRDs from `all`. Seems people never learn this is a bad idea. :-(

The underlying problem is people assume that everyone works as cluster admin against the cluster when that isn't the case. They therefore think doing this is a convenience for everyone when it isn't.

**Comment by GrahamDumpleton** [comment]
What is annoying is that `kubectl` has an option:

```
--ignore-not-found=false: If the requested object does not exist the command will return exit code 0.
```

to not complain when a resource doesn't exist, but no option for don't yell and complain when RBAC prevents access to the resources which are named directly or via an alias. If it had such an option and one could also somehow set an environment variable so was applied all the time, one could suppress these noisy messages.
