### ISSUE TITLE
Huge amount of retries in case of failures

### ISSUE THREAD

**Issue by achimweigel** [carvel-dev/kapp-controller#61]
**Describe the problem/challenge you have**
Assume we define an App CR to deploy some artefacts on some target cluster. If the deployment fails, e.g. if the target cluster is hibernated and not reachable, the deployment is retried every few seconds without any deceleration. This results in a flood of retries if there are more than one such App CR.

**Describe the solution you'd like**
Perhaps it would be a good idea to slow down the retries perhaps using the standard strategy of the controller framework. Not sure if this should be configurable?

**Comment by ewrenn8** [comment]
Added an exponential backoff with a ceiling equal to app sync period here d74a210231f94922497da67655fc13a1668ca84e

**Comment by cppforlife** [comment]
shipped in v0.15.0
