### ISSUE TITLE
Kicking an installed package should show fetch and deploy logs

### ISSUE THREAD

**Issue by voor** [carvel-dev/kapp-controller#661]
**Describe the problem/challenge you have**
I am rapidly falling in love with kick in its many forms.  When I have an installed package and I kick it, I usually do this:

```
kctrl package installed kick -n common-install -i external-dns -y
kctrl app kick -n common-install -a external-dns -y
```

I would really like to be able to just do this:

```
kctrl package installed kick -n common-install -i external-dns -y --SOMETHING
```

And combine these into one command.

**Describe the solution you'd like**
Add a new `--follow` or `--recurse` or you come up with a better name, 

**Anything else you would like to add:**
Please name the parameter something that makes sense and don't feel like my suggestions are part of the feature request.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment]
@voor Any specific reason you would want to kick the underlying app CR as well? 
(As kicking the package install would technically kick the underlying app CR)

**Comment by voor** [comment]
I am interested in seeing the fetch and deploy outputs, that's not shown when I kick the pkg.

**Comment by praveenrewar** [comment]
Ideally you should be able to see deploy outputs while kicking the package install, but I think that there are still some edge cases that needs to be covered. (cc @100mik)
Would you be able to share the output that you are seeing when kicking package install?

**Comment by voor** [comment]
```
$ kctrl package installed kick -n common-install -i external-dns -y
Target cluster 'https://rv2-tap-apiserver-xxxx.us-gov-east-1.elb.amazonaws.com:6443' (nodes: ip-10-0-19-154.us-gov-east-1.compute.internal, 7+)

Triggering reconciliation for package install 'external-dns' in namespace 'common-install'

12:21:30PM: Waiting for PackageInstall reconciliation for 'external-dns'
12:21:31PM: Waiting for generation 4 to be observed 
12:20:23PM: App reconciled (1m ago)

Succeeded
```

**Comment by voor** [comment]
I would expect to see this:
```
kctrl app kick -a external-dns -n common-install -y                                                                                                                         
Target cluster 'https://rv2-tap-apiserver-xxxxx.us-gov-east-1.elb.amazonaws.com:6443' (nodes: ip-10-0-19-154.us-gov-east-1.compute.internal, 7+)

App 'external-dns' is owned by 'PackageInstall/external-dns'
Triggering reconciliation for app 'external-dns' in namespace 'common-install'12:22:52PM: Triggering reconciliation for app 'external-dns' in namespace 'common-install'
12:22:52PM: Waiting for app reconciliation for 'external-dns'
12:22:53PM: Fetching 
	    | apiVersion: vendir.k14s.io/v1alpha1
	    | directories:
	    | - contents:
	    |   - imgpkgBundle:
	    |       image: example.com/image:latest
	    |     path: .
	    |   path: "0"
	    | kind: LockConfig
	    | 
12:22:53PM: Fetch succeeded 
12:22:53PM: Template succeeded 
12:22:53PM: Deploy started (2s ago)
12:22:55PM: Deploying 
	    | Target cluster 'https://10.96.0.1:443' (nodes: ip-10-0-19-154.us-gov-east-1.compute.internal, 7+)
	    | Changes
	    | Namespace  Name  Kind  Conds.  Age  Op  Op st.  Wait to  Rs  Ri
	    | Op:      0 create, 0 delete, 0 update, 0 noop, 0 exists
	    | Wait to: 0 reconcile, 0 delete, 0 noop
	    | Succeeded
12:22:57PM: App reconciled 

Succeeded
```

**Comment by 100mik** [comment]
(GitHub mobile is not fun, let's mark this comment stale) 

Ideally, kicking the PackageInstall and the underlying App will yield the exact same output. 
Is the "kick" exiting without tailing the App? 
As Praveen said sharing the output might help us out! 

(Kicking the installation, also triggers a reconciliation of the underlying app, and we tail that output)

**Comment by praveenrewar** [comment]
I am also seeing some inconsistencies while kicking a package install. Sometimes it's showing the status and sometimes it's not)
`Try 1`
```bash
kctrl package installed kick -i test                                  
Target cluster 'https://192.168.64.89:8443' (nodes: minikube)

Triggering reconciliation for package install 'test' in namespace 'default'

Continue? [yN]: y

10:42:03PM: Waiting for PackageInstall reconciliation for 'test'

Succeeded
```

`Try 2`
```bash
kctrl package installed kick -i test -y                                
Target cluster 'https://192.168.64.89:8443' (nodes: minikube)

Triggering reconciliation for package install 'test' in namespace 'default'

10:51:50PM: Waiting for PackageInstall reconciliation for 'test'
10:51:50PM: Waiting for generation 13 to be observed
10:51:58PM: Fetching
	    | apiVersion: vendir.k14s.io/v1alpha1
	    | directories:
	    | - contents:
	    |   - imgpkgBundle:
	    |       image: index.docker.io/k8slt/kctrl-example-pkg@sha256:8ffa7f9352149dba1d539d0006b38eda357917edcdd39b82497a61dab2c27b75
	    |     path: .
	    |   path: "0"
	    | kind: LockConfig
	    |
10:51:58PM: Fetch succeeded
10:51:58PM: Template succeeded
10:51:58PM: Deploy started
10:51:59PM: Deploying
	    | Target cluster 'https://10.96.0.1:443' (nodes: minikube)
	    | Changes
	    | Namespace  Name  Kind  Conds.  Age  Op  Op st.  Wait to  Rs  Ri
	    | Op:      0 create, 0 delete, 0 update, 0 noop, 0 exists
	    | Wait to: 0 reconcile, 0 delete, 0 noop
	    | Succeeded
10:51:59PM: App reconciled

Succeeded
```

**Comment by 100mik** [comment]
@voor the output should be exactly what you're expecting to see. 
Let me try and reproduce this and take a closer look 🚀
