### ISSUE TITLE
`kctrl` : Progress tailing for repo add and delete. 

### ISSUE THREAD

**Issue by 100mik** [carvel-dev/kapp-controller#671]
**Describe the problem/challenge you have**
`kctrl` should tail the status of a PackageRepo similar to App and PackageInstall status tailing

**Describe the solution you'd like**
A tail similar to App tailing which illustrates reconciliation progress

**Acceptance criteria**
- [ ] Repository statuses are tailed while reconciling/deleting
- [ ] Errors that might happen are surfaced
- [ ] Can we indicate packages that are shared between repositories better? (ongoing work by @joe-kimmel-vmw )
- [ ] `kick`, `status` and `pause` commands for PackageRepository
- [ ] Tests

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by 100mik** [comment]
@joe-kimmel-vmw I believe we were iterating over a lot of PackageRepo stuff.
Especially, regarding shared pakages and how they are created on the cluster.
This can go ahead once we have sort of decided on that and maybe when the information surfaced by the status field is "stable"
Feel free to add anything relevant that will help here!

**Comment by cppforlife** [comment]
we are not changing status API for PackageRepository CR as part of above mentioned work.
