### ISSUE TITLE
`kctrl`: disallow use of shared namespaces while installing packages

### ISSUE THREAD

**Issue by 100mik** [carvel-dev/kapp-controller#672]
**Describe the problem/challenge you have**
`kctrl` should not allow installation of packages into shared namespaces

**Describe the solution you'd like**
This could be disabled by default and we could add a dangerous flag overriding this behaviour.

**Anything else you would like to add:**
- [ ] disallow use of shared namespaces for installation
- [ ] Add a flag which accepts comma seperated values where packages can be installed to override this behaviour, similar to `--dangerous-allow-use-of-shared-namespace=default,kube-public`

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by 100mik** [comment]
@cppforlife could you elaborate between the motivation behind this? And how this helps?
Thanks!

**Comment by cppforlife** [comment]
we want to discourage users from using default namespace since it's not a good idea to keep sensitive configurations (service accounts, PackageInstall configuration, etc) in it. (it's commonly seen as a "shared" namespace.)
