### ISSUE TITLE
determine better way to delete App CR when destination cluster is gone/disconnected

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#71]
**Describe the problem/challenge you have**

in cases when App CR no longer has access to service account (e.g. remote cluster is deleted, disconnected), we dont have a natural way to delete App CRs. one "solution" today is to initiate deletion and then delete finalizer. this feels more like a hack.

**Describe the solution you'd like**

not sure. suggestions previously were:
- add force delete flag of sorts (may be annotation, etc)

**Anything else you would like to add:**

this issue may arise also when service account resource is deleted before App CR (so not just in the cases of remote cluster).

**Comment by danielhelfand** [comment]
Closed by #146
