### ISSUE TITLE
The "source <(kctrl completion bash)" command outputs an error message

### ISSUE THREAD

**Issue by itaytalmi** [carvel-dev/kapp-controller#717]
**What steps did you take:**
[A clear and concise description steps and any files that can be used to reproduce the problem.]

Added `source <(kctrl completion bash)` to my `/etc/profile` so it would automatically load.

To reproduce the issue, you can simply run `source <(kctrl completion bash)`.

**What happened:**
[A small description of the result]

Got the following error message:

```text
Succeeded: command not found
```

This is because the `kctrl completion bash` commands outputs a `Succeeded` string at the end, which is not a valid command, and when used with `source`, bash tries to execute it.

Bash completion does work, though.

**What did you expect:**
[A description of what was expected]

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

As a workaround, I'm using the following:

```bash
source <(kctrl completion bash | grep -v Succeeded)
```

This removes the `Succeeded` string from the output, so the error doesn't occur.

Same issue has also occurred with kapp before, as I described here:
https://github.com/vmware-tanzu/carvel-kapp/issues/447
In kapp, this issue was fixed using the `--tty=false` option.

Same issue also occurs in imgpkg, as I described here:
https://github.com/vmware-tanzu/carvel-imgpkg/issues/342

This issue doesn't occur with ytt, because `ytt completion bash` doesn't output the `Succeeded` string.

**Environment:**

- kctrl version (use `kctrl --version`): `0.36.1`
- OS (e.g. from `/etc/os-release`): Using `Linux Ubuntu 20.04.4 LTS (Focal Fossa)` and `macOS Monterey 12.2.1`, but this issue occurs on any bash.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment]
@itaytalmi Thanks for creating the issue. We are working on improving the tty experience and hopefully this will get fixed along with that, if not, we will make the same fix done in kapp.
