### ISSUE TITLE
PackageRepository’s Cannot Be Fetched From Git

### ISSUE THREAD

**Issue by nebhale** [carvel-dev/kapp-controller#739]
**What steps did you take:**
Given the following CR:

```yaml
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: test
spec:
  fetch:
    git:
      url: https://github.com/vmware-tanzu/community-edition
      ref: origin/main
      subPath: addons/packages
```

**What happened:**
The CR fails to reconcile with the following `usefulErrorMessage`:

```plain
ytt: Error: Checking file '/etc/kappctrl-mem-tmp/kapp-controller-fetch-template-deploy1183788892/0/packages': lstat /etc/kappctrl-mem-tmp/kapp-controller-fetch-template-deploy1183788892/0/packages: no such file or directory
```

**What did you expect:**
I expected the `Package` and `PackageMetadata` CRs defined [here](https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages) to be created within the cluster.

**Anything else you would like to add:**
Nothing additional.

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`):
```yaml
kbld.k14s.io/images: |
  - origins:
    - local:
        path: /home/runner/work/carvel-kapp-controller/carvel-kapp-controller
    - git:
        dirty: false
        remoteURL: https://github.com/vmware-tanzu/carvel-kapp-controller
        sha: e0d5ff2821bc65ba2cbe11077b51e87135c96b24
        tags:
        - v0.38.1
    url: ghcr.io/vmware-tanzu/carvel-kapp-controller@sha256:a6cd018f365ab138ebc9f7d414513ec26418ce35b1ce3e8efe644ee1ab513f3a
```
- Kubernetes version (use `kubectl version`)
```plain
$ kubectl version                                                                             
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```
---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
it's currently expected that there would be packages directory under given "root" of pkg repo. in your case you can change `subPath: addons/packages` => `subPath: addons/`. we seem to only have this documented under pkg repo bundle: https://carvel.dev/kapp-controller/docs/v0.38.0/packaging-artifact-formats/#package-repository-bundle, but as of now that's a generic restriction.

**Comment by cppforlife** [comment]
(just for the record https://github.com/vmware-tanzu/community-edition 's addons directory is not meant to be consumed as a pkg repo -- pkg repo should only contain PackageMetadata and Package CRs, however, in TCE's case there are actually contents of individual packages stored in those directories.)

**Comment by nebhale** [comment]
Understood on the directory restriction being across all fetches (feels like some doc polishing would be useful there).

For clarity on the “should only contain…” statement, why? Is there some concrete misbehavior when the controller encounters files containing things other than the CR’s it was expecting?  I’d kind of assumed that it’d follow [Postel’s Law](https://en.wikipedia.org/wiki/Robustness_principle) and ignore things that it wasn’t looking for.

**Comment by cppforlife** [comment]
> Is there some concrete misbehavior when the controller encounters files containing things other than the CR’s it was expecting?

it should in theory ignore things that it doesnt know about (this was done for backwards/forward-compatibility) but there is no way to gurantee that while its recursively collecting yml files, it wont find something that is meaningful to it (e.g. Package/PackageMetadata CR), but not actually intended to be included (e.g. if there are some development related Package CRs in those directories).

**Comment by nebhale** [comment]
Understood on the dangers of finding something meaningful but not intended for inclusion.  Thanks for the clarification.
