### ISSUE TITLE
issue with Contour app

### ISSUE THREAD

**Issue by AkhilCh308** [carvel-dev/kapp-controller#74]
**What steps did you take:**
[A clear and concise description steps that can be used to reproduce the problem.]

kubectl apply -f ingress/contour/namespace-role.yaml
kubectl create secret generic contour-data-values --from-file=values.yaml=ingress/contour/vsphere/contour-data-values.yaml -n tanzu-system-ingress-4
kubectl apply -f ingress/contour/contour-extension.yaml
kubectl get app contour -n tanzu-system-ingress

**What happened:**
[A small description of the issue]
root@tkg [ ~ ] tkg12workloadcluster-01-admin@tkg12workloadcluster-01:default) # k get app contour -n tanzu-system-ingress-4
NAME      DESCRIPTION   SINCE-DEPLOY   AGE
contour   Reconcile failed: Fetching (0): Fetching registry image: Imgpkg: exit status 1 (stderr: Error: Collecting images: Working with registry.tkg.vmware.run/tkg-extensions-templates:v1.2.0_vmware.1: Get https://registry.tkg.vmware.run/v2/: dial tcp: i/o timeout
)                       64m

**What did you expect:**
[A description of what was expected]
NAME      DESCRIPTION           SINCE-DEPLOY   AGE
contour   Reconcile succeeded   15s            72s

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`):
- Kubernetes version (use `kubectl version`)

**Comment by cppforlife** [comment]
> Get https://registry.tkg.vmware.run/v2/: dial tcp: i/o timeout

this error message indicates that it cannot reach above registry. (it's making a call to that registry from within kapp-controller pod).

**Comment by AkhilCh308** [comment]
Hi @cppforlife , yeah I knew that, can you pls suggest any steps to fix this?

**Comment by cppforlife** [comment]
@AkhilCh308 you'll have to figure out how to allow TCP connections between your environment and that location. im guessing somehow your network rules block such request.

**Comment by cppforlife** [comment]
going to close this issue per my above comment.
