### ISSUE TITLE
kctrl: should have command to trigger immediate reconciliation attempt on a given package

### ISSUE THREAD

**Issue by kartiklunkad26** [carvel-dev/kapp-controller#788]
**Describe the problem/challenge you have**
When troubleshooting a deployment, we often need to wait several minutes for a reconciliation attempt on the packageinstall we want to reconfigure. 

**Describe the solution you'd like**
If we had a "kctrl package installed trigger-reconciliation " command that simply paused and unpaused the underlying relevant reconciler we could short-circuit this delay.

**Anything else you would like to add:**
@markfynes has raised this issue, in case we want to reach out for further conversations. 

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by 100mik** [comment]
Heyo!

`kctrl package installed kick -i installation-name` would do exactly this

**Comment by 100mik** [comment]
Worth noting that it was brought up that the command `kick` might not be the most obvious name.
But the help section should help with that.

Do you think this was inaccessible/ not easy to find?

**Comment by kartiklunkad26** [comment]
I think this was a miss because it wasn't available in the downstream commercial CLI. Closing given we have this capability in kctrl.
