### ISSUE TITLE
unable to retrieve the complete list of server APIs: data.packaging.carvel.dev/v1alpha1

### ISSUE THREAD

**Issue by leonard520** [carvel-dev/kapp-controller#790]
**What steps did you take:**
I met the error for several times but I am not sure what the exact reproduce step is. This time, I can only remember I was updating the secret of the package repo. After several rounds of `UNAUTHORIZED: authentication required,` (which could because I am using a wrong credential to the container registry), I am able to correct the secret. However, then the package repo still reconciled failed and left this error message.
`        kapp: Error: unable to retrieve the complete list of server APIs: data.packaging.carvel.dev/v1alpha1: the server is currently unable to handle the request (possibly related issue: https://github.com/vmware-tanzu/carvel-kapp/issues/12)`

According to my previous experience, the deletion of kapp controller pod can get it recovered. This time, it still works.

I think the above reproduce step may not be so useful. At least in the last time I saw this error, I am not working on changing the secret.

**What happened:**
The reconcile of package repo failed

**What did you expect:**
It should reconcile success

**Anything else you would like to add:**
I think the issue is very similar to https://github.com/vmware-tanzu/tanzu-framework/issues/571
During the error `        kapp: Error: unable to retrieve the complete list of server APIs: data.packaging.carvel.dev/v1alpha1: the server is currently unable to handle the request (possibly related issue: https://github.com/vmware-tanzu/carvel-kapp/issues/12)` exists, I tried to list packages manually but failed.
```
kubectl get package
error: the server doesn't have a resource type "package"
```

I am pretty sure that before the error happens, I am able to list the packages by the same command.

So I try to use `kubectl proxy` to manually check the api, when visiting `http://localhost:8001/apis/data.packaging.carvel.dev/v1alpha1` I see the below error message
`error trying to reach service: x509: certificate signed by unknown authority`
The information above could be useful because after I manually delete the kapp controller pod and everything recovers, the uri can return the list of packages correctly.

Does it mean I miss something in installation or so?

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`):
0.38.4
- Kubernetes version (use `kubectl version`)
1.22

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
@leonard520 how are you installing kapp-controller? via kapp deploy?

**Comment by joe-kimmel-vmw** [comment]
@leonard520 This is unusual -- usually if an issue of the packaging APIs being unavailable is reported, there's absolutely no communication possible between the kubernetes API server and the kapp-controller extension API server. Those issues are generally due to the network being locked down in a way that prevents communication entirely.  I'm not aware of anything that can cause the kind of intermittent outage you're describing!  Please tell us more about how you're installing and configuring kapp-controller and kubernetes?

**Comment by leonard520** [comment]
I am using k8s api to install kapp-controller and I am not able to reproduce it recently. I think we can close the bug now and re-open if it happens again. Thanks for looking into it!
