### ISSUE TITLE
Convert Kapp-controller's own deployment to use ytt schemas

### ISSUE THREAD

**Issue by joe-kimmel-vmw** [carvel-dev/kapp-controller#797]
**Describe the problem/challenge you have**
they're clean, sleek and modern

**Describe the solution you'd like**
[A clear and concise description of what you want to happen. If applicable a visual representation of the UX.]

**Anything else you would like to add:**
This work could be seen as peeling of a pre-requisite for : https://github.com/vmware-tanzu/carvel-kapp-controller/issues/774

so if it doesn't get done as a standalone work item then it will get done with #774 is tackled.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joe-kimmel-vmw** [comment]
Thank you @joe-kimmel-vmw for submitting this issue!  We appreciate your contributing to our community.

**Comment by neil-hickey** [comment]
will be done as part of https://github.com/vmware-tanzu/carvel-kapp-controller/pull/926
