### ISSUE TITLE
kapp-controller works on OpenShift + vSphere

### ISSUE THREAD

**Issue by aaronshurley** [carvel-dev/kapp-controller#810]
**Describe the problem/challenge you have**
We want to ensure that kapp-controller's basic functionalities work on OpenShift + vSphere.

**Describe the solution you'd like**
We discussed as a team that the following plan would be sufficient:
1. Obtain an environment running on OpenShift + vSphere.
2. Run the e2e tests.
    1. If the tests succeed, we're done.
    2. If the tests fail, create issues to resolve specific problems.

**Anything else you would like to add:**

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joe-kimmel-vmw** [comment]
it looks like the pipeline  we have for creating this isn't working at all right now.  We can try again or just wait:


 Bootstrap failed to complete: timed out waiting for the condition 
[31mERROR[0m Failed to wait for bootstrapping to complete. This error usually happens when there is a problem with control plane hosts that prevents the control plane operators from creating the control plane.

**Comment by joe-kimmel-vmw** [comment]
I ran our e2e tests against a OS+VS cluster. at a high level the following tests failed:
```
--- FAIL: Test_AppStatus_DisplaysUsefulErrorMessage_ForDeploymentFailure (15.16s)
--- FAIL: TestConfig_TrustCACerts (629.54s)
--- FAIL: TestConfig_SkipTLSVerify (629.33s)
--- FAIL: Test_App_FetchPath (674.72s)
    --- FAIL: Test_App_FetchPath/Multiple_Fetch_-_path (651.42s)
--- FAIL: TestGitHttpsPublic (649.84s)
--- FAIL: TestGitSshPrivate (614.34s)
```

The suite itself also timed out towards the end?  you can see above that a lot of these tests' failure mode is that they time out and i think we might've hit a suite-wide timeout.     

It does look like the common thread is kind of "credentials and trust stuff is handled differently in openshift" .   ~I'm going to try to run the test suite a second time.~ unfortunately the cluster seems a little bit bricked after the test failures so i'll have to see i can debug what's changed on it.

**Comment by joe-kimmel-vmw** [comment]
confirmed from a user that packaging apis are working in this environment.

**Comment by joe-kimmel-vmw** [comment]
I think this is maybe a complete list of which e2e tests fail repeatedly and independently against openshift : 


~--- FAIL: TestConfig_HTTPProxy (0.46s)~
~--- FAIL: TestConfig_KappDeployRawOptions (7.64s)~ -- passes on kc 0.40
--- FAIL: Test_App_FetchPath (6.05s)
    --- FAIL: Test_App_FetchPath/Single_Fetch_-_path_given (6.05s)
~--- FAIL: TestGitHttpsPublic (6.22s)~
--- FAIL: TestGitSshPrivate (459.37s)
--- FAIL: TestHelm (6.53s)
    --- FAIL: TestHelm/Helm_v3_(chart_spec_v2)_deployment (6.53s)
--- FAIL: TestHTTP (6.45s)
--- FAIL: TestHTTPSSelfSignedCerts (459.87s)
--- FAIL: Test_FetchAndDeployImgpkgBundle_Successfully (5.95s)
--- FAIL: TestImgpkgBundleSkipTLSVerify (237.66s)
--- FAIL: Test_PackageInstalled_FromPackageInstall_Successfully (7.85s)
--- FAIL: Test_PackageInstalled_FromPackageInstall_DeletionFailureBlocks (1.17s)

**Comment by joe-kimmel-vmw** [comment]
--- FAIL: TestGitHttpsPublic (6.22s)
 this test fails because it fetches an app over Git+HTTPS and the app fails to install.  the fetch works, so the test "succeeds" at the important part,  but it fails because the app is a redis installation that hasn't been openshifted.

**Comment by joe-kimmel-vmw** [comment]
TestGitSshPrivate.  Fails to deploy its private git server on Openshift so the test can never run.

      5:29:26PM: ongoing: reconcile deployment/git-server (apps/v1) namespace: kappctrl-test
        5:29:26PM:  ^ Waiting for 1 unavailable replicas
        5:29:26PM:  L ok: waiting on replicaset/git-server-7944646467 (apps/v1) namespace: kappctrl-test
        5:29:26PM:  L ongoing: waiting on pod/git-server-7944646467-b56bv (v1) namespace: kappctrl-test
        5:29:26PM:     ^ Pending: ErrImagePull (message: rpc error: code = Unknown desc = reading manifest xenial in docker.io/library/ubuntu: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit)

**Comment by joe-kimmel-vmw** [comment]
HelmTests use the same redis package which can't install on openshift.

**Comment by neil-hickey** [comment]
Thanks for testing it out @joe-kimmel-vmw , we can take it from here :D
