### ISSUE TITLE
Integration with Open Service Mesh

### ISSUE THREAD

**Issue by leonard520** [carvel-dev/kapp-controller#823]
Usually, service mesh injects a sidecar to pod/deployment to manage traffic/certificate. However, I find Carvel will reconcile and remove the sidecar. I am wondering if there is a way to make the packages managed by Carvel to co-work with service mesh? Thanks.

**Comment by praveenrewar** [comment]
Hi @leonard520! You can use [kapp rebase rules](https://carvel.dev/kapp/docs/v0.51.0/config/#rebaserules) to copy fields from the resources present in cluster so that it doesn't get removed in further reconciliations.

**Comment by cppforlife** [comment]
@leonard520 insertion of sidecar should happen during "save cycle" (via webhooks). fields added as part of the save cycle are not considered as changes by kapp (unless something else changes on the resources after the save cycle completes).

**Comment by leonard520** [comment]
Thanks for the quick response. I think I find the reason why the sidecar is removed. I am using https://openservicemesh.io/ and it will add an annotation to the namespace that enable auto sidecar injection. However, the annotation should be removed by reconciling so OSM think it shouldn't do sidecar injection. I will take a look at @praveenrewar 's suggestion to see if I can keep the annotation.
@cppforlife Please correct me if it is not the reason.

**Comment by cppforlife** [comment]
> However, the annotation should be removed by reconciling so OSM think it shouldn't do sidecar injection.

yeah, if the namespace is created by a PackageInstall via kapp-controller, added annotations would be reconciled away. you can for example add this annotation (or add a rebase rule) via overlays -- https://carvel.dev/kapp-controller/docs/v0.38.0/package-install-extensions/

**Comment by neil-hickey** [comment]
Seems like this is solved via kapp rebase rules, @leonard520. Did you manage to get this working?

**Comment by leonard520** [comment]
Yes, I am able to make it works. Thanks a lot for the help.
