### ISSUE TITLE
Feedback on kctrl from `Graham Dumpleton`

### ISSUE THREAD

**Issue by rohitagg2020** [carvel-dev/kapp-controller#837]
Feedback on kctrl from `Graham Dumpleton`

- [x] [Doc] Cert-manager example misses `kctrl pkg release -v 1.0.0` command. Fixed before release.
- [x] [Doc] Add the `kctrl pkg init` command in case of cert-manager example.
- [x] [Bug] If `kctrl pkg init` is not run successfully, then running `kctrl pkg release` fail with panic. Fixed before release.
- [x] `--local` and `--build` flags are missing while running `kctrl dev` command.
- [x] [Doc] Enhance `kctrl dev` documentation. https://kubernetes.slack.com/archives/CH8KCCKA5/p1660799313014129?thread_ts=1660781243.782389&cid=CH8KCCKA5
- [x] [Doc]There are 404 errors while clicking on links.
- [x] #934
- [x] [Doc] In case a pkg init is rerun, explicitly mentions what app spec will get overwritten(of packageBuild or package in package-resources.yml).
- [x] [Code] Pkg init rerun overwrite PackageMetadata changes.
- [x] #933
- [x] [Code] `kctrl pkg release` cmd will fail with error `no .imgpkg/images.yml file` even if YAML supplied is broken
- [x] [Doc/Code] In the above scenario, creating an empty `.imgpkg/images.yml` file will make the cmd succeed but no carvel-artifacts directory is created.
- [x] [Code/Doc] `kctrl` consumer flow: PackageInstall fails as it is not able to authenticate with registry.
- [x] [Doc] Add proper documentation on creating service account and rbac for `kctrl dev` flow.  
- [x] #932
- [x] While consuming the package, it is trying to install in the default namespace. This gives the error: kctrl: Error: Creating sensitive resources in a shared namespace (default)(hint: Specify a namespace using the '-n' flag or use kubeconfig to change default namespace 'kubectl config set-context --current --namespace=private-namespace'.Or use '--dangerous-allow-allow-use-of-shared-namespace=default' to allow use of shared namespace)
- [x] #932

**Comment by 100mik** [comment]
Branched out from #831

**Comment by 100mik** [comment]
> [Doc] In case a pkg init is rerun, explicitly mentions what app spec will get overwritten(of packageBuild or package in package-resources.yml).

As of now we document the current behaviour here [here](https://carvel.dev/kapp-controller/docs/v0.40.0/kctrl-faq/#how-can-we-go-about-updating-a-package-dependent-on-an-upstream-release). Checking it off.

**Comment by 100mik** [comment]
> kctrl pkg release cmd will fail with error no .imgpkg/images.yml file even if YAML supplied is broken

Looks like a missing check on `reconcilerErr` fixing it up.

**Comment by 100mik** [comment]
> Add proper documentation on creating service account and rbac for kctrl dev flow.

We do mention this right after we show `package-resources.yml` in the tutorial. Does it need more clarity? Or needs to be highlighted more?

**Comment by 100mik** [comment]
> kctrl consumer flow: PackageInstall fails as it is not able to authenticate with registry.

This feels a lot like an environment issue, and needs a closer look

**Comment by renuy** [comment]
closing this issue as separate issues have been created for one's mentioned here
