### ISSUE TITLE
kapp-controller status Pending and never finish when deploying Unmanaged Clusters

### ISSUE THREAD

**Issue by Rocking80** [carvel-dev/kapp-controller#844]
**What steps did you take:**
I am following  [getting-started-unmanaged](https://tanzucommunityedition.io/docs/v0.12/getting-started-unmanaged/) to deploying Tanzu unmanaged cluster.
1. Install Tanzu CLI on My windows desktop
2. Deploy a cluster using `tanzu unmanaged-cluster create beepboop`

**What happened:**
In step 2, the command output hung on  `kapp-controller status: Pending` and never finish.
![image](https://user-images.githubusercontent.com/16066437/186323540-99322aa3-71aa-4ed3-ab1d-e6aca93e2f65.png)

**What did you expect:**
The cluter should be create without error.

**Anything else you would like to add:**
Is there any method to see what is going on in background. And why the kapp-controller cannot be created for such a long time (hours)?

**Environment:**

- Windows 10
- Docker Desktop on Windows: version 20.10.8, build 3967b7d
- tce-windows-amd64-v0.12.1

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
Hey @Rocking80 
If you are using windows containers, kapp-controller currently does not support it.
To look at the logs of kapp-controller you can try:
```bash
$ kubectl get pods -A
NAMESPACE         NAME                               READY   STATUS    RESTARTS   AGE
kapp-controller   kapp-controller-77c94b5f94-zdmlj   2/2     Running   0          6d17h

$ kubectl logs -n kapp-controller   kapp-controller-77c94b5f94-zdmlj
```
This should give you some logs if it is starting.

You can also execute `kubectl get pods -n kapp-controller -o yaml` this will get you information about the pods and maybe it will help diagnose is the pods are not able to standup.

**Comment by Rocking80** [comment]
Thanks @joaopapereira , if you take a look at the [getting-started-unmanaged](https://tanzucommunityedition.io/docs/v0.12/getting-started-unmanaged/) guide, it says windows is supported.

And I am using Windows (only *Docker Desktop* is needed) to deploy tanzu community, before the unmanaged cluster is deployed. The commands you show would not work yet.

```
C:\Users\>kubectl get pods -A
error: the server doesn't have a resource type "pods"
```
Someone told me the stuck is because the containerd in the *kind* image is not configured with the proxy, so images can not be pulled from within the cluster. But I don't know how to fix this.

**Comment by neil-hickey** [comment]
Hey @Rocking80 , sorry for not getting back to follow up with you sooner. Did you make it any further? Do you still need our help? :)
