### ISSUE TITLE
kctrl times out after 5min during package install

### ISSUE THREAD

**Issue by corneil** [carvel-dev/kapp-controller#847]
`kctrl package install` produces error **`kapp: Error: Timed out waiting after 5m0s for resources:`** 

I did set `--wait-timeout` to 15m but it didn't make a difference. Seems like we need `--wait-resource-timeout` to be passed to kapp.

Is there something I missed?

**Comment by praveenrewar** [comment]
Hi @corneil !

The default wait timeout in kapp is 15 minutes, but I am guessing that the package you are using sets it to 5 minutes using the rawOptions in deploy section (https://carvel.dev/kapp-controller/docs/v0.40.0/app-spec/).

**Comment by corneil** [comment]
Will that be part of the package itself?

**Comment by praveenrewar** [comment]
> Will that be part of the package itself?

Yes (https://carvel.dev/kapp-controller/docs/v0.40.0/packaging/#package).
You could probably confirm it by viewing the package that you are trying to install using kubectl.

**Comment by praveenrewar** [comment]
Hi @corneil !! Please let us know if you need more help on this, or if we can close the issue.

**Comment by corneil** [comment]
Increasing the concurrency didn't help because the controlplane was rate limiting us.

By using more clusters each with 2 to 3 nodes the load on controlplane is within bounds and we get successful deployments of many instances.

**Comment by praveenrewar** [comment]
(BTW, the error is coming in the waiting stage, so eventually, in further kapp-controller reconciliations, the package installs should come in the Reconciled Successfully state if there's no other issue)
