### ISSUE TITLE
Different Group Name for Fake Client

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#86]
When using the [fake kapp-control client](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/dee8a5beacd13c97423213dc7381917577d8505c/pkg/client/clientset/versioned/fake/clientset_generated.go#L20) for mocking interactions with a cluster, if an actual App runtime object is loaded into the NewSimpleClientset constructor, the app will never be retrieved by the fake client. 

This is due to how the [ObjectTracker](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/dee8a5beacd13c97423213dc7381917577d8505c/pkg/client/clientset/versioned/fake/clientset_generated.go#L50) works for the fake client. The ObjectTracker stores runtime objects passed into the NewSimpleClientset constructor as key-value pairs where the key is the GroupVersionResource combination and the value is a list of objects the ObjectTracker is aware of.

Since the fake client uses a group name of [`kappctrl`](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/dee8a5beacd13c97423213dc7381917577d8505c/pkg/client/clientset/versioned/typed/kappctrl/v1alpha1/fake/fake_app.go#L21) instead of `kappctrl.k14s.io`, apps created/used in tests are never located by the fake client.

It would greatly help with testing to be able to use the actual App structs in tests and load them into the fake client to replicate communicating with a cluster.

**Comment by danielhelfand** [comment]
It seems it was related to how the fake client is generated. One of the directives given to client generator had the incorrect group name: https://github.com/vmware-tanzu/carvel-kapp-controller/blob/53cbfee531155c40268ff8914f62becd15a94836/pkg/apis/kappctrl/v1alpha1/doc.go#L6.

**Comment by aaronshurley** [comment]
@danielhelfand Could you share a bit more about how this impacts your workflow now (i.e. this would save x amount of time each time we're in this test suite)? We're trying to determine when/if we should prioritize this.

**Comment by danielhelfand** [comment]
It would basically allow developers working on kapp-controller to test things in a non e2e fashion, which means less dependencies (i.e., a Kubernetes cluster, setting environment vars for tests) are needed and feedback can be received faster since the tests should run quicker. Currently, some of our e2e tests can some times take 2 minutes to run. So it can be challenging getting quick feedback when developing. Whereas writing tests with the fake client can run in seconds.

The downside of this approach is that it can't test deployment features of kapp-controller. This would really be reserved for testing where no deployment needs to take place, so we can more easily test things without going through the whole e2e flow. I think the benefits of better testing patterns that allow for quicker feedback would be very helpful. 

This is also a one line change and regenerating the client to use this new group name. Or we can manually edit the group name for the fake client and it should work.

**Comment by aaronshurley** [comment]
Thank you for the explanation. If this is low-hanging fruit then please feel free to drag it into the backlog where it makes sense.

**Comment by danielhelfand** [comment]
This has been addressed and can be closed out: https://github.com/vmware-tanzu/carvel-kapp-controller/blob/d94984a77fa907ac5ecc681e9a842b9877766a6b/pkg/apis/kappctrl/v1alpha1/doc.go#L6
