### ISSUE TITLE
kapp-controller does not show kapp associatedResources after second deploy (noop)

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#863]
**What steps did you take:**
first deploy shows status.deploy.kapp.associatedResources content correctly; however, after second reconciliation that section is gone. is it kapp that no longer reports correct info or is it kapp-controller that somehow loses it?

**What did you expect:**
status.deploy.kapp.associatedResources should continue to persist.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`):
- Kubernetes version (use `kubectl version`)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by renuy** [comment]
@praveenrewar please check from kapp perspective. 
slack thread: https://kubernetes.slack.com/archives/CH8KCCKA5/p1662672602140659

**Comment by praveenrewar** [comment]
We are saving the metadata file in a [temp directory](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/pkg/deploy/kapp.go#L55) which we remove after extracting the metadata and in kapp we [return early](https://github.com/vmware-tanzu/carvel-kapp/blob/develop/pkg/kapp/cmd/app/deploy.go#L187) when there are no changes so metadata is not saved to app-metadata file output.
I think it would make more sense to make these changes in kapp itself as we might not want to persists metadata file in kapp-controller?

Update: ^ Related [PR](https://github.com/vmware-tanzu/carvel-kapp/pull/601) in kapp.

**Comment by praveenrewar** [comment]
Fixed in kapp [v0.53.0](https://github.com/vmware-tanzu/carvel-kapp/releases/tag/v0.53.0) and kapp-controller [v0.41.2](https://github.com/vmware-tanzu/carvel-kapp-controller/releases/tag/v0.41.2)
