### ISSUE TITLE
Documentation to help package authors package and distribute their software

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#88]
**Describe the problem/challenge you have**
Once the Package Management APIs are available in kapp-controller, package authors might find it difficult to discover and start using those APIs. 

**Describe the solution you'd like**
Clear documentation (getting started guide) with examples telling authors how to use the Package Management APIs to package and distribute their software.

**Anything else you would like to add:**

**Comment by danielhelfand** [comment]
Note that these changes have been added to carvel.dev but may be updated as future release candidates are developed:
* https://github.com/vmware-tanzu/carvel.dev/pull/52
* https://github.com/vmware-tanzu/carvel.dev/blob/9fc2418d3966720fe4f77ece7a0e3785eb931779/content/kapp-controller/docs/latest/packaging.md
* https://github.com/vmware-tanzu/carvel.dev/blob/9fc2418d3966720fe4f77ece7a0e3785eb931779/content/kapp-controller/docs/latest/package-authoring.md

**Comment by vibhas** [comment]
I moved this issue to "In-Progress". One thing that still needs to be documented in the future is air-gapped workflows.

**Comment by ewrenn8** [comment]
Im going to close this and add a new issues for air gapped scenarios.

Documentation for package authors can be found at https://carvel.dev/kapp-controller/docs/latest/package-authoring/
