### ISSUE TITLE
v0.x.0: Update documentation to include imgpkg's IaaS auth updates

### ISSUE THREAD

**Issue by aaronshurley** [carvel-dev/kapp-controller#884]
**Describe the problem/challenge you have**
When we bump to the latest version of imgpkg for kapp-controller, we will need to update kapp-controller's documentation to use [the new IaaS authentication environment variables](https://carvel.dev/imgpkg/docs/v0.32.0/auth/#via-iaas).

**Describe the solution you'd like**
kapp-controller's documentation includes references to imgpkg's updated environment variable (`IMGPKG_ACTIVE_KEYCHAINS`) and does not include any references to the deprecated environment variable (`IMGPKG_ENABLE_IAAS_AUTH`).

**Anything else you would like to add:**
There's at least one reference to this env var here: https://carvel.dev/kapp-controller/docs/v0.40.0/install/#openshift

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
It is live in https://carvel.dev/kapp-controller/docs/develop/install/#openshift

**Comment by alexbarbato** [comment]
The docs don't say where you're supposed to apply this env var - is it possible to add that context please? Actually the new ones might, hold please!

I think I found it, but the docs now state to remove the env var from the sidecar (which is useful!), but I think there must be versions of kapp-controller where that's nto the case and you have to explicitly set it.

**Comment by joaopapereira** [comment]
`Remove the environment variable IMGPKG_ACTIVE_KEYCHAINS [environment variable](https://carvel.dev/imgpkg/docs/latest/auth/#via-iaas) from the deployment yaml of the sidecar container.`
This is what is in the docs. Do you think it is enough?

**Comment by alexbarbato** [comment]
I think what confused me is in my deployment (from Tanzu Cluster Essentials) that var was not there but rather it had to be applied and set to false.

And that in with the CLI hint being super useful, but it didn't tell me the sidecar bit so I kind of had to play whack a mole to find the right config.
