### ISSUE TITLE
Documentation to help package consumers install and manage their software

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#89]
**Describe the problem/challenge you have**
Once the Package Management APIs are available in kapp-controller, package consumers might find it difficult to discover and start using those APIs. 

**Describe the solution you'd like**
Clear documentation (getting started guide) with examples telling consumers how to use the Package Management APIs to install and manage software provided by authors.

**Anything else you would like to add:**

**Comment by danielhelfand** [comment]
Note that these docs have been added to carvel.dev but may be updated as future release candidates are added:
* https://github.com/vmware-tanzu/carvel.dev/blob/9fc2418d3966720fe4f77ece7a0e3785eb931779/content/kapp-controller/docs/latest/package-consumption.md

**Comment by vibhas** [comment]
I moved this issue to "In-Progress". One thing that still needs to be documented in the future is air-gapped workflows.

**Comment by ewrenn8** [comment]
Going to close this and add a new issue for airgapped scenarios

Documentation for package consumers can be found here: https://carvel.dev/kapp-controller/docs/latest/package-consumption/
