### ISSUE TITLE
CRD to package a software

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#90]
**Describe the problem/challenge you have**
Package authors do not have a consistent way to package their software which then can be distributed for consumption.

**Describe the solution you'd like**
Package authors should be able to create a new Package CR to package their software that can then be distributed for consumption by others. They should be able to define the following in this CR:
- Reference to a Package Contents Bundle (containing all the files, OCI images)
- Name and version of the package
- Authors and description
- Describe how to install the package

The Package CR can be deployed on a cluster directly or bundled in a package repository.

**Anything else you would like to add:**

**Comment by danielhelfand** [comment]
In progress on the [dev-packaging](https://github.com/vmware-tanzu/carvel-kapp-controller/tree/dev-packaging) branch. As of now, the CRD is called `Package`.

**Comment by ewrenn8** [comment]
This is available in release v0.17.0-alpha.1+.

Installation instructions for the latest alpha versions containing this can be found [here](https://carvel.dev/kapp-controller/docs/latest/install-alpha/)
Release yaml can be found [here](https://github.com/vmware-tanzu/carvel-kapp-controller/tree/dev-packaging/alpha-releases)

For tracking when this is available in a major release, please follow the [epic issue](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/87)
