### ISSUE TITLE
CRD to watch a package repository

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#91]
**Describe the problem/challenge you have**
Package consumers currently need to discover and install one software at a time on a cluster. They should have a way to watch a particular package repository that contains multiple packages so that they can discover all the packages available to them and install the ones that they need.

**Describe the solution you'd like**
- Package consumers should be able to watch a repository using kapp-controller PackageRepository CR
- They should be able to view the status of a repository (Broken to a different issue https://github.com/vmware-tanzu/carvel-kapp-controller/issues/109)
- Once the package repository CR is deployed, all the packages in the repository should be available on the cluster
- They should be able to view the list of repositories that are being watched 

**Anything else you would like to add:**

**Comment by danielhelfand** [comment]
In progress on the [dev-packaging](https://github.com/vmware-tanzu/carvel-kapp-controller/tree/dev-packaging) branch. As of now, the CRD is called PackageRepository. 

One thing that might need a bit more refinement is what a PackageRepository status should report for this requirement:
> They should be able to view the status of a repository

**Comment by vibhas** [comment]
> One thing that might need a bit more refinement is what a PackageRepository status should report for this requirement.

A new issue has been created for this https://github.com/vmware-tanzu/carvel-kapp-controller/issues/109

**Comment by ewrenn8** [comment]
This is available in release v0.17.0-alpha.1+.

Installation instructions for the latest alpha versions containing this can be found [here](https://carvel.dev/kapp-controller/docs/latest/install-alpha/)
Release yaml can be found [here](https://github.com/vmware-tanzu/carvel-kapp-controller/tree/dev-packaging/alpha-releases)

For tracking when this is available in a major release, please follow the [epic issue](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/87)
