### ISSUE TITLE
View all the packages available on a cluster

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#92]
**Describe the problem/challenge you have**
Once one or more packages are available to install, the package consumer will need a way to be able to view the list of packages and their metadata.

**Describe the solution you'd like**
We need to provide a way such that package consumers can achieve the following:
- View packages available in a cluster 
- Search for packages by name and version (Broke it into a different issue https://github.com/vmware-tanzu/carvel-kapp-controller/issues/111)
- View the details/metadata of a particular package

**Anything else you would like to add:**

**Comment by danielhelfand** [comment]
In progress on the [dev-packaging](https://github.com/vmware-tanzu/carvel-kapp-controller/tree/dev-packaging) branch.

**Comment by ewrenn8** [comment]
This is available in release v0.17.0-alpha.1+.

Installation instructions for the latest alpha versions containing this can be found [here](https://carvel.dev/kapp-controller/docs/latest/install-alpha/)
Release yaml can be found [here](https://github.com/vmware-tanzu/carvel-kapp-controller/tree/dev-packaging/alpha-releases)

For tracking when this is available in a major release, please follow the [epic issue](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/87)
