### ISSUE TITLE
kctrl package release: error at ytt phase

### ISSUE THREAD

**Issue by matteo-magni** [carvel-dev/kapp-controller#927]
**What steps did you take:**
- create Carvel package with some ytt logic that does `assert.fail`based on some validation of input values
- run `kctrl package release` against this package

**What happened:**
`kctrl` v0.40.0 goes through, v0.41.2 fails because no input values have been provided to `ytt`

**What did you expect:**
Input values will never be submitted to `kctrl package release` because they're not part of the package itself. Instead, they should be provided by the user in order to install such a package.

**Anything else you would like to add:**

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`): v0.38.4_vmware.1
- Kubernetes version (use `kubectl version`): v1.23.10-eks-15b7512

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by rohitagg2020** [comment]
@matteo-magni I have tried it and it seems ytt failed in version `0.40.0` as well. But `kctrl pkg release` continue to move onto next step. From version `0.41.2`, kctrl exits in case ytt throws an error.

Can you confirm this behavior?

**Comment by matteo-magni** [comment]
@rohitagg2020 Yes, exactly. `ytt` version is the same in both scenarios and it actually does fail if I run it over my code without the values, but it seems that `kctrl` v0.40.0 doesn't care.

**Comment by rohitagg2020** [comment]
We have received the feedback after v0.40.0 release to handle and propagate the errors. I will close this issue if there is no action item.

**Comment by renuy** [comment]
@rohitagg2020 , if we know the PR for the issue, we could link it here and mark this as done?

**Comment by rohitagg2020** [comment]
Related PR: https://github.com/vmware-tanzu/carvel-kapp-controller/pull/834
