### ISSUE TITLE
kctrl: Adding comments to the generated package-build and package-resources.yml.

### ISSUE THREAD

**Issue by rohitagg2020** [carvel-dev/kapp-controller#932]
Adding comments to the generated package-build and package-resources.yml.

This will make end user understand better the purpose of each file and section in them

**Comment by ThomasVitale** [comment]
This might be a duplicate of https://github.com/vmware-tanzu/carvel-kapp-controller/issues/959

**Comment by 100mik** [comment]
Looks like it, maybe we should keep the newer one.
We should update the existing one with the information that we should also ensure that comments added by user are not overwritten.

**Comment by 100mik** [comment]
Clarification: the intention of this issue was to actually add comments to the boilerplate that we generate. We are still unsure about when we will get around to this.
Adding this back to triage.

**Comment by rohitagg2020** [comment]
Duplicate issue: https://github.com/carvel-dev/kapp-controller/issues/959
