### ISSUE TITLE
kctrl:[Doc] Define what app spec will get overwritten(of packageBuild or package) in case of `pkg init rerun`.

### ISSUE THREAD

**Issue by rohitagg2020** [carvel-dev/kapp-controller#934]
Define what app spec will get overwritten(of packageBuild or package) in case of pkg init rerun. #

**Comment by 100mik** [comment]
@rohitagg2020 is this something that we still need to track?
I am guessing we are saying that we should call out which parts of boilerplate get rewritten?

Could you elaborate on the case?
