### ISSUE TITLE
CRD to install a package on the cluster

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#94]
**Describe the problem/challenge you have**
Once the packages are available on a cluster, the package consumers need a way to install a specific version of the package and provide their own configurations.

**Describe the solution you'd like**
Package consumers should be able to create a kapp-controller InstalledPackage CR to install a package. They need to provide the following information:
- Name of the package
- Version of the package (exact match or loose match such as latest or constraints based on semver)
- Configuration for the package

Also, once the changes are executed, the consumer should be able to check the status of the installed package.
Note that any dependent packages must be deployed manually by creating individual InstalledPackage CRs.

**Anything else you would like to add:**

**Comment by danielhelfand** [comment]
In progress on the [dev-packaging](https://github.com/vmware-tanzu/carvel-kapp-controller/tree/dev-packaging) branch. As of now, the CRD is called `InstalledPackage`.

**Comment by ewrenn8** [comment]
This is available in release v0.17.0-alpha.1+.

Installation instructions for the latest alpha versions containing this can be found [here](https://carvel.dev/kapp-controller/docs/latest/install-alpha/)
Release yaml can be found [here](https://github.com/vmware-tanzu/carvel-kapp-controller/tree/dev-packaging/alpha-releases)

For tracking when this is available in a major release, please follow the [epic issue](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/87)
