### ISSUE TITLE
View all the installed packages on a cluster

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#95]
**Describe the problem/challenge you have**
Package consumers need visibility on the packages that are currently installed on their cluster.

**Describe the solution you'd like**
We need to provide a way such that package consumers can achieve the following:
- View the installed packages in a cluster

**Anything else you would like to add:**

**Comment by danielhelfand** [comment]
In progress on the [dev-packaging](https://github.com/vmware-tanzu/carvel-kapp-controller/tree/dev-packaging) branch.

**Comment by ewrenn8** [comment]
This is available in release v0.17.0-alpha.1+.

Installation instructions for the latest alpha versions containing this can be found [here](https://carvel.dev/kapp-controller/docs/latest/install-alpha/)
Release yaml can be found [here](https://github.com/vmware-tanzu/carvel-kapp-controller/tree/dev-packaging/alpha-releases)

For tracking when this is available in a major release, please follow the [epic issue](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/87)
