### ISSUE TITLE
Description for `kctrl dev` command in help section should also include package installs

### ISSUE THREAD

**Issue by praveenrewar** [carvel-dev/kapp-controller#964]
**What steps did you take:**
`kctrl dev -h`

**What happened:**
```
Deploy App CRs and packaging CRs

Usage:
  kctrl dev [flags]

Flags:
      --delete             Delete deployed app
  -f, --file strings       Set App CR file (required)
  -h, --help               help for dev
  -b, --kbld-build         Allow kbld build
  -l, --local              Use local fetch source
  -n, --namespace string   Specified namespace ($KCTRL_NAMESPACE or default from kubeconfig)
      --tty                Force TTY-like output

Global Flags:
      --color                       Set color output (default true)
      --column strings              Filter to show only given columns
      --debug                       Include debug output
      --json                        Output as JSON
      --kube-api-burst int          Set Kubernetes API client burst limit (default 1000)
      --kube-api-qps float32        Set Kubernetes API client QPS limit (default 1000)
      --kubeconfig string           Path to the kubeconfig file ($KCTRL_KUBECONFIG)
      --kubeconfig-context string   Kubeconfig context override ($KCTRL_KUBECONFIG_CONTEXT)
      --kubeconfig-yaml string      Kubeconfig contents as YAML ($KCTRL_KUBECONFIG_YAML)
  -y, --yes                         Assume yes for any prompt

Succeeded
```

**What did you expect:**
The description for the `dev` command should `Deploy App CRs, Package CR and PackageInstall CRs`.
Description for the `-f` flag should just be `Set file name`

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`):
- Kubernetes version (use `kubectl version`)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by ThomasVitale** [comment]
I have submitted a PR to handle this issue: https://github.com/vmware-tanzu/carvel-kapp-controller/pull/1000
