### ISSUE TITLE
kctrl: Re-running "kctrl package init" deletes info from vendir.yml

### ISSUE THREAD

**Issue by ThomasVitale** [carvel-dev/kapp-controller#966]
**What steps did you take:**
It seems that a regression has been introduce in v0.42.0 affecting the behaviour of the kctrl CLI when running `kctrl package init` a second time.

1. Get an existing Carvel package based on an upstream tool: `git clone https://github.com/arktonix/package-for-knative-eventing.git`
2. Navigate to the package directory: `cd package`
3. Run `kctrl package init`

**What happened:**
The upstream repository name and version are deleted from the `vendir.yml` file and I'm asked to insert them again via the CLI.

**What did you expect:**
The `kctrl package init` command should use the information already provided and stored in `vendir.yml` and `package-build.yml`, just like it used to do in previous versions.

**Anything else you would like to add:**
I noticed that the CLI works correctly when the upstream manifests come from a Git repository source (option 4). Instead, it doesn't work correctly when the source is a GitHub release (option 2), resulting in the `vendir.yml` info being deleted.

**Environment:**

- kapp Controller version: v0.42.0
- Kubernetes version (use `kubectl version`): v1.25.3

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by 100mik** [comment]
The expected behaviour is that `init` will load defaults from the file.
If run with the `--yes` flag, it will simply use the defaults instead of prompting the user.

I am going to verify this ^

Another issue that @mamachanko pointed out is that `kctrl` overwrites comments and rearranges keys in PackageBuild when the user runs init/release. This is something we will be creating an issue for

**Comment by 100mik** [comment]
@ThomasVitale looks like it is a regression :( 
Gonna take a closer look at it (the other issue I mentioned is unrelated)

**Comment by ThomasVitale** [comment]
@100mik thanks for looking into this issue.
