### ISSUE TITLE
Update the installed package when a newer version of the package is available

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#97]
**Describe the problem/challenge you have**
When a newer version of a package is available on the cluster, Package consumers should be able to install the new version on their cluster.

**Describe the solution you'd like**
Package consumers should be able to update the InstalledPackage CR to point to the newer version of the package in order to deploy it.

**Anything else you would like to add:**

**Comment by danielhelfand** [comment]
In progress on the [dev-packaging](https://github.com/vmware-tanzu/carvel-kapp-controller/tree/dev-packaging) branch.

**Comment by ewrenn8** [comment]
This is available in release v0.17.0-alpha.1+.

Installation instructions for the latest alpha versions containing this can be found [here](https://carvel.dev/kapp-controller/docs/latest/install-alpha/)
Release yaml can be found [here](https://github.com/vmware-tanzu/carvel-kapp-controller/tree/dev-packaging/alpha-releases)

For tracking when this is available in a major release, please follow the [epic issue](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/87)
